### ISSUE TITLE
missing history file (?) leads to exception and xonsh failing to start

### ISSUE THREAD

**Issue by arielf** [scopatz/xonsh#1000]
Thanks for xonsh.  It looks very promising.

Issue:
```
$ xonsh
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/xonsh/main.py", line 180, in main
    args = premain(argv)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/main.py", line 165, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/shell.py", line 76, in __init__
    self._init_environ(ctx, config, rc)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/shell.py", line 116, in _init_environ
    self.execer = Execer(config=config)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/execer.py", line 40, in __init__
    load_builtins(execer=self, config=config)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/built_ins.py", line 780, in load_builtins
    ts=[time.time(), None], locked=True)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/history.py", line 268, in __init__
    with open(self.filename, 'w', newline='\n') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/.local/share/xonsh/xonsh-328aa1da-e158-4be1-af29-1f90be87a349.json'
```

I managed to work around this issue by adding a `try: ... except: pass` around the:
      `with open(self.filename, 'w', newline='\n') as f:`

in line 268 of `/usr/local/lib/python3.5/dist-packages/xonsh/history.py`

**Comment by scopatz** [comment]
Hey @arielf! Thanks for reporting this! Would you mind opening up a PR with this change please?

**Comment by arielf** [comment]
@scopatz Will do.   My fix was the wrong fix though.  It was intended just as a brute-force workaround.

I figured that the failure was because ~ isn't expanded to the user home dir so a better (and probably not best) solution is to call `os.path.expanduser()` on `data_dir`, which also avoids the exception, but this is still not the right fix, since I don't get history preserved between sessions (is that intentional?).

Let me look into this more.  Thanks.

**Comment by scopatz** [comment]
Thanks a ton @arielf. I *really* appreciate it!

**Comment by gforsyth** [comment]
Hey @arielf -- quick question for you: when you say you don't have history preserved between sessions, do you mean concurrent sessions or sequential ones?

**Comment by arielf** [comment]
Sequential ones.

Looks like there are multiple code-paths were ~/ still isn't being expanded.

To help reproduce:  I have this since the configuration phase:
 In `~/.config/xonsh/config.json`:
```

 "env": {
  "XDG_DATA_HOME": "~/.local/share",
  "XONSH_DATA_DIR": "~/.local/share/xonsh"
 },
 "foreign_shells": [
  {
   "shell": "bash"
  }
 ]
}
```

And it may be the root cause of the issue.

**Comment by scopatz** [comment]
Oh yeah, we should probably add expand_path() calls to the validators of these and related envvars.
