### ISSUE TITLE
Tab-completing .. does not append / because Ellipsis exists.

### ISSUE THREAD

**Issue by ivh** [scopatz/xonsh#101]
When trying to type "cd ../.." or similar, I use TAB to get the forward slash. This does not work in xonsh because the three-dot Ellipsis exists as an option.

I understand that this might be just me, but it's highly annoying. :)

BTW, del(...) causes ValueError: expression which can't be assigned to in Del context

**Comment by scopatz** [comment]
This should be as simple as removing the `... ` case from completer.py

**Comment by ivh** [comment]
You mean from the XONSH_TOKENS list? This seems to remove ..., yes, but there seem to be two .. so the slash still does not get appended.

**Comment by ivh** [comment]
... and when I remove .. from that list as well, it *does* get completed, but with a blank instead of a slash.

(I won't have time to look at this today, just thought I'd get it out there.)

**Comment by scopatz** [comment]
OK @ivh - well whenever you get a chance, unless some one beats you to it. Just wanted to let you know that I am very open to this change.

**Comment by scopatz** [comment]
This change has been implemented at some point.  Feel free to reopen if it hasn't been.

**Comment by ivh** [comment]
I just tried (with master) and .. does not get its slash tab-appended, same as before. Still for the same reasons, I think, there is the ellipsis and a second instance of ..

**Comment by wrywerytwreywery** [comment]
I am planning on working a little bit on tab competion today (to try to deal with names with spaces more appropriately), so I can try to figure out this problem while I am working on that (unless you want to go for it, @ivh).

**Comment by ivh** [comment]
Please do @wrywerytwreywery, I don't have time for this soon. :)
