### ISSUE TITLE
&& and || operators in subprocess mode

### ISSUE THREAD

**Issue by Cheaterman** [scopatz/xonsh#1024]
Hello,

Yet && is being interpreted as two backgrounding characters, and || as two contiguous pipes, which of course doesn't work.

It would be great if things like ```true && echo Owiii``` or ```false || echo Onooo``` would work!

Thanks in advance!

**Comment by Cheaterman** [comment]
Yay 2¹⁰ issues ^__^

**Comment by adqm** [comment]
Something is weird about that particular input (perhaps because it is valid python?).  This works with certain other arguments:

```
hartz@tabby-3 ~ $ echo "hi" || echo "hello"
hi
hartz@tabby-3 ~ $ echo "hi" && echo "hello"
hi
hello
```

Three ways around this that I can see:

* put the whole path to `true`,
* use the Python `True` (though this has an interesting side effect in the interactive prompt), or
* manually wrap `true` with `![]` to force running it in subproc mode.

```
hartz@tabby-3 ~ $ /bin/true || echo "hi"
hartz@tabby-3 ~ $ /bin/true && echo "hi"
hi
hartz@tabby-3 ~ $ ![true] || echo "hi"
hartz@tabby-3 ~ $ ![true] && echo "hi"
hi
hartz@tabby-3 ~ $ True || echo "hi"
True
hartz@tabby-3 ~ $ True && echo "hi"
hi
```

**Comment by Cheaterman** [comment]
Funny, thanks! It would be even better if what I wrote worked though, would that be possible somehow?

**Comment by Cheaterman** [comment]
Oh, also most of the things you mention don't work in 0.2.7. My ```true && echo owi``` example seems to work fine in 0.3.0, like your other examples. Thanks!

**Comment by scopatz** [comment]
Hi @Cheaterman - just to be clear, you mean `True && echo owi`, with a capital `T` right?

**Comment by adqm** [comment]
That said, something does seem to be amiss with the auto-escaping here (`subproc_toks`?).

`true`, when run on its own, is escaped as `![true]`, as we might expect.

`true && echo "hi"`, though, is escaped as `true && ![echo "hi"]` (without escaping the `true`), and then the second piece gets double-wrapped as `![![echo "hi"]]`

@scopatz, is this expected, or is that a bug?

**Comment by scopatz** [comment]
This looks like a bug and a regression. I thought I had tests for this case.  I'll reopen and investigate now.

**Comment by scopatz** [comment]
Ok I think I have figured it out.  This stuff is super tricky.

**Comment by Cheaterman** [comment]
Wow congratulations, thanks a lot! I had closed it because my test case behaved as expected in 0.3.0 (as opposed to 0.2.7 which I was using when I reported).
