### ISSUE TITLE
Commands that start with punctuation give syntax errors

### ISSUE THREAD

**Issue by mattbowen** [scopatz/xonsh#1044]
Using xonsh/0.3.0 from pypi, OS X 10.10.5, Python 3.5.1 via homebrew.

Following Brandon Rhodes, [I prefix my personal shell commands (scripts, aliases, and functions) with a comma](http://rhodesmill.org/brandon/2009/commands-with-comma/). This works fine in bash/zsh, but results in a syntax error in xonsh.

Example:

In zsh
`⌁ [matthew:~] % ls -la ~/.bin | grep ,`
`-rwxr--r--    1 matthew  staff    28 May 30 10:37 ,demo`
`⌁ [matthew:~] % ,demo`
`I work!`

In xonsh

`matthew@Matthews-MacBook-Pro ~ $ ,demo`
`................................`
`  File "<string>", line None`
`SyntaxError: <xonsh-code>:1:0: ('code: ,',)`

The problem occurs in scripts and aliases; I haven't been able to source most of my zsh functions, so I can't verify there.

**Comment by melund** [comment]
Hi @mattbowen It may have been fixed with 0.3.1. https://github.com/scopatz/xonsh/blob/master/CHANGELOG.rst

Can you try to update to the newest version? I think it is currently 0.3.2

**Comment by mattbowen** [comment]
Nice, it works! Thank you.
