### ISSUE TITLE
0.3.2 crashes on launch

### ISSUE THREAD

**Issue by HarryCutts** [scopatz/xonsh#1045]
I just upgraded my "production" xonsh installation (using `sudo pip3 install --upgrade xonsh`) to 0.3.2, and started getting the following crash when I tried to run it:

```
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.2', 'console_scripts', 'xonsh')()
  File "/home/harry/.local/lib/python3.4/site-packages/setuptools-7.0-py3.4.egg/pkg_resources.py", line 339, in load_entry_point
    run_main = run_script   # backward compatibility
  File "/home/harry/.local/lib/python3.4/site-packages/setuptools-7.0-py3.4.egg/pkg_resources.py", line 2470, in load_entry_point
    def _parsed_pkg_info(self):
  File "/home/harry/.local/lib/python3.4/site-packages/setuptools-7.0-py3.4.egg/pkg_resources.py", line 2184, in load
    if version is not None:
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 17, in <module>
    from xonsh.shell import Shell
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 9, in <module>
    from xonsh.execer import Execer
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 11, in <module>
    from xonsh.parser import Parser
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 6, in <module>
    from xonsh.parsers.v34 import Parser
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parsers/v34.py", line 4, in <module>
    from xonsh.parsers.base import BaseParser
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parsers/base.py", line 11, in <module>
    from xonsh.lexer import Lexer, LexToken
  File "/usr/local/lib/python3.4/dist-packages/xonsh/lexer.py", line 51, in <module>
    token_map[tokenize.IOREDIRECT] = 'IOREDIRECT'
AttributeError: 'module' object has no attribute 'IOREDIRECT'
```
Launching with `--no-rc` did not fix the issue.

This is harder to debug than it first appears, as when I pulled the latest version of `xonsh` from GitHub and installed it in my development virtual environment (with `python3.4 setup.py install`, overwriting a pre-0.3 version I had hanging around in there), `xonsh` ran fine. Creating a clean virtual environment and installing the latest version (also with `python3.4 setup.py install`) crashes with the same stack trace.

**Aside:** anybody else encountering this problem may wish to know how to change their system shell when all of their shells crash straight away. To do so, you should be able to pass `--command=bash` (or whatever other shell you have installed) to `gnome-terminal` or `terminator`. That didn't work for me for some reason, so I installed `gksu` through the Ubuntu Software Centre, then could use Alt+F2 to run `gksudo gnome-terminal`, which worked because my root user was still on `bash`.

**Comment by HarryCutts** [comment]
Sorry, accidentally hit submit before finishing description. Edit incoming.

**Comment by HarryCutts** [comment]
Description updated.

**Comment by HarryCutts** [comment]
Digging out the `.pyc` file for the `tokenize` module (in my case, `lib/python3.4/site-packages/xonsh/__pycache__/tokenize.cpython-34.pyc` inside the fresh virtual environment) and running `strings` on it does return `IOREDIRECT`.

**Comment by HarryCutts** [comment]
Ah, but the *system's* copy of `tokenize.cpython-34.pyc` (at `/usr/lib/python3.4/__pycache__/tokenize.cpython-34.pyc`) does **not** contain the string `IOREDIRECT`.

**Comment by gforsyth** [comment]
Hey @harrycutts -- sorry for the trouble! Broken terminals are no fun. Also note that if you don't have `gksu` you can drop to a TTY with Ctrl + Alt + F2 (or some other number) and then log in as root, etc...

This is an issue (I think) with changes in the parser tables. Can you try these two things and see if either of them helps?

1. `pip install --upgrade --force-reinstall xonsh` 

2. Remove the xonsh directory from the `usr/local/lib...` and then try again to reinstall.

**Comment by HarryCutts** [comment]
Hi @gforsyth,

No worries! Removing the `xonsh` directory and then running `pip install --upgrade --force-reinstall xonsh` fixed the issue. Thanks!

And yes, I had tried changing to another TTY, but it seems that Ubuntu doesn't allow root login by default (as it assumes you'll use `sudo` all the time) and my other account didn't have `sudo` privileges.
