### ISSUE TITLE
Readline Cannot Find Init File

### ISSUE THREAD

**Issue by fxfitz** [scopatz/xonsh#1049]
Soooo, I must be missing something, but I can't seem to figure out why on xonsh starting I'm always getting this error:

```
$ xonsh
FileNotFoundError: [Errno 2] No such file or directory
xonsh: could not load readline default init file.
```

I've narrowed it down to https://github.com/scopatz/xonsh/blob/master/xonsh/readline_shell.py#L75-L79 (obviously), but without being too familiar with `readline`, it is not obvious to me what the fix is.

Can anyone shed any light on this?

**Comment by smogg** [comment]
+1

**Comment by gforsyth** [comment]
Hey @fxfitz , @smogg -- which OS are you on?

**Comment by adqm** [comment]
Thanks for reporting!

Can you try setting `$XONSH_SHOW_TRACEBACK = True` in your `.xonshrc` file?  That should cause a more complete traceback to show up.  Can you paste that here?

Also, can you please let us know what is the output of running the `xonfig` command?  I know different platforms' readlines have their own quirks...

**Comment by fxfitz** [comment]
Here's the traceback:
```
$ xonsh
Traceback (most recent call last):
  File "/Users/fxfitz/.pyenv/versions/3.5.0/lib/python3.5/site-packages/xonsh/readline_shell.py", line 76, in setup_readline
    readline.read_init_file()
FileNotFoundError: [Errno 2] No such file or directory
xonsh: could not load readline default init file.
```

And from xonfig:
```
$ xonfig
+------------------+-------+
| xonsh            | 0.3.2 |
| Python           | 3.5.0 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | None  |
| pygments         | 2.1.3 |
| on posix         | True  |
| on linux         | False |
| on darwin        | True  |
| on windows       | False |
| is superuser     | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by smogg** [comment]
@gforsyth OSX 10.11.4

Traceback:

```
File "/usr/local/lib/python3.5/site-packages/xonsh/readline_shell.py", line 76, in setup_readline
    readline.read_init_file()
FileNotFoundError: [Errno 2] No such file or directory
xonsh: could not load readline default init file.
```

xonfig:


```
+------------------+-------+
| xonsh            | 0.3.2 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | None  |
| pygments         | 2.1.3 |
| on posix         | True  |
| on linux         | False |
| on darwin        | True  |
| on windows       | False |
| is superuser     | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by fxfitz** [comment]
Also, I'm on OSX (El Cap).

**Comment by adqm** [comment]
Hmm I would have to guess that there is something weird about readline on Mac.  Unfortunately, I don't have a Mac machine to test this.  @gforsyth, are you a Mac person?  If not, we may have to wait for @scopatz (who I believe has a Mac).

In the meantime, the [readline docs](https://docs.python.org/3/library/readline.html) say:
>The underlying Readline library API may be implemented by the libedit library instead of GNU readline. On MacOS X the readline module detects which library is being used at run time.
>The configuration file for libedit is different from that of GNU readline. If you programmatically load configuration strings you can check for the text “libedit” in readline.\__doc__ to differentiate between GNU readline and libedit.

Can you try running Python, importing readline, printing `readline.__doc__`, and letting us know the result?

**Comment by gforsyth** [comment]
@adqm, I am not.  And I'm pretty sure @scopatz switched to Linux, although he may still have a mac laptop lying around?  Or, I can grab one of the hundreds of macs around me at PyCon, but people seem to react badly to that...

**Comment by adqm** [comment]
In the meantime, it looks like IPython handles loading the init files in a slightly nicer way.  I'll try bringing some of their code over to see if that fixes it.

One workaround would be to install `prompt_toolkit` via `pip` (or similar) and set `$SHELL_TYPE = "prompt_toolkit"` in your `.xonshrc` file, which would use that shell instead of using `readline` (some would even say the prompt toolkit shell is better than the readline one).

**Comment by fxfitz** [comment]
```
$ python
Python 3.5.0 (default, Oct  6 2015, 17:53:19) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
>>> readline.__doc__
'Importing this module enables command line editing using GNU readline.'
```

I'll give the `prompt_toolkit` a try!

**Comment by fxfitz** [comment]
`prompt_toolkit` worked! :-D

**Comment by smogg** [comment]
it did work for me 2

**Comment by adqm** [comment]
@fxfitz, @smogg: Great!  I'll still put in the fix for readline, though, in case others encounter this.

**Comment by adqm** [comment]
@smogg, @fxfitz: If you are interested to use the readline shell, I have just put in #1054, which may fix the original issue.  If you feel comfortable doing so, would you mind installing that version and setting `$SHELL_TYPE = "readline"` in your `.xonshrc` temporarily to help test?  If not, we can wait on a core dev with a Mac.
