### ISSUE TITLE
Extra space from {curr_branch} in $RIGHT_PROMPT

### ISSUE THREAD

**Issue by tgoodlet** [scopatz/xonsh#1053]
If I configure:
```
$RIGHT_PROMPT = '[{branch_color}{curr_branch}{NO_COLOR}]'
```
I get an extra space (which @scopatz says is coming from [xonsh.environ.current_branch](https://github.com/scopatz/xonsh/blob/master/xonsh/environ.py#L963)).

So the right prompt looks like `[ master]` :(

**Comment by adqm** [comment]
Ah, yes.  That was designed explicitly for use with a left-sided prompt (before we knew about the right-hand prompt).  Not sure whether we want to change.

Untested, but something like the following should suffice as a workaround (in your .xonshrc):

```
$FORMATTER_DICT["my_curr_branch"] = lambda: $FORMATTER_DICT["curr_branch"]()[1:]
$RIGHT_PROMPT = '[{branch_color}{my_curr_branch}{NO_COLOR}]'
```

HTH!

**Comment by melund** [comment]
The curr_branch function also a have `pad` argument which you can set to `False`
```
$FORMATTER_DICT["curr_branch_unpadded"] = lambda: $FORMATTER_DICT["curr_branch"](pad=False)
```

**Comment by gforsyth** [comment]
I'm going to close this @tgoodlet as there are a few solutions here, but please reopen if they haven't addressed your concerns.  Thanks!

**Comment by scopatz** [comment]
I think we could certainly use a more generic approach to adding padding on the sides of arguments. Please feel free to open another issue!
