### ISSUE TITLE
xonsh crashes only when used as login shell with SLIM

### ISSUE THREAD

**Issue by TobalJackson** [scopatz/xonsh#1057]
Hello, I have a particularly strange issue. I'm running xonsh 0.3.2 from pip under Arch-Linux using xfce4 as my Desktop environment and Slim as my login manager.  If I simply use 
<pre>chsh</pre>  and set it to `/usr/bin/xonsh` , slim gives me a "login command error".  Looking at the Slim configuration file `/etc/slim.conf` , it seems the login command is:
<pre>exec /bin/bash -login ~/.xinitrc %session</pre>
and the `~/.xinitrc` file's contents are:
<pre>#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

#automagically unlock keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# exec gnome-session
# exec startkde
exec startxfce4
# ...or the Window Manager of your choice
</pre>

I saw another issue that talked about differentiating `exec` and `xexec`, so I edited Slim's login command to: 
<pre>xexec /bin/bash -login ~/.xinitrc %session</pre>
and it was able to start my xfce4 environment properly this time. However, upon launching any terminal emulator (terminator, gnome-terminal, xfce-terminal, xterm, etc...) I get the following error:

<pre>Traceback (most recent call last):
  File "/usr/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.2', 'console_scripts', 'xonsh')()
  File "/usr/lib/python3.5/site-packages/xonsh/main.py", line 254, in main
    shell.cmdloop()
  File "/usr/lib/python3.5/site-packages/xonsh/shell.py", line 79, in __getattr__
    return getattr(self.shell, attr)
AttributeError: 'BaseShell' object has no attribute 'cmdloop'
</pre>
before the terminal emulator exits.  Oddly, I can switch my TTY to another (ctrl + alt + F1), login, and use xonsh there without issue.  At this point, to allow me to use any terminals in XFCE I have to chsh away from xonsh, log out of my session, then re-login, and xonsh will start working normally under XFCE4.

**Comment by gforsyth** [comment]
Hey @TobalJackson -- thanks for reporting.  Can you post the output of `xonfig` from your TTY?

Also, if you open a TTY and just do `startx`, does that work?  I believe that SliM is abandonware so it may be doing something funky and unexpected, but we can hopefully help out.

**Comment by TobalJackson** [comment]
Hey @gforsyth , here is my xonfig:
<pre>+------------------+-------+
| xonsh            | 0.3.2 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | 1.0.0 |
| pygments         | 2.1.3 |
| on posix         | True  |
| on linux         | True  |
| distro           | arch  |
| on darwin        | False |
| on windows       | False |
| is superuser     | False |
| default encoding | utf-8 |
+------------------+-------+
</pre>
and I'll try executing both `startx` and `startxfce4`  after having my default shell set to xonsh and see what happens.

**Comment by TobalJackson** [comment]
So having xonsh set as my default shell and disabling SLiM and using `startxfce4` causes XFCE4 to load properly and have all terminal emulators load xonsh properly as well.  It would seem the issue is with how SLiM logs me in to the system.  

I also was not aware that SLiM had deprecated, so I'll be switching away from it to another login/display manager, which will hopefully handle xonsh as my default shell just fine.  I think you can consider this issue closed unless anyone else needs this capability.

**Comment by Maradonna90** [comment]
have the same issue, but tbh at this point with SLiM I don't see any sense in fixing it for xonsh.
