### ISSUE TITLE
Can't run commands with `/?`

### ISSUE THREAD

**Issue by janschulz** [scopatz/xonsh#1059]
```bat
jschulz@littlebottom [C:\data\downloads\libpng\matplotlib-1.5.0+2326.gf349629-np18py27_0.tar\ma `-> % set /?
.....
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: ?',)
```

(I also tried `dumpbin /?`, same result...)

**Comment by laerus** [comment]
what is it that are you trying to achieve?

**Comment by melund** [comment]
I can confirm the error. Many cmd.exe tools on windows use `/?` to get help, but that doesn't  play nicely with xonsh

**Comment by scopatz** [comment]
you can probably put that argument in quotes for the moment, `"/?"`. This should be relatively easy to fix in the base parser.

**Comment by adqm** [comment]
> This should be relatively easy to fix in the base parser.

I'm not sure I 100% understand the use of `/?`, but the hard part is the question mark.  Because of the `?` and `??` syntax for help and superhelp, I don't think we can let question marks be a part of a name in subproc mode.

I guess in theory we could allow them as part of names and then do something special if a name ends with `?` or `??` (run an executable if one exists, or run the help functions if not).  But that's a little on the ugly side.

**Comment by janschulz** [comment]
All "for windows" commands have `command /?` like *ix commands have `command --help` so it would be really great if `/?` could be special cased :-)

```
c:\data\external\conda-packages\staged-recipes (pr/644)
λ echo /?
Zeigt Meldungen an oder schaltet die Befehlsanzeige ein (ON) oder aus (OFF).

  ECHO [ON | OFF]
  ECHO [Meldung]

ECHO ohne Parameter zeigt die aktuelle Einstellung der Befehlsanzeige an.
```

**Comment by scopatz** [comment]
Hi @adqm, I don't think that the help and superhelp syntax overlap with the  subproc args syntax, IIRC. The former only applies to Python mode and the latter only applies to subproc mode. I think all that would need to happen is to add QUESTION_MARK to subproc_arg_part(). The only concern that I have is if we later wanted to use ? for some piece of subprocess syntax in a way that overlaps with this.  So this might regress at some point, even though I can't think of a case where trailing questionarks would have this issue.

Hi @janschulz, I believe that there are many ways to solve this problem: the one I have detailed here, xoreutils, the string trick, etc. However, I think special casing is probably off the table. the language should be easy to teach and understand and not have a lot of special pieces to learn.

**Comment by janschulz** [comment]
@scopatz Not sure if I got my idea across: with special casing I mean that on windows, the parser should identify `/?` as part of a command, not as part of a help request. Currently, the parser does some funny things here:

```
jschulz@littlebottom ~ $ copy?
NameError: name 'copy' is not defined     # <- correct error, kind of helpful
jschulz@littlebottom ~ $ copy /?
........................                                  # <- can`t identify that the command is finished?
  File "<string>", line None
SyntaxError: <xonsh-code>:1:6: ('code: ?',)   # <- Error is IMO unhelpful
jschulz@littlebottom ~ $ cmd /c copy /?
........................
  File "<string>", line None
SyntaxError: <xonsh-code>:1:7: ('code: copy',)
```

Not sure where `?` can get you help here, but if it can't get help for subprocess commands, then IMO if the help can't be interpreted as a help topic, then IMO it should try to interpret the line as a subprocess command?

**Comment by scopatz** [comment]
This has now been added in #1067. Please feel free to reopen if needed.
