### ISSUE TITLE
Xonsh not quite reentrant?

### ISSUE THREAD

**Issue by buchuki** [scopatz/xonsh#1065]
I'm trying Xonsh again after seeing how far it's come in your Pycon talk. It's working pretty well in my tests so far, but I'm having trouble getting it to run inside tmux. I've set tmux to use xonsh as its default shell by putting `set-option -g default-shell /usr/bin/xonsh` in my `.tmux.conf`.

If I run `tmux` from a zsh shell, everything works fine. However, if I run `tmux` from a xonsh shell, I get this output in each tmux pane:

    /bin/sh: module: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_module'
    /bin/sh: scl: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_scl'

xonsh starts just fine in each pane, it's just annoying output.

I've been able to replicate this without using tmux by just calling `xonsh` from inside `xonsh`:

    dusty@localhost:~ 
    $ xonsh
    dusty@localhost ~ $ xonsh
    /bin/sh: scl: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_scl'
    /bin/sh: module: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_module'
    dusty@localhost ~ $ 

while debugging this, I discovered that I get similar output if I run zsh from inside xonsh:

    $ xonsh
    dusty@localhost ~ $ zsh
    /bin/sh: module: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_module'
    /bin/sh: scl: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_scl'
    /bin/sh: module: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_module'
    /bin/sh: scl: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_scl'
    /bin/sh: module: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_module'
    /bin/sh: scl: line 1: syntax error: unexpected end of file
    /bin/sh: error importing function definition for `BASH_FUNC_scl'
    dusty@localhost:~ 

If, however, I run tmux from inside zsh, it correctly loads xonsh instances inside each pane without any output. It seems like my environment is confusing xonsh, or possibly the other way around.  

    dusty@localhost ~ $ print(xonfig.main([]))
    +------------------+--------+
    | xonsh            | 0.3.2  |
    | Python           | 3.4.3  |
    | PLY              | 3.7    |
    | have readline    | True   |
    | prompt toolkit   | 1.0.0  |
    | pygments         | 2.1    |
    | on posix         | True   |
    | on linux         | True   |
    | distro           | Fedora |
    | on darwin        | False  |
    | on windows       | False  |
    | is superuser     | False  |
    | default encoding | utf-8  |
    +------------------+--------+

I'm using gnome-terminal under Fedora. I'm testing with my xonsh/config.json containing an empty object; no configuration.

**Comment by scopatz** [comment]
Hi @buchuki - I believe that this is an issue with how your bash is setup. We have addressed in our Linux guide here: http://xon.sh/linux.html#possible-conflicts-with-bash  Would you mind trying that fix and letting us know if that works.

**Comment by buchuki** [comment]
That does indeed solve it. I was previously using zsh so I didn't think to check the bash installation.

**Comment by scopatz** [comment]
Glad that worked for you @buchuki! Feel free to put in a PR that changes the docs to something more meaningful, if you'd like!
