### ISSUE TITLE
Interactive syntax errors should show a column arrow

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#1081]
In xonsh:

```
xonshat-docs%🐚 test())
..............
SyntaxError: <xonsh-code>:1:6: Unmatched ")" at line 1, column 6
```

vs Python

```
>>> test())
  File "<stdin>", line 1
    test())
          ^
SyntaxError: invalid syntax
```

It's useful to have the column indicator, rather than just "6", to see where the problem is (I like the better error message, though).

**Comment by scopatz** [comment]
I think that this is a relatively easy fix to the parser error func.

**Comment by scopatz** [comment]
Feel free to reopen @asmeurer.
