### ISSUE TITLE
A few issues ...

### ISSUE THREAD

**Issue by mburo** [scopatz/xonsh#1101]
Here are a few things I ran into when testing xonsh 0.3.2 today
on my Fedora 23 system:
+------------------+----------+
| xonsh            | 0.3.2    |
| Python           | 3.4.3    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | None     |
| on posix         | True     |
| on linux         | True     |
| distro           | Fedora   |
| on darwin        | False    |
| on windows       | False    |
| is superuser     | False    |
| default encoding | utf-8    |
+------------------+----------+

1) cat | grep aaa
    and typing some lines such as

    aaa
    bbb
    ctrl-d

    doesn't work as expected
 
    bash prints aaa right after lines that contain aaa;
    xonsh doesn't print anything, and execution doesn't stop after ctrl-d.
   
    cat > xxx
    aaa
    bbb
    ctrl-d
  
    works!

2)  Launching a command (like emacs) followed by ctrl-z suspends
     the process but doesn't return keyboard control to xonsh. So there
     is no way to detach the process with bg and continue typing. The
     documentation only mentions that ctrl-z doesn't work on Windows.

3) Can we have bash's ![prefix] to rerun recent commands?
    I guess it's easy to create our own "! [prefix]" alias but the
    additional space clashes with muscle memory.

4) Just hitting [ret] repeatedly in the terminal shows that something 
    is consuming lots of CPU cycles (top shows 100% CPU) when
    executing empty commands. It looks like at ~6 commands can
    be executed each second. Scrolling may take some cycles, but I
    doubt that many.

**Comment by scopatz** [comment]
Hi @mburo  - would you mind please opening separate issues for each of these so that we can categorize them and discuss them separately, please? Thanks a lot!  Trust me, you aren't spamming the list :)

**Comment by mburo** [comment]
OK, done. Please close this one.
