### ISSUE TITLE
: commands not working anymore?

### ISSUE THREAD

**Issue by mburo** [scopatz/xonsh#1108]
Not sure what happened, but after pulling commit 
0dcd929392eb31a7136ea399bcc59cd14692e410
typing any of the following commands

if True:
for i in range(0,4):
try:

produce error message 
AttributeError: 'NoneType' object has no attribute 'split'

Other commands still work, like print(3+5)
for loops in functions called by aliases also still work.

xonfig
+------------------+----------+
| xonsh            | 0.3.2    |
| Python           | 3.4.3    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | None     |
| on posix         | True     |
| on linux         | True     |
| distro           | Fedora   |
| on darwin        | False    |
| on windows       | False    |
| is superuser     | False    |
| default encoding | utf-8    |
+------------------+----------+

**Comment by scopatz** [comment]
Thanks for reporting @mburo!  I doubt that it was that commit specifically, but I think I see a solution.  Fix incoming.

**Comment by scopatz** [comment]
See #1109

**Comment by scopatz** [comment]
Closing due to fix in #1109. Please reopen, if needed!
