### ISSUE TITLE
Documentation related minor issues

### ISSUE THREAD

**Issue by zaxebo1** [scopatz/xonsh#117]
suggestion1: sphinx generated doc of xonsh on https://readthedocs.org
 I would suggest using https://readthedocs.org/ for uploading the sphinx generated documentation of xonsh . It has webhooks, which can auto import the documentation from github and update the site using sphinx

 for example: some other projects using readthedocs
      http://plumbum.readthedocs.org/en/latest/
      https://twisted.readthedocs.org/en/latest/

========================

suggestion2: on the first page/faq of documentation, it may mention that it does not work on python 2 and what is the minimum version of python 3.x needed
  on the homepage/faq ,also it may mention that whether it fully works on MSWindows too or not. mention - whether it has some optional prerequisite (apart from python 3.x) or not

==========================

suggestion3: it would be great if you put some COMPARISON(advantage/disadvantage) vis-a-vis with other competitors like
           2.1)  Plumbum    https://pypi.python.org/pypi/plumbum 
           2.2)  ipython with %rehashx       (see:  http://ipython.org/ipython-doc/stable/interactive/shell.html  )  (note: your current document mentions ipython, but does not take the care of situation when ipython is started with %rehashx )

The difference may not be as obvious for many initial users

============================================

**Comment by scopatz** [comment]
Hi @zaxebo1, thanks for opening this issue.

> suggestion1: sphinx generated doc of xonsh on https://readthedocs.org

If you'd like to set this up, I'd happily let you.  I don't think I have the bandwidth personally.

> suggestion2: on the first page/faq of documentation, it may mention that it does not work on python 2 and what is the minimum version of python 3.x needed on the homepage

It does, right at the top and in the middle of the page.

> faq

Pull requests welcome!

> also it may mention that whether it fully works on MSWindows too or not

I don't actually know if it does or not!  I am assuming it does, which is dangerous....

> . mention - whether it has some optional prerequisite (apart from python 3.x) or not

All dependencies are listed on the front page.

> suggestion3: it would be great if you put some COMPARISON(advantage/disadvantage) vis-a-vis with other competitors

We'd love to have a page like that.  Again, pull requests very welcome!

**Comment by scopatz** [comment]
Thanks @zaxebo1 - I have implemented these on master.

**Comment by zaxebo1** [comment]
thanks :-) :-)   :+1:
