### ISSUE TITLE
.xonshrc parse error when function arguments are on new line

### ISSUE THREAD

**Issue by abingham** [scopatz/xonsh#12]
If my `.xonshrc` looks like this:
```
def prompt():
    return '{user}'.format(user='me')

$PROMPT = prompt
```
then it works as expected. (BTW, I'm mostly guessing as to how .xonshrc is supposed to work.)

However, if I put `user='me')` on a new line like this:
```
def prompt():
    return '{user}'.format(
        user='me')

$PROMPT = prompt
```
then I get an error on xonsh startup:
```
austinbingham@TK421% python3 -m xonsh.main
/Users/austinbingham/projects/xonsh/xonsh/environ.py:118: RuntimeWarning: syntax error in xonsh run control file '/Users/austinbingham/.xonshrc'
  RuntimeWarning)
austinbingham@TK421.local ~/projects/xonsh $
```
`xonsh` still starts as you can see, but my prompt is ignored.

**Comment by scopatz** [comment]
Hi @abingham, this is how it is supposed to be used :). This seems like a parser error. I am looking into it.

**Comment by scopatz** [comment]
Actually, it was a lexer error more than a parser one.  Should be fixed by 62cc3dc.  Do you mind trying it out?

**Comment by abingham** [comment]
Yep, seems to work now.

**Comment by scopatz** [comment]
Fantastic!
