### ISSUE TITLE
~user is resolved as ${HOME}user

### ISSUE THREAD

**Issue by TheJJ** [scopatz/xonsh#127]
This should be expanded to the homefolder of user, not just replace ~ with $HOME.

example:
```
cd ~mom
cd: no such file or directory: /home/jjmom
```
expected:
```
cd ~mom
<now in /home/mom>
```

**Comment by scopatz** [comment]
Thanks for reporting.  However, I think what it does now is the desired behaviour and consistent with what other shells do, namely bash.

**Comment by TheJJ** [comment]
Just tried it, bash also changes directory to ~user the way i described. zsh does this as well.

**Comment by scopatz** [comment]
I just tried it in bash, and it worked the way I described.  Perhaps there is some environment setting that works does this.  Or maybe your $HOME dir in bash has a trailing `/`.

**Comment by TheJJ** [comment]
https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html
seems that your bash is doing something fishy, hmm.

**Comment by scopatz** [comment]
Given the docs you linked, I don't think that the syntax you proposed is correct.

```bash
scopatz@athenaie ~ BA$H ~scopatz
bash: /home/scopatz: Is a directory
scopatz@athenaie ~ BA$H ls ~xonsh
ls: cannot access ~xonsh: No such file or directory
scopatz@athenaie ~ BA$H ls ~scopatz/xonsh
README.rst  build  docs  license  recipe  scripts  setup.py  tests  xonsh  xonsh.egg-info  __pycache__
```

**Comment by TheJJ** [comment]
```
jj@jjpad ~ % bash
jj@jjpad ~ $ ~jj
bash: /home/jj: Is a directory
jj@jjpad ~ $ ~guest
bash: /home/guest: Is a directory
jj@jjpad ~ $ ls ~
<output redacted>
jj@jjpad ~ $ ls ~jj
<output redacted, but same as ls ~>
jj@jjpad ~ $ ls ~jj/devel/xonsh
docs  license  README.rst  recipe  scripts  setup.py  tests  xonsh
jj@jjpad ~ $ ls ~guest
bin  naminggame  skel
jj@jjpad ~ $ ls ~guest/bin
baseconv  bindiff  cccp  collapse  cols  cptar  cryptmnt  flacsplit  gnu  launch_at  mergedir  normchmod  pycalc  pymv  randbytes  randfile  rfc  tmp
```

How i understand it:
~ = $HOME
~somebody = homefolder of somebody
And that's exactly the way it works on my machines (i haven't configured anything for bash).
zsh is behaving the same way, cant remember having configured that as well.

Independently, it's really convenient typing `cd ~www` and going to `/srv/http/docroot` or something.

**Comment by TheJJ** [comment]
And to prove that your bash example proves xonsh wrong:
```
jj@jjpad ~ $ ls ~jj/devel/xonsh
ls: cannot access /home/jjjj/devel/xonsh: No such file or directory
```
whereas the same expression in bash on your machine:
```
scopatz@athenaie ~ BA$H ls ~scopatz/xonsh
README.rst  build  docs  license  recipe  scripts  setup.py  tests  xonsh  xonsh.egg-info  __pycache__
```

**Comment by wrywerytwreywery** [comment]
`os.path.expanduser` does the right thing, so a well-placed call to that should fix this problem.  However, once the directory gets to `cd`, it has already been expanded in the wrong way, so it's too late to fix the problem there.  

@scopatz, do you know where that modification is happening?  Maybe we could replace that with a call to `os.path.expanduser`, or something like that.

**Comment by scopatz** [comment]
@wrywerytwreywery it might be the parser that does this (`parser.py:2102`) I might have been trying to be too clever :)

**Comment by wrywerytwreywery** [comment]
Yep.  My initial thought is that just removing that check and modifying `cd` always to `expanduser` will fix.  But I'll check a little bit before submitting a PR.

**Comment by scopatz** [comment]
Can you check if this is resolved now @TheJJ

**Comment by TheJJ** [comment]
Jup, now it's behaving correctly. Username completion is missing though :grin:

**Comment by scopatz** [comment]
> Username completion is missing though :grin:

Pull requests welcome :)

**Comment by TheJJ** [comment]
To be honest: I really like the potentiall of this shell, but currently, i'm very happy with my zsh.

I have an `alias p='python3 -q'` for launching python really quick, and because of my current main project (openage) I don't have motivation to contribute things other than ideas and notes.

Keep it up, maybe you may replace my zsh some day! :+1:

**Comment by scopatz** [comment]
Ok. Well thanks for the ideas. Pull requests welcome means that anyone is free to pr though, not just you.

**Comment by scopatz** [comment]
I think that the core issue here has been addressed.  Please reopen if you feel otherwise.
