### ISSUE TITLE
Multi-line input never terminates

### ISSUE THREAD

**Issue by mbollmann** [scopatz/xonsh#13]
When starting a multi-line input, I can't seem to ever get out of multi-line mode no matter how many times I press 'enter'.

I tried to do some good old print-debugging in `shell.py`, outputting the contents of `col` and `buf` [immediately after line 106](https://github.com/scopatz/xonsh/blob/master/xonsh/shell.py#L106), and `col` is always zero no matter what I entered before. So it seems that `buf.pop()` gets called for every line I enter after the first, which means that the buffer never holds a syntactically valid input.

For reference, the output of my print-debugging:

```
>>> if True:
col is 0, buf is ['if True:\n']
Try executing:
if True:

SyntaxError!
...   print(1)
col is 0, buf is ['if True:\n', '  print(1)\n']
Try executing:
if True:

SyntaxError!
... 
col is 0, buf is ['if True:\n', '  print(1)\n']
Try executing:
if True:

SyntaxError!
...   print(2)
col is 0, buf is ['if True:\n', '  print(2)\n']
Try executing:
if True:

SyntaxError!
... 
```

Let me know if I can help debug this problem in any way; I don't understand enough of the code so far to know how to proceed from here.

**Comment by scopatz** [comment]
Thanks for reporting @mbollmann. Super important question, what does the following command return:

```console
$ python -c "import readline; print(readline.__file__)"
```

**Comment by shoyer** [comment]
Just installed xonsh and came here to report the exact same issue.
```
shoyer@tcc-shoyer.local ~ $ python -c "import readline; print(readline.__file__)"
/Users/shoyer/miniconda/envs/xonsh/lib/python3.4/lib-dynload/readline.so
```

**Comment by scopatz** [comment]
@crbates - I think that this is the same issue you were seeing too.  This seems mac specific. @mbollmann and @crbates, are you on conda too?

**Comment by mbollmann** [comment]
```
bollmann@underberg ~ $ python3 -c "import readline; print(readline.__file__)"
/usr/lib/python3.4/lib-dynload/readline.cpython-34m-x86_64-linux-gnu.so
```

I'm neither on Mac nor on Conda -- using Xubuntu 14.04 and installed xonsh from source via setup.py.

**Comment by shoyer** [comment]
I'm on OS X and use conda environments to manage applications, but I also installed xonsh from source (well, `pip install https://github.com/scopatz/xonsh/archive/master.zip`).

Your binstar channel doesn't have builds for OS X. If you're going to continue advertising that method of install, I would consider adding those (e.g., by using `conda convert`).

**Comment by torgny** [comment]
I think what's needed is to use the cmd.Cmd.emptyline to detect that an empty line is used (instead of using RL_POINT). I have a local patched version that fixes this bug using this method, but I have to test it more thoroughly and I don't have time right now.

**Comment by scopatz** [comment]
closed by #19

**Comment by mbollmann** [comment]
For what it's worth, this still happens if the multi-line input contains syntactically invalid lines, e.g.:

```
>>> if True:
...   print foo   # oops, Python-2-style print without brackets
...
...
...
... asdf
...   foobar
... # never terminates unless you press CTRL+C ...
```

Maybe the solution to this issue is "just don't do that", but I can imagine it to be confusing when you're not aware where the error actually is, and you have no way to find out. (Maybe related to #22 ?)

**Comment by scopatz** [comment]
Thanks for reporting this @mbollmann.  82aa979 should fix this issue - which sadly seems unrelated to #22
