### ISSUE TITLE
there should be an environmental variable $XONSH_VERSION

### ISSUE THREAD

**Issue by zaxebo1** [scopatz/xonsh#132]
when we are in zsh, there is a $ZSH_VERSION environmental variable
when we are in bash, there is a $BASH_VERSION environmental variable. Rather bash has many many other bash specific envionmental variables, which are probably never needed. :)  

I think there should be a $XONSH_VERSION env variable to immediately check the version. and accordingly act in my script

**Comment by scopatz** [comment]
A good idea.

**Comment by scopatz** [comment]
This should be implemented now
