### ISSUE TITLE
Job Control

### ISSUE THREAD

**Issue by wrywerytwreywery** [scopatz/xonsh#141]
I think this won't be easy given how xonsh is put together, but it would be great to support some job control commands (ctrl-z, fg, bg, etc) in addition to having the ability to start a subprocess in the background.

**Comment by scopatz** [comment]
I should note that ending with `&` already exists.  So I think bg is a simple alias along the lines of:

```python
from xonsh.built_ins import subproc_uncaptured
def bg(args, stdin=None):
    subproc_uncaptured(args, '&')
    return None
```

We might need to build a jobs set, but that shouldn't be too hard.  Also Ctrl-z would be a feature of the Shell, I feel like, which would then need to send the SIGTSTP to the current process.

**Comment by SmartViking** [comment]
In bash/zsh each job is given a number and you can select which to `fg` with `fg %n`, or kill like `kill %n`, I think xonsh should support something similar to that.

**Comment by wrywerytwreywery** [comment]
bg and fg are a little more complicated, as they can act on running jobs to push them to the background or bring them to the foreground, so we would definitely need a jobs list.  And we would also need the shell to have a notion of which process, if any, is in the foreground.

There is also the question of the nice way to get xonsh to grab the `SIGSTP` and send it to the current foreground process; presumably something in `signal` can help (and we can use `os.kill` to send the command).

I think this is doable.  Unless someone else wants to take a stab, I can put it on my queue.

**Comment by wrywerytwreywery** [comment]
The behavior that I really want, by the way, is at least the following:
* start a process (not backgrounded)
* stop with ctrl-z
* run another command
* bring original process back to foreground

and...
* start a process (not backgrounded)
* realize i wanted it backgrounded
* stop with ctrl-z
* send to background to let it run but keep the shell open for other commands

**Comment by SmartViking** [comment]
One job may contain several processes, like this:

```
$ find . | cat > file &
[1] 14954 14955
$
[1]  + done       find . | cat > file
```

Both `find` and `cat` are considered (here by zsh) as one job.

**Comment by SmartViking** [comment]
You can intercept CTRL-Z with this:

```python
def handler(num, frame):
    pass

signal.signal(signal.SIGTSTP, handler)
```
As I understand it, the fg process will receive `SIGTSTP` and then the main thread will pause execution and run this function. The problem becomes: how to deal with `Popen.communicate()` in `built_ins.run_subproc`? You have make it stop waiting. I tried raising exceptions in `handler` and you can indeed catch them to cancel the waiting. But can that break the internal workings of `Popen` somehow?

**Comment by scopatz** [comment]
Maybe with [something like this](http://stackoverflow.com/a/12058234/2312428) where the process is polled until it is done?

**Comment by scopatz** [comment]
And if the process is ever put into the background, then the loop is broken out of and communicate never happens

**Comment by wrywerytwreywery** [comment]
I have something vaguely resembling a plan for this :) I was planning to dig in in the morning.

I think, roughly, it means: we don't want to be using `communicate` anymore.  We can use `poll` instead to check whether the process is still alive.  And if we keep some sort of structure around that tells us the current foreground process, we know what to `poll` (and, also, where to send signals if need be).  Background processes don't need to be polled, of course, and we could have `fg` bring things back to the foreground.

I think we also want to rethink `ProcProxy`, modifying it to looks as close as possible to a `Popen` object, so that we only have to have one kind of interaction.  My thought is that we can use `multiprocessing` to this end.  This also makes sense, I think, since not all aliases will be able to run so quickly as those that exist in the builtins; I think we want to be able to stop and background them, or bring them back to the foreground, just the same as any other process.

**Comment by scopatz** [comment]
Something with multiprocess sounds right to me :).  ProcProxy was a quick hack to get functionality.  Originally I wanted xonsh to be fully usable as possible.

**Comment by wrywerytwreywery** [comment]
I spent some time today trying to rework `ProcProxy`.  As with anything involving `multiprocessing`, shared memory is the hard part (both `cd` and `exit` want to change global variables in the main process), so that rewrite is going to be harder than I expected (though I still think it's possible).  Using `threading` instead would fix that problem, but it also doesn't quite do the trick, since, as far as I know, there is no easy way to suspend a thread once it has been started.

**Comment by SmartViking** [comment]
Won't the user of xonsh also have to deal with shared memory complications when they're writing aliases? That would make xonsh inaccessible and difficult to use for a lot of people who otherwise would be able to use it.

**Comment by wrywerytwreywery** [comment]
Yes; I decided to leave `ProcProxy` as it is (at least for now), for exactly that reason.

**Comment by SmartViking** [comment]
Maybe you could use special decorators for things you want threaded/multiprocessed.

And btw, shouldn't it be possible to create aliases that read/write from stdin/stdout instead of receiving the full deal and returning the full deal? That would enable the alias to run simultaneously as the other parts of a pipe. You could have a decorator for that too.

**Comment by wrywerytwreywery** [comment]
I have what I think is a working version of job control (ctrl-z, `jobs`, `fg`, `bg`) in wrywerytwreywery/xonsh on the job_control branch as of right now.  It currently only works for subprocesses, and `ProcProxy` exists as it was before.  I am planning on doing some cleanup (and maybe trying to deal with `ProcProxy`) before submitting a pull request, but if you're interested, I'd appreciate more testing of the functionality.

`fg` and `bg` are slightly different from their bash counterparts, in that, instead of taking a job number as, e.g., `%1`, they just take them as a single number, e.g., `1`.

> Maybe you could use special decorators for things you want threaded/multiprocessed.

That's a nice idea.  I think each has its benefits and drawbacks, and letting the user choose between them might be nice (and even letting the user use the current `ProcProxy`, since that might end up being easier to write).  At the same time, I was really hoping to have a single, unified `ProcProxy` that "just worked" in the sense that it mirrored `Popen`.

> And btw, shouldn't it be possible to create aliases that read/write from stdin/stdout instead of receiving the full deal and returning the full deal?

This was my main motivation for wanting to change `ProcProxy` to begin with.  It could be that the right thing in the short term is to using `threading` and forget about trying to make it suspendable with ctrl-z.  That would at least be a step in the right direction, I think, and we wouldn't be losing anything since `ProcProxy` processes aren't suspendable now anyway.

**Comment by wrywerytwreywery** [comment]
I am going to close this one for now since job control has been implemented, and I'd like to table updates to `ProcProxy`.  I was writing something this morning and it was close to working, but it's tricky to get exactly right (I was reimplementing a lot of low-level things to try to make pipes work), and as time went on, I because less certain of the benefits.

My current feeling is that the right message is: if you have something that is going to be running for a long time, or something that needs to use `stdout` and `stdin` as file-likes rather than returning the strings in one go, then a better thing to do would be to write a script (in xonsh or in python), and alias that instead.

**Comment by scopatz** [comment]
I think that is reasonable.
