### ISSUE TITLE
Website suggestions

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#142]
Some suggestions when reading the website:

- Make the link to GitHub more prominent (a "fork me on GitHub" banner is one way to do this). 

- You can just use `-c scopatz` in the conda command. The full binstar url is not required. 

- The movie is low res and looks bad on my retina display

**Comment by scopatz** [comment]
Thanks @asmeurer!

> Make the link to GitHub more prominent (a "fork me on GitHub" banner is one way to do this). 

Will do.

> You can just use -c scopatz in the conda command. The full binstar url is not required. 

Will do.

> The movie is low res and looks bad on my retina display

Will do the next time that we make a movie.

**Comment by scopatz** [comment]
The first two have been implemented.  The third will have to wait until v0.2

**Comment by scopatz** [comment]
I have switched this to asciinema on master, which should address the last issue.
