### ISSUE TITLE
Simple multiple assignment leads to a syntax error

### ISSUE THREAD

**Issue by wrywerytwreywery** [scopatz/xonsh#147]
I can't figure out why, but simple multiple assignments (like `a, b = 7, 8`) are syntax errors in xonsh.  Starexprs seem to work fine (like the tests currently in tests/test_parser.py, e.g. `*x, y = [1,2,3]`).  

I can't see why, but `a, b` seems not to parse out to a `testlist_star_expr`, despite having the right tokens (`NAME`, `COMMA`, `NAME`).    It does parse down to a testlist.  I tried changing the rules for `p_expr_stmt` to allow testlists, but that didn't work (though maybe I screwed it up somehow).

Could this be a precedence issue?  Or maybe I'm missing something simple...  I can keep looking at it, but if you have any insights, @scopatz, I'd appreciate it.

**Comment by scopatz** [comment]
This seems to be an issue with grouping the left-hand side.  Adding parentheses seems to make everything work:

```console
scopatz@athenaie ~ $ (a, b) = (7, 8)
scopatz@athenaie ~ $ (a, b) = 7, 8
```

I doubt that this is anything that you did @wrywerytwreywery since `a, b = 7, 8` fails on the current master too (cfb031b82765d2713e144b9aaa01ae8b299f46ee).

**Comment by wrywerytwreywery** [comment]
Oh, that makes sense that it would error if it's grouping that, for example, as `(a,  b=7, 8)`, rather than `(a,b) = (7,8)`.

**Comment by wrywerytwreywery** [comment]
I'm happy to try to give this a shot sometime over the next couple of days, but if you want to take it, that would be fine, too!

**Comment by scopatz** [comment]
I'll take a look tonight. One of my friends (@gidden) is defending his PhD tomorrow, so I might not be really around tomorrow night :)
