### ISSUE TITLE
File-redirect and `&` aren't compatible

### ISSUE THREAD

**Issue by SmartViking** [scopatz/xonsh#148]
```bash
ls > file &
```
The above doesn't create `file`. The reason for the bug is in `built_ins.run_subproc`. When it's a background job it doesn't wait, and consequently doesn't write to the file at the end.

Maybe the fix would be send the object created by `open` as the `stdout` argument to `Popen`? Then, presumably, the process will begin writing to the file before all the output is computed, which is more standard behavior.

**Comment by scopatz** [comment]
Yep.  This is an issue.  Thanks for reporting @SmartViking

**Comment by scopatz** [comment]
@SmartViking can you confirm that master (c3bb6acae2f1e2b83594501cad5cdc7fc8536dd7) fixes the issue for you, please? Thanks!

**Comment by SmartViking** [comment]
Yep, works as expected now.

**Comment by scopatz** [comment]
Awesome!
