### ISSUE TITLE
Ctrl-C does not abort readline (reverse-i-search)

### ISSUE THREAD

**Issue by icarito** [scopatz/xonsh#161]
Often I need to look up an older command. 
I use readline's ctrl-r for an incremental history search.

Many times I abort the search for whatever reason, using Ctrl-C. This works in bash, but not in xonsh.

To test:
1. In xonsh, use Ctrl-r
2. Start typing (so it will traverse history)
3. Type Ctrl-c to abort
4. Aparently all is fine.
5. Now press enter.
6. Last command in reverse search will be executed.

**Comment by wrywerytwreywery** [comment]
I can confirm this behavior (Ubuntu 14.04, Python 3.4, libreadline 6.3-4ubuntu2).  This may be a duplicate of issue #78, although the specific symptoms seem to have changed since then.

**Comment by icarito** [comment]
Indeed this is a duplicate of #78 so I'm closing this one. Thanks for pointing it out.
