### ISSUE TITLE
More complete history

### ISSUE THREAD

**Issue by jalanb** [scopatz/xonsh#17]
I suggest that each command executed in xonsh should create an history object, some of whose attributes could be

1. The command which ended up being run
2. stdout
3. stderr
4. return status
5. timestamp

History should be stored in a normal, text based, configuration file, e.g. ~/.xonsh_history, or ~/.config/xonsh/history, and (Unlike bash) history should be unlimited by default

A function, or command, should be provided to recall history items by index, or by searching on command text or output text

**Comment by shoyer** [comment]
This is a nice idea. IPython does something similar with the `In` and `Out` objects.

**Comment by scopatz** [comment]
I wouldn't mind if someone beat me to implementing this :)  Probably should persist as JSON.  This is on the to do list, though.

**Comment by anula** [comment]
Are you (or anyone) already implementing this? It sounds like an interesting project and I would be happy to implement it if no one else has started yet.

**Comment by scopatz** [comment]
Hi @anula - to the best of my knowledge, no one has started implementing this yet.  It would be great if you wanted to take a stab it.  We definitely need people to start implementing all of the desired features :)

**Comment by anula** [comment]
Great! Then I will start implementing it ;)
One question for now - this extended history should last only for current session, or should be preserved indefinitely? I think that IPython keeps it only for current session, also I don't see any particular use-case for keeping it longer, but maybe I am missing something.

**Comment by scopatz** [comment]
History should definitely have the option of being persisted. The length of history saved should determined by the `$XONSH_HISTORY_LENGTH`  environment variable.  One thing that would be super neat that you can also think about is having each xonsh session  have its own id and its own history in whatever file is stored.  Thanks!

**Comment by scopatz** [comment]
This would replace the current history that is written by readline.

**Comment by jalanb** [comment]
I would definitely prefer that the current history be preserved indefinitelty. (One of my major bugbears with bash is that it took me (literally) decades to find out how to keep history for long enough to get back "that iptables command we used on Project X about 2 years ago". Even now I only *think* the bash history is long enough, but only started new system on 2015/02/04).

If an environment variable such as $XONSH_HISTORY_LENGTH is used, then it should recognise (at least one) sentinel value, e.g. -1, to mean "keep indefinitely"

**Comment by scopatz** [comment]
Yep @jalanb - something like that.

**Comment by anula** [comment]
Sure - I agree that command history should be kept for as long as possible. I also very often try to find a command in my history just to discover that max length is too short to contain the particular command.
But I don't see much value in preserving stdout or stderr for so long - have you ever needed those after time longer than, let's say, a month? 
Main issue here is that there are many situations where programs produce a lot of output - and suddenly after a few months you discover that your history file is 10GB big (and that is not the worst case, I'd guess, consider amount of logging while building some open-source projects, or just when trying to compile C++ code that has error in some complicated templates). And you want to preserve history of commands, so just deleting the file is not an option.

My guess is that you don't really need those output values for longer than just one session, but maybe it would be reasonable to just have a limit (on size, time, or number of entries) after which outputs will be deleted and only commands preserved.

**Comment by scopatz** [comment]
Hi @anula - I agree with you on many of these points.  Setting a garbage collection timer would be an awesome feature :).  However, I do think that different people have different use cases and so most of these choices what, how much, and how long to store things should be configurable.  xonsh should have sensible defaults but accommodate use cases on all ends of the spectrum.

**Comment by bsmt** [comment]
I can help with this too if it won't conflict with @anula.

**Comment by scopatz** [comment]
closed by #353
