### ISSUE TITLE
Enable Subprocess Completion for Subsequent Tokens

### ISSUE THREAD

**Issue by blink1073** [scopatz/xonsh#171]
I have used the following to set my bash completion:  
```bash
$BASH_COMPLETIONS=`/usr/local/etc/bash_completion.d/*`
```

There's a `git-completion.bash` in that folder, so one would expect to be able to type `git clo<TAB>` and get `git clone`.  I read in the docs that completion is enabled for the first token in Subprocess mode.  Is there a chance to enable it for the rest of the tokens as well?

**Comment by blink1073** [comment]
Right now subsequent tokens are treated as Python, so that if I type `git cl<TAB>` I get `git class`.

**Comment by scopatz** [comment]
Hi @blink1073 - where are you setting the `$BASH_COMPLETIONS`? This needs to be done in the `~/.xonshrc` file.  Also, since you are using the backtick globbing, you probably meant to do `.*` at the end of your regex.  That is:

```console
$BASH_COMPLETIONS = `/usr/local/etc/bash_completion.d/.*`
```

Do those fixes help?

**Comment by blink1073** [comment]
Works on my Linux box, I'll try it on my Mac when I get home, thanks @scopatz.

**Comment by blink1073** [comment]
Yep, it works now, but I get a *lot* of errors when I start up.  Here's a sampling:

```python
/usr/local/etc/bash_completion.d/update-alternatives: line 39: syntax error in conditional expression: unexpected token `('
/usr/local/etc/bash_completion.d/update-alternatives: line 39: syntax error near `--@(i'
/usr/local/etc/bash_completion.d/update-alternatives: line 39: `        if [[ "${COMP_WORDS[i]}" == --@(install|remove|auto|display|config|remove-all|set) ]]; then'
/usr/local/etc/bash_completion.d/util-linux: line 5: have: command not found
```

**Comment by scopatz** [comment]
Can you post the full output please?

**Comment by blink1073** [comment]
https://gist.github.com/blink1073/cdfa267f222f83d1066d

**Comment by scopatz** [comment]
You need to add the file "/usr/local/etc/bash_completion" to the front of the list, if it exists.  If not, you need to find the bash completion file that contains the `have()` function and then put that file at the beginning.

**Comment by blink1073** [comment]
`have()` is indeed defined in "/usr/local/etc/bash_completion", and I added as 

```
$BASH_COMPLETIONS=["/usr/local/etc/bash_completion"] + `/usr/local/etc/bash_completion.d/.*`
```

The error persists.  I verified that the desired file was first in `$BASH_COMPLETIONS`.

**Comment by scopatz** [comment]
What if you leave off the regex globbing?  Here is what mine looks like:

```console
scopatz@athenaie ~ $ $BASH_COMPLETIONS
['/etc/bash_completion', '/usr/share/bash-completion/completions/git']
```

**Comment by blink1073** [comment]
We have a winner!

**Comment by blink1073** [comment]
Final version: `$BASH_COMPLETIONS=["/usr/local/etc/bash_completion"]`

**Comment by scopatz** [comment]
Great!  Please feel free to close.

**Comment by blink1073** [comment]
I'm pondering whether the docs should be more explicit on this.  Right now `$BASH_COMPLETION` is mentioned in the doc, but not the fact that it *must* be in the `.xonshrc` file (I was setting it via the command line at first).  It also mentions that the defaults are platform dependent, but sane.  When using brew, it ends up in `$(brew --prefix)/etc/bash_completion`.  When using Macports its in `/opt/local/etc/profile.d/bash_completion.sh`.  Perhaps these locations should be checked in `environ.py` and added if available?

http://blog.jeffterrace.com/2012/09/bash-completion-for-mac-os-x.html
https://trac.macports.org/wiki/howto/bash-completion

**Comment by blink1073** [comment]
(or just assume `/usr/local/` for `(brew --prefix)` since that is the default).

**Comment by scopatz** [comment]
Hi @blink1073 - I completely agree.  The docs should be more explicit.  Also, I am all for adding checks for common locations in environ.  Adding extra files should be safe, since the completer will check for the file's existence before trying to source it.  

Pull requests are really very welcome here for both of these issues. I clearly did a bad job on the docs the first time and I can't test this with macports or brew easily :)
