### ISSUE TITLE
Issues when SSH'ing (with command) into machine running xonsh

### ISSUE THREAD

**Issue by wrywerytwreywery** [scopatz/xonsh#176]
I have noticed two issues with SSH'ing with a command into a machine running xonsh (i.e., `ssh machine_running_xonsh COMMAND`).  I have plans to fix these, but I wanted to document them.

* Currently, running any command in this way will error.  This is because of a bug in the job control, where it tries to pass the terminal in which it is currently running to a child subprocess; but when started in this way (above), xonsh is not being run in a terminal.  I have something locally that seems to work (simply don't try to give away the terminal if we're not running in interactive mode), but I would like to test more before submitting a PR.  SSH'ing without a command works fine (since we actually have a terminal in that case).

* Even with the fix above in place, the output of the xonsh process seems only to show up once xonsh has exited (probably for the same reason as above, since stdout is a pipe instead of a terminal).  We can probably get around this by changing the shebang line in the xonsh startup file to run `/whatever/python3 -u` (don't buffer stdin, stdout, stderr) instead of just `/whatever/python3` (I hope there is an easy way to change this by modifying `setup.py`).

**Comment by scopatz** [comment]
Crazy!  I haven't tried this yet.  sshing in as a log in (no command) works, though, right?

**Comment by wrywerytwreywery** [comment]
>  sshing in as a log in (no command) works, though, right?

Yep.  Because (I think) ssh actually connects us to a terminal in that case, whereas, with a command, it seems to just hook us up to a pipe.

**Comment by wrywerytwreywery** [comment]
I may be able to get a fix pushed tonight.

**Comment by Russell-Jones-OxPhys** [comment]
For reference, ssh -t allocates pseudo terminal (pty).

**Comment by scopatz** [comment]
Cool thanks for the tip, @Russell-Jones-OxPhys
