### ISSUE TITLE
Exec bashrc crash

### ISSUE THREAD

**Issue by aig787** [scopatz/xonsh#178]
I added lines to my .bashrc to exec xonsh instead if present and it immediately crashes. If I redirect stdout to a file it looks like the error I get is

Traceback (most recent call last):
  2   File "/usr/local/bin/xonsh", line 3, in <module>
  3     main()
  4   File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 61, in m    ain 
  5     code = shell.execer.compile(code, mode='exec', glbs=shell.ctx)
  6   File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 92, in     compile
  7     code = compile(tree, self.filename, mode)
  8 TypeError: expected some sort of stmt, but got <_ast.Call object at 0x7f21d1    548ac8>

Calling exec after bash has loaded works just fine.

**Comment by scopatz** [comment]
Hi @aig787 - what version of xonsh are you on?  This looks suspiciously similar to an issue that is now fixed on master, if you want to give that a try.  Thanks for reporting!

**Comment by wrywerytwreywery** [comment]
Won't it also be the case, though, that, even if this issue has been resolved, having bashrc start xonsh could lead to an infinite loop (since xonsh runs bash when getting the initial environment and when trying to import aliases)?

**Comment by scopatz** [comment]
@wrywerytwreywery probably, unless @aig787 has xonsh running in an if-block that first checks to make sure that xonsh isn't running.

**Comment by scopatz** [comment]
PS infinite bash loops are really annoying since they hang forever and eat up all of your system resources.

**Comment by aig787** [comment]
@scopatz and @wrywerytwreywery thanks so much for the awesome (and quick) feedback! I'm running 0.1.4 and it looks like it's a combination of the two you mentioned depending on quotes. If I put `exec 'xonsh'` I get the crash, if I put `exec xonsh` everything goes okay after I added the bit to check if it was already running.

When I went to install from master to see if the quote problem has been fixed I get

```bash
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 2, in <module>
    from xonsh.main import main
ImportError: No module named 'xonsh.main'
```

**Comment by scopatz** [comment]
When do you see this @aig787? When you install or when you run?

**Comment by aig787** [comment]
When I run it. If I removed it and was able to install with pip just fine.

**Comment by scopatz** [comment]
hmm what directory are you in when you run it and what is your python path (ie `python -c 'import sys; import pprint; pprint.pprint(sys.path)'`)

**Comment by aig787** [comment]
I'm in my home directory and my python path is 

```bash
$ python3 -c 'import sys; import pprint; pprint.pprint(sys.path)'
['',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages']

I think it's a permissions issue, the permissions of /usr/local/lib/python3.4/dist-packages/xonsh are drwxr-s--- and it's owned by root. I installed with `sudo python3 setup.py install', running without sudo gave me permissions errors in /usr/local/.

**Comment by scopatz** [comment]
Can you install (without sudo) with `python setup.py --user`?  You will need to add `~/.local/bin` to your PATH, too.

**Comment by aig787** [comment]
That worked perfectly no issues now. Thanks so much.

**Comment by scopatz** [comment]
Glad it is working!
