### ISSUE TITLE
Slow initialization of xonsh

### ISSUE THREAD

**Issue by SavinaRoja** [scopatz/xonsh#198]
I started out writing this issue rather more clueless than I am now that I am finishing it... Basically it seems that the start-up time for PLY might be pretty punitive on weaker processors as found on the Raspberry Pi when it comes to scripting. This issue may or may not be a bit complicated to address.

I installed xonsh on a little Raspberry Pi 2 Model B I have for personal file serving so I could tinker with writing xonsh shell scripts (and hopefully replace some active scripts at some point) and noticed that the startup time for xonsh was pretty slow.

Here's some time benchmarks from my desktop workstation and from my raspberry pi, collected using `time bash -c true; time xonsh -c true; time python -c "pass"`:

```
Desktop:
  Bash:               Xonsh:              Python:
    real    0m0.005s    real    0m1.271s    real    0m0.025s
    user    0m0.000s    user    0m1.160s    user    0m0.016s
    sys     0m0.004s    sys     0m0.060s    sys     0m0.004s
-------------------------------------------------------------
Raspberry Pi 2 Model B:
  Bash:               Xonsh:               Python:
    real    0m0.025s    real    0m13.894s    real    0m0.231s
    user    0m0.010s    user    0m12.840s    user    0m0.170s
    sys     0m0.010s    sys     0m0.290s     sys     0m0.030s
```

After some quick testing and I observed that `xonsh -h` was much faster (and in line with my general expectations):

```
real    0m1.881s
user    0m1.750s
sys     0m0.110s
```

With this hint and some some fiddling, I observed that the great majority of the time was being spent during the call to initialize `Shell`.

I then did a basic cProfile of `xonsh.shell.Shell()` on both the desktop and the raspberry pi, the results of which are detailed here: https://gist.github.com/SavinaRoja/1f9051193376e5374aa9

This seems to show that the main chunk of time is being spent initializing the PLY Parser. I am not sure what can be done to improve this. Perhaps there might be an optional installation route for Xonsh to utilize the Lex and Yacc tools natively?

**Comment by scopatz** [comment]
Fascinating: here are my timings.   

```
  Bash:               Xonsh:              Python:
    real    0m0.003s    real    0m0.291s    real    0m0.019s
    user    0m0.003s    user    0m0.291s    user    0m0.019s
    sys     0m0.000s    sys     0m0.063s    sys     0m0.000s
```

This person from reddit claimed a 25 second startup! http://www.reddit.com/r/commandline/comments/2z7727/xonsh_intelligent_modern_shell/cph3n0a

**Comment by scopatz** [comment]
So most of the damage comes from the `yacc.lr_parse_table()` fucntion  (https://github.com/dabeaz/ply/blob/master/ply/yacc.py#L2421)  I think that we have a rather complicated parse tree, but trying to smooth that out would only give differential benefits.

**Comment by scopatz** [comment]
OK I have figured out that you are not running in optimize mode on either your desktop or on the Pi. That explains the really long run times.  Can you please do a clean install and then post the full output, please?  You desktop should be good enough.  Thanks!

**Comment by SavinaRoja** [comment]
Both of these installations for the testing I did today were from GitHub a couple of hours prior to opening this issue. I'll reinstall and see if anything changes, get back to you in a minute.

**Comment by SavinaRoja** [comment]
I have an interesting finding; there is a noticeable and reliable difference between installation modes. I created two virtualenvs, one with standard installation and one with a development "Editable" install (this was the mode I was employing before). Here are the summarized results:

```
Standard Installation:
  Bash:               Xonsh:              Python:
    real    0m0.005s    real    0m0.486s    real    0m0.025s
    user    0m0.000s    user    0m0.392s    user    0m0.020s
    sys     0m0.000s    sys     0m0.048s    sys     0m0.004s
-------------------------------------------------------------
"Editable" Installation:
  Bash:               Xonsh:              Python:
    real    0m0.005s    real    0m1.264s    real    0m0.018s
    user    0m0.000s    user    0m1.164s    user    0m0.016s
    sys     0m0.000s    sys     0m0.044s    sys     0m0.004s
```

**Comment by SavinaRoja** [comment]
The new timings for the Raspberry Pi are as follows:

```
Standard Installation:
  Bash:               Xonsh:              Python:
    real    0m0.036s    real    0m1.936s    real    0m0.230s
    user    0m0.030s    user    0m1.700s    user    0m0.160s
    sys     0m0.000s    sys     0m0.180s    sys     0m0.060s
```

**Comment by scopatz** [comment]
What was the command you ran for the editable install?

**Comment by scopatz** [comment]
Just `--editable`?

**Comment by SavinaRoja** [comment]
`pip install -e <xonsh-dir>`

**Comment by scopatz** [comment]
OK!  I believe I have a potential fix for editable on the `e` branch, see #199.  Can you try this out, please?

**Comment by SavinaRoja** [comment]
Error during installation:
```
running develop

Remove xonsh/parser_table.py

Building lexer and parser tables.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/pablo/workspace/venvs/xonsh-dev-new/xonsh/setup.py", line 134, in <module>

    main()

  File "/home/pablo/workspace/venvs/xonsh-dev-new/xonsh/setup.py", line 91, in main

    setup(**skw)

  File "/usr/local/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/local/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/pablo/workspace/venvs/xonsh-dev-new/xonsh/setup.py", line 54, in run

    install.run(self)

  File "/home/pablo/workspace/venvs/xonsh-dev-new/lib/python3.4/site-packages/setuptools/command/install.py", line 53, in run

    if self.old_and_unmanageable or self.single_version_externally_managed:

  File "/usr/local/lib/python3.4/distutils/cmd.py", line 103, in __getattr__

    raise AttributeError(attr)

AttributeError: old_and_unmanageable
```

**Comment by scopatz** [comment]
Sorry, there was a really stupid bug. It should be fixed now.

**Comment by SavinaRoja** [comment]
Looks good, new timing:

```
"Editable" Installation on branch "e":
  Bash:               Xonsh:              Python:
    real    0m0.005s    real    0m0.485s    real    0m0.024s
    user    0m0.000s    user    0m0.400s    user    0m0.016s
    sys     0m0.000s    sys     0m0.048s    sys     0m0.004s
```

**Comment by scopatz** [comment]
Whoohoo!

**Comment by SavinaRoja** [comment]
Later when I'm not sleepy I'll have study why this all worked the way it did. I'd still be curious about ways to reduce the load time overhead further, but this definitely knocked out a major part of the observed issue.

**Comment by scopatz** [comment]
Yup, yup. I am still interested in startup time speedups too.  Feel free to ask any questions!  Further profiling is probably needed to get more speed ups.  For me, it looks like a lot of time is spent in subprocess and `load_builtins()`.  I loading the bash completions is a fair amount of that, which frankly doesn't have to happen in the main thread.

**Comment by scopatz** [comment]
Alright @SavinaRoja - #198 is now on master, feel free to close this, please.  I think we can continue the discussion of speedups in another thread. Thanks!

**Comment by scopatz** [comment]
Please feel free to reopen @SavinaRoja, if this is not sufficient.
