### ISSUE TITLE
bash aliases extraction is unreliable

### ISSUE THREAD

**Issue by auscompgeek** [scopatz/xonsh#204]
The `xonsh.aliases.bash_aliases()` function mostly assumes only the output of the `alias` command will be written. However, many `bashrc`s, including distros' `/etc/bash.bashrc`s set `$PROMPT_COMMAND` when bash is run in interactive mode, which can cause unexpected output.

**Comment by auscompgeek** [comment]
This begins to raise the question of whether this is worth the trouble that it causes...

**Comment by scopatz** [comment]
Thanks for opening this issues @auscompgeek, I think the choice of whether it is worth it or not should be left up the users.  So really, there should be a way to toggle whether this feature is on or off....
