### ISSUE TITLE
Implement module import completion

### ISSUE THREAD

**Issue by eyalzek** [scopatz/xonsh#206]
For example; typing:
import 
and clicking tab, should list available modules.

**Comment by scopatz** [comment]
Thanks for opening this issue @eyalzek

**Comment by scopatz** [comment]
Closed by #218

**Comment by asmeurer** [comment]
Are there plans to powerhouse the Python completion with jedi?

**Comment by scopatz** [comment]
Not yet, but now there should be :)

**Comment by asmeurer** [comment]
I'll open an issue.
