### ISSUE TITLE
RPyC zero deploy for seamless xonsh with ssh.

### ISSUE THREAD

**Issue by traverseda** [scopatz/xonsh#215]
This is a feature discussion. Don't know if I'd go so far as to call it a feature request.

RPyC is a tool for remote procedure calls. It's zero deploy, and runs over ssh.

You can run data intensive tasks over a bunch of servers, or you could just import the remote's "os" module and use "remotefile = remote.open('/home/remoteServerUser/cat.jpg', 'r')", and treat it like a normal file object.

Also stuff like 

I'd like to see a syntax something like the following, in xonsh. 

---
```
remoteServer = connectionObject("remoteServer.tld", "alex")
~ $ password prompt: ***

##Copy a file. Like scp, but a bit more flexable hopefully
remoteServer.xonsh("cat /home/remoteServerUser/cat.jpg) > /home/localUser/cat.jpg"

##Get the remote public IP address by asking a we service. We parse the reponse on the local machine
remoteIP=remoteServer.xonsh("""
from urllib import urlopen
remoteIP = str(urlopen('http://checkip.dyndns.com/').read())
re.compile(r'Address: (\d+\.\d+\.\d+\.\d+)').search(remoteIP).group(1)
"""
)

```

They syntax obviously feels really awful. It wouldn't(?) work with curses interfaces either, I think. No doing things like 

    remoteServer.xonsh("vim /home/remoteServerUser/log.txt")

And since vim (and everything else) doesn't work on python fileObjects, you can't do something like

    vim @(remoteServer.xonsh(/home/remoteServerUser/log.txt))

Getting tab completion from the remote xonsh instance would be extra awesome. No more seperate terminal for an ssh connection, and you can pipe things across computers without screwing around and learning new syntax.

With a fuse filesystem we might be able to solve the vim thing. Something like

    vim @(fuseOpen(remoteSever, "filePath"))

The fuseOpen would obviously return a local file path, and use the remoteServer's open() function to link the local file to the remote fileObject instance. Breaks tab completion though, presuming we manage to somehow get that working with the remoteServer.xonsh() method.

The syntax is problematic. And that's not even handling things like curses yet. I think the approach is more elegant then traditional ssh in a lot of ways. Well, when paired with xonsh's awesomeness. And the fact that xonsh wouldn't even need to be installed on the remote is definitly a plus.

Interested in hearing opinions (especially on syntax and tab completion) before I dive in and try to understand a bunch of freaky readline/RPyC stuff.

**Comment by scopatz** [comment]
> And since vim (and everything else) doesn't work on python fileObjects, you can't do something like

> `vim @(remoteServer.xonsh(/home/remoteServerUser/log.txt))`

Actually, as long as `remoteServer.xonsh(/home/remoteServerUser/log.txt)` returned something that could be eval'd into a string (or returned a list of strings) to file-like objects, this would work.  So if this call opened up a temporary file on the file system this could work.  

Personally, I'd love to see experimentation in this direction.  Before adding any syntax, though, I think there should be an underlying implementation.  (In general, I am not big on adding syntax, but if there was something the could support all kinds of remote execution we should consider it.)

**Comment by traverseda** [comment]
I've got the ssh authentication working, and I've even got xonsh running on the remote server. But it uses the local machines os and sys. Need to get better at monkey patching.

**Comment by scopatz** [comment]
@traverseda Cool :) Let us know when you have a PR.

**Comment by traverseda** [comment]
Still haven't had any time to work on this. My day job and startup are taking wayy too much time. Closing, since there's a shiny new thing I'd like to discuss.

**Comment by scopatz** [comment]
Haha OK.  You can always leave this open too :) Someone else may come along and resolve it...

**Comment by Shellcat-Zero** [comment]
Hey @traverseda and @scopatz, was there ever any solution for this? If not, it is something that I will probably work on. This would answer my question for https://github.com/xonsh/xonsh/issues/4589.
