### ISSUE TITLE
Subprocess exit code exception (bash "set -e")

### ISSUE THREAD

**Issue by rbrewer123** [scopatz/xonsh#220]
I saw some mention of subprocess exit codes under another issue but thought opening a separate issue would be best.   

The upcoming history mechanism may provide a useful way to fetch the exit code of a recently run process.  For scripts, it would also be nice to have a mechanism similar to "set -e" in bash, where any subprocess that exits with a non-zero exit code is considered an error.  For xonsh, perhaps this mode could raise a python exception similar to subprocess.check_call().  I would suggest raising exactly the CalledProcessError exception from the subprocess module. 

I think enabling this mode per-module via a module-level global variable would be convenient ("subprocess_check = True") and/or via a "with" statement ("with subprocess_check(True):").

**Comment by scopatz** [comment]
Hi @rbrewer123, thanks for noting this. I think this is good feature to have, just like traces (`set -x`).  The variable name might need to be special and/or namespaced (`__xonsh_subproc_check__`), but the general idea is good.  A context manager would also be nice.

**Comment by scopatz** [comment]
I believe that this has now been implemented.
