### ISSUE TITLE
Problem parsing a command ending with comment, like: $ ls # foo

### ISSUE THREAD

**Issue by naufraghi** [scopatz/xonsh#23]
```
$ ls # foo
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/xonsh/shell.py", line 92, in default
    self.execer.exec(code, mode='single', glbs=None, locs=self.ctx)
  File "/usr/local/lib/python3.4/site-packages/xonsh/execer.py", line 108, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
NameError: name 'ls' is not defined
```
Besides that, a very usable shell!

**Comment by scopatz** [comment]
Thanks for reporting @naufraghi - I think I know what the problem is.

Thanks!

**Comment by scopatz** [comment]
The problem has to do with the `subproc_line()` function being applied as `$[ls # foo]` instead of `$[ls] # foo`, for the interested.

**Comment by scopatz** [comment]
I believe that I have a fix for this on my `sl` branch @naufraghi. Would you please try it out?

**Comment by scopatz** [comment]
This should now be fixed on master

**Comment by naufraghi** [comment]
Sorry to be late, fix confirmed!

**Comment by naufraghi** [comment]
Some pointer to add a regression test if not already done?

**Comment by scopatz** [comment]
I did add some tests associated with this.
