### ISSUE TITLE
windows: shebang (#!) scripts don't work

### ISSUE THREAD

**Issue by rbrewer123** [scopatz/xonsh#233]
On Windows, running shebang scripts from xonsh generally doesn't work.  My preliminary investigation shows that _is_runnable_name() may be too restrictive and preventing the shebang-checking code from ever executing.  On Linux this is no big deal since Linux intrinsically can run shebang lines.  On Windows, this needs to be fixed.

I think a good answer here is for _is_runnable_name() to do an effective 'which' command to see if anything on the PATH may be runnable.  

For increased compatibility with msysGit, cygwin, and other unix-compatibility schemes on Windows, I think '#!' handling on Windows should additionally allow unix-style pathnames.  A simple way to do this is to check for a '#!' path starting with '/' and just take the basename of the path, relying on PATH lookup to find the right thing to execute.  Many '#!' scripts use '/usr/bin/env' anyway to perform a similar lookup of the correct file on the PATH.

Does this seem like a reasonable direction to go?

**Comment by wrywerytwreywery** [comment]
> I think a good answer here is for _is_runnable_name() to do an effective 'which' command to see if anything on the PATH may be runnable. 

When I wrote `_is_runnable_name`, it was only intended for running when invoking an executable by specifying its full name.  So I think it is important not to lose that, but extending it to also check whether the argument is an executable in the PATH seems like it should be fine.

> A simple way to do this is to check for a '#!' path starting with '/' and just take the basename of the path, relying on PATH lookup to find the right thing to execute. 
> Does this seem like a reasonable direction to go?

I'm no Windows expert, but I think that sounds pretty reasonable (though of course we don't want to do that on *nix systems).

Do you want to tackle these, or should I?  I might have some time this afternoon.

**Comment by rbrewer123** [comment]
@wrywerytwreywery it'll be a couple days until I could get back to this, so you're welcome to take it.  I think it's the highest priority issue on the Windows port.
