### ISSUE TITLE
windows: enable git branch checking

### ISSUE THREAD

**Issue by rbrewer123** [scopatz/xonsh#234]
Git branch checking is currently disabled on Windows due to it having really poor performance.  My first  implementation (the one that was too slow) attempted to run 'git' to check availability, since 'which' is not available on Windows.  A simple Python implementation of 'which' is probably the first thing to try to see if acceptable performance is achieved.  

If that's not enough, perhaps some very simple caching of the last branch state would be enough, with the cache being invalidated if any command is run.  For example, I will often press 'enter' several times in a row on the command line to create some visual space.  If the cached git branch were displayed in that case, the perception would be that it's very fast.  When I enter any command at all besides a blank line, if the prompt took a little longer it may not be as noticeable as in the case when I press enter several times in a row.

**Comment by wrywerytwreywery** [comment]
Hmmm my initial feeling would have been just to skip the other checks on Windows and do something like the following (from `current branch` in `env.py`):
```
        try:                                                                    
            cmd = ['git', 'rev-parse', '--abbrev-ref', 'HEAD']                  
            s = subprocess.check_output(cmd,                                    
                                        stderr=subprocess.PIPE,                 
                                        cwd=cwd,                                
                                        universal_newlines=True)                
            s = s.strip()                                                       
            if len(s) > 0:                                                      
                branch = s                                                      
        except subprocess.CalledProcessError:                                   
            pass                            
```

But that is slow on Windows?

One kludgy option (not sure how reliable it would be, but it might be faster) is to climb to directory tree looking for `.git/HEAD` and try to read the current branch from that.

**Comment by rbrewer123** [comment]
I hadn't tried your first idea.  My quick test is that although it's still slower than I'd prefer, it's within the realm of sanity and may be acceptable on faster hardware.  I'll work on a patch but it may be a couple days to get back to it.

**Comment by rbrewer123** [comment]
I'm getting faster at the process, so #238 is available.

**Comment by rbrewer123** [comment]
Closing this since branch checking was enabled on Windows (with marginal performance) by #238.  If performance is still an issue, we can open a separate issue later.
