### ISSUE TITLE
Problem parsing a command like $ git commit -m"message" (option arg with no space)

### ISSUE THREAD

**Issue by naufraghi** [scopatz/xonsh#24]
Without the space: :skull: 
```
matteo@pecetta.local ~ $ git commit -m"message"
........................ [] <- cursor here
```
With the space: :ok_hand:
```
matteo@pecetta.local ~ $ git commit -m "message"
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
	modified:   .bashrc

no changes added to commit
```

**Comment by scopatz** [comment]
So this isn't a bug, per say.  Quote provide the way to dump the content of the string directly as a single argument to the subprocess command.  This means avoiding a whole nest of nasty string syntax issues (especially regarding env variables) that BASH has.  In this particular case, you should be able to get away without the quotes at all:

```console
$ git commit -mmessage
```

Alternatively the following syntaxes should also be valid:

```console
$ git commit -m message
$ git commit -m "message"
$ git commit '-m"message"'
```

Even the following *might* work:

```console
$ git commit "-mthis whole thing is a message"
```

I think that the benefits to this are pretty huge, such as being able to use special characters (!, ?\\, $) in you message without needing to worry about it having some terrible side effect in the environment.

Also note that you should be able to use `b""`, `r""`, and `u""` without problems.

**Comment by scopatz** [comment]
I am going to close this issue.  Please reopen if you feel it was not properly addressed.

**Comment by naufraghi** [comment]
The rational is ok, but the UX problem remains.

Is it possible to detect this case and notify the user with the correct syntax?

**Comment by scopatz** [comment]
Yeah, we could show a meaningful error message. However, I think you'd always have to enter multi-line mode before hand.  Mutliline mode is entered when there is a syntax error on the first line.
