### ISSUE TITLE
Make tab work in multi-line input?

### ISSUE THREAD

**Issue by shoyer** [scopatz/xonsh#25]
It would be nice if I could use the tab key to indent four spaces if the first line of multiline input is something like a `for` loop. Even better, things could be automatically indented (like IPython).

**Comment by scopatz** [comment]
So it is not immediately apparent how to do automatic indenting.  And TAB is very strongly bound by readline to completion.  However, I did set up Shift-Tab to indent on 6336907.  The amount of indentation is controlled by $INDENT on start-up.  It is 4 spaces by default.  

Unfortunately, Ctrl-Tab is actually the same key press as just Tab. I'd be happy to consider other key-bindings or being able to customize this key-binding.  

Is this helpful enough? For the short term at least?

**Comment by shoyer** [comment]
Yes, shift+tab would do the trick.

I do wonder to what extent you might be able to leverage IPython console for some of these features....

**Comment by scopatz** [comment]
Yeah, I have thought of that too.  Maybe in a future version that can be the case. The `cmd.Cmd` interface was just to get started and to always be there so other dependencies can be optional.  Personally, I'd really like to see an IXonsh notebook too.

**Comment by scopatz** [comment]
Closing.
