### ISSUE TITLE
windows: startup failure with prompt-toolkit

### ISSUE THREAD

**Issue by rbrewer123** [scopatz/xonsh#256]
On Windows 8.1 running Python 3.4.3 and prompt-toolkit 0.37 (installed via ``pip install prompt-toolkit``), I get a traceback when I start xonsh with prompt-toolkit.  I also installed prompt-toolkit directly from the github master and got the same behavior.

```
C:\Users\rbrewer\xonsh>python -m xonsh.main --shell-type prompt_toolkit
☺☻rbrewer@rob-winbook☺☻ ~\xonsh ☺☻$☺☻ Traceback (most recent call last):
  File "C:\tools\python\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\tools\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rbrewer\xonsh\xonsh\main.py", line 92, in <module>
    main()
  File "C:\Users\rbrewer\xonsh\xonsh\main.py", line 88, in main
    shell.cmdloop()
  File "C:\Users\rbrewer\xonsh\xonsh\prompt_toolkit_shell.py", line 97, in cmdloop
    lexer=self.lexer)
  File "C:\Users\rbrewer\xonsh\xonsh\prompt_toolkit_shell.py", line 63, in get_user_input
    document = cli.read_input()
  File "C:\tools\python\lib\site-packages\prompt_toolkit\interface.py", line 321, in read_input
    self.eventloop.run(self.stdin, self.create_eventloop_callbacks())
  File "C:\tools\python\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 54, in run
    keys = self._console_input_reader.read()
  File "C:\tools\python\lib\site-packages\prompt_toolkit\terminal\win32_input.py", line 119, in read
    ev = getattr(ir.Event, EventTypes[ir.EventType])
KeyError: 0
Exception ignored in: <bound method PromptToolkitShell.__del__ of <xonsh.prompt_toolkit_shell.PromptToolkitShell object at 0x02AE3C10>>
Traceback (most recent call last):
  File "C:\Users\rbrewer\xonsh\xonsh\prompt_toolkit_shell.py", line 84, in __del__
  File "C:\Users\rbrewer\xonsh\xonsh\prompt_toolkit_shell.py", line 33, in teardown_history
AttributeError: 'module' object has no attribute '__xonsh_env__'
```

I got around the traceback from  ``__xonsh_env__`` but the initial ``KeyError`` traceback remained.  Considering that the prompt-toolkit README says it is not well-tested on Windows yet I suspect this is a prompt-toolkit bug but I'd like to do some more testing first.  If anyone else is able to confirm this behavior that would be helpful.

**Comment by anula** [comment]
I'd say that the later problem (exception in __del__) happens because of the previous one, but I am unfortunately unable to run it now on Windows, so I cannot confirm this behavior.

**Comment by rbrewer123** [comment]
I've done some more testing with prompt-toolkit on Windows.  My previous message about the startup crash was while running xonsh inside a ConEmu window.

When running xonsh with prompt-toolkit inside a ``cmd.exe`` window it starts without crashing, but prints a lot of escape characters as part of the prompt.  It is unusably slow on my hardware, and I was able to induce a crash by typing past the right side of the window (so the cursor wraps to the left side) and then attempting to backspace back across the right-side border.

When running inside a git bash window I see the same behavior as inside the cmd.exe window.

My next test will be to run prompt-toolkit's ``ptpython`` shell to see if I can reproduce any of this behavior with that.

**Comment by wrywerytwreywery** [comment]
I also get weird characters printed out as part of the prompt on GNU/Linux with prompt_toolkit (they seem to happen where the color escape sequences would be).

**Comment by rbrewer123** [comment]
Thanks to #339, xonsh seems to be running fine in both ConEmu and `cmd.exe` on my Windows 10 setup.  Interestingly, the drawing of the completion window is noticeably faster in ConEmu than in `cmd.exe`.  I've now opened #360 to track the raw color escape codes issue (which I've observed on Windows 10 and Ubuntu 14.04).
