### ISSUE TITLE
Vim refuses to come back to foreground with fg

### ISSUE THREAD

**Issue by roblabla** [scopatz/xonsh#265]
https://asciinema.org/a/0qa0ncj2izljo0oyr9wn3pi2u

When inside of vim, CTRL+Z works fine, however running the `fg` command fails, giving me the following output : 

```
*[1] running: vim (15707)

*[1] stopped: vim & (15707)
```

Running on archlinux.
Xonsh version : 0.1.6
Vim version : 7.4.729

**Comment by wrywerytwreywery** [comment]
Thanks for reporting this, @roblabla!

Not sure exactly what's going on, but I am able to reproduce this here.  I'll take a look when I have a chance.

**Comment by wrywerytwreywery** [comment]
I haven't had a chance to look too deeply into this yet, but this also happens with emacs (for those who are on the other side), though I haven't noticed this behavior with any programs aside from those two.

**Comment by adqm** [comment]
By now, I know a couple of "almost" fixes, but I am still working on something robust.
