### ISSUE TITLE
Files with non-standard characters

### ISSUE THREAD

**Issue by mankoff** [scopatz/xonsh#268]
Just an FYI that I had a file named `#foo` in `/tmp/`. I tried to delete it and xonsh supported auto-completion of `/tmp/#<TAB>`, but then interpreted the "#" as a comment and deleted the `/tmp` folder. Human error, but perhaps xonsh could escape file characters when TAB-completing the way bash does.

**Comment by scopatz** [comment]
Thanks for reporting.  It is a good idea that we are warming up to. Until then, you can always put the file name in quotes for it to be passed in literally as typed.

**Comment by ned2** [comment]
A limitation of the quoting workaround is that you can't use globbing to say delete all your `#` prefixed files, so having an explicit means of escaping `#` would indeed be most welcome.

**Comment by scopatz** [comment]
For what it is worth, I would just use regex globbing in this case.

**Comment by ned2** [comment]
Ah yes of course. Still absorbing xonsh's capabilities. Thanks @scopatz!

**Comment by ned2** [comment]
Actually, it seems like xonsh is interpreting `#` as a comment even inside a regex. Unless I'm missing something?

**Comment by adqm** [comment]
> Actually, it seems like xonsh is interpreting # as a comment even inside a regex. Unless I'm missing something?

Yep, confirmed here.  This is definitely a parsing bug (well, actually, a lexing bug).  I think I know how to fix.

**Comment by adqm** [comment]
@ned2, I just put in #943, which I believe should fix this..  Do you mind giving that a whirl?

**Comment by scopatz** [comment]
Also, you can use the super-verbose `ls @(__xonsh_glob__("#*"))` if you just need to get something working :)

**Comment by ned2** [comment]
@adqm, looks good! Was able to conveniently delete a bunch of octothorpe-riddled stale emacs autosave files.

**Comment by scopatz** [comment]
Great! @mankoff feel free to close this.  In your original case, you could use strings around the file name, though you could also use regex globbing.
