### ISSUE TITLE
Parsing of .bashrc aliases

### ISSUE THREAD

**Issue by janpipek** [scopatz/xonsh#269]
I have aliases in .bashrc with quotes in them like this:

```shell
alias alias1='python -c "print(4 + 4)"'
alias alias2="python -c 'print(4 + 4)'"
```

While the first one works, the second one does not:

```
    /home/honza/anaconda/envs/py34/lib/python3.4/site-packages/xonsh/aliases.py:84:
    RuntimeWarning: could not parse Bash alias "alias2": ValueError('No escaped character',)  
    RuntimeWarning)
```

It is a minor issue (everyone should be able to rewrite the aliases), still I think it is worth fixing.
In any case, thanks for xonsh :-)

**Comment by scopatz** [comment]
Ahh I think I see why this is the case. This is because Bash treat single and double quotes differently, resulting in the funny behaviour of:

```console
scopatz@athenaie ~ BA$H alias alias1='python -c "print(4 + 4)"'
scopatz@athenaie ~ BA$H alias alias2="python -c 'print(4 + 4)'"
scopatz@athenaie ~ BA$H alias 
alias alias1='python -c "print(4 + 4)"'
alias alias2='python -c '\''print(4 + 4)'\'''
```

Regardless this should be fixable.

**Comment by scopatz** [comment]
Thanks for reporting.

**Comment by janpipek** [comment]
Seems like commit 5981ffd3b93b5c9014e2841d186ae448e8ca9a90 solves this.

**Comment by scopatz** [comment]
Great!  Do you feel that this can be closed then?

**Comment by janpipek** [comment]
I would think so :-) At least it did work for me. Thanks, @mic-e
