### ISSUE TITLE
fish inspired autocompletion suggestions

### ISSUE THREAD

**Issue by eskhool** [scopatz/xonsh#272]
xonsh is the future! (or so we thin :+1:  :)
However, the real time autocompletion in fish is awesome. Can we use this thread to get a head start on the best approach for the same? 
@scopatz if you could put the places in the code where one should start, maybe somebody (me? :D) will send a PR

**Comment by scopatz** [comment]
Hi @eskhool - yep fish autocompletion is awesome and is definitely worth emulating!  The right place to start is by looking at the completer.py module (https://github.com/scopatz/xonsh/blob/master/xonsh/completer.py). This could certainly use some improvements.

**Comment by scopatz** [comment]
There is preliminary man page completion, but I think that this could use some updates too.

**Comment by mdraw** [comment]
https://github.com/jonathanslenders/python-prompt-toolkit/commit/9431b94322e84eaa3d9f7ea8da91716927365ea1
An implementation of fish's marvellous right-arrow completion system is now available in prompt_toolkit 0.52.
I tested it on ptipython and it works perfectly, exactly like fish. Can we easily enable support for this feature in xonsh in prompt_toolkit mode?

**Comment by mdraw** [comment]
https://github.com/scopatz/xonsh/compare/master...mdraw:patch-1 This small change should add support for fish-style auto-suggestions, but there are two issues with it:
1. The actual completion by pressing the right arrow key won't work, since xonsh does not seem to send keycodes to prompt_toolkit like e.g. ptpython does.
2. The suggestions have the same text color as the user-written text. This is confusing. The suggestion should be in another color. An example of what it looks like in fish (I wrote "xonsh --sh", the rest is an auto-suggestion):
![fish](https://cloud.githubusercontent.com/assets/6719909/10123241/07527c44-6535-11e5-9dd5-c338f04fad0c.png)

**Comment by scopatz** [comment]
Hi @mdraw - cool!  Would you mind opening up a pull request please?

**Comment by scopatz** [comment]
PS - I think that this would be *extremely* valuable to have.

**Comment by mdraw** [comment]
I agree that this feature will be fantastic to have, but the patch I provided isn't ready to be merged. I thought I'd open a pull request as soon as I or someone else has solved the two issues I've mentioned above. In the current form it would be useless and confusing.
(Or should I do a pull request for this work-in-progress anyways? I am quite new to pull requests in general, so I don't know if I should.)

**Comment by scopatz** [comment]
@mdraw, yeah, open the pull request anyway and mention that it is a work in progress and the outstanding issues in the text of the PR. It gives the all of us a central place to work off of.

**Comment by mdraw** [comment]
Oh well, just as I wanted to open the PR I stumbled upon this: https://github.com/jonathanslenders/xonsh/commit/77c69a91736709e78ad789a8cdde2e6d89f2493d, so I am sure we will get a proper pull request from @jonathanslenders very soon.

**Comment by scopatz** [comment]
Haha no worries

**Comment by scopatz** [comment]
I believe that this has been implemented via prompt-toolkit. Please reopen if you feel otherwise.

**Comment by denfromufa** [comment]
I do not get autocompletion, only tab-completion. How do I get it working?

**Comment by scopatz** [comment]
@denfromufa are you using the prompt-toolkit shell?

**Comment by denfromufa** [comment]
@scopatz how to I know/enable prompt-toolkit shell? I vaguely remember how I did it on Windows, but currently I'm on Linux

**Comment by scopatz** [comment]
You have to have the ptk insalled and then set this in the rc file or on the command line: http://xon.sh/envvars.html#shell-type

**Comment by denfromufa** [comment]
`xonsh --shell-type prompt_toolkit`

still not working!

**Comment by denfromufa** [comment]
```
xonsh --help
usage: xonsh [-h] [-V] [-c COMMAND] [-i] [-l] [--config-path CONFIG_PATH]
             [--no-rc] [--no-script-cache] [--cache-everything]
             [-D [ITEM [ITEM ...]]]
             [--shell-type {readline,prompt_toolkit,best,random}]
             [script-file] [args [args ...]]

xonsh

positional arguments:
  script-file           If present, execute the script in script-file and exit
  args                  Additional arguments to the script specified by
                        script-file

optional arguments:
  -h, --help            show help and exit
  -V, --version         show version information and exit
  -c COMMAND            Run a single command and exit
  -i, --interactive     force running in interactive mode
  -l, --login           run as a login shell
  --config-path CONFIG_PATH
                        specify a custom static configuration file
  --no-rc               Do not load the .xonshrc files
  --no-script-cache     Do not cache scripts as they are run
  --cache-everything    Use a cache, even for interactive commands
  -D [ITEM [ITEM ...]]  define an environment variable, in the form of
                        -DNAME=VAL. May be used many times.
  --shell-type {readline,prompt_toolkit,best,random}
                        What kind of shell should be used. Possible options:
                        readline, prompt_toolkit, random. Warning! If set this
                        overrides $SHELL_TYPE variable.
```

**Comment by scopatz** [comment]
What is your value for http://xon.sh/envvars.html#auto-suggest?

**Comment by denfromufa** [comment]
True

**Comment by scopatz** [comment]
Can you post an asciinema that demos the problem or a screenshot please? That would be very helpful.. Thanks!

**Comment by denfromufa** [comment]
https://asciinema.org/a/3mtlsc9i0z1ambgee3mbtrmky

**Comment by scopatz** [comment]
Ahh I see, I think you are hitting TAB instead of the right arrow to complete the suggestion.  This is mentioned in the docs: http://xon.sh/envvars.html#auto-suggest

**Comment by gforsyth** [comment]
Hey @denfromufa, the autosuggestion is populated from your history. When
you type `import i` in the asciicinema you can see a light gray suggestion
text appear. To select this you can hit right arrow.

**Comment by denfromufa** [comment]
looks like I got spoiled by ptipython and IDEs with auto completion. Auto
suggestion or tab completion is all I get in xonsh.

**Comment by denfromufa** [comment]
By auto completion I really mean something like intellisense in PTVS

**Comment by scopatz** [comment]
Ahh I see what you are referring to. I think that this is related to the fuzzy matching, fzf, and jedi issues.  However, we would still need the feature to auto suggest options.  More like autocompletions, I guess.

Would I happy to accept a PR that implements this.

**Comment by ShalokShalom** [comment]
> Ahh I see what you are referring to. I think that this is related to the fuzzy matching, fzf, and jedi issues. However, we would still need the feature to auto suggest options. More like autocompletions, I guess.
> 
> Would I happy to accept a PR that implements this.

You added help-wanted, and forgot to reopen the issue.

Now here I am, almost 10 years later. 😅

Therr is now a package that provides what this issue really was about, although it is already a bit dated, it makes a good impression:

https://github.com/xonsh/xontrib-fish-completer
