### ISSUE TITLE
fish syntax high lighting

### ISSUE THREAD

**Issue by eskhool** [scopatz/xonsh#273]
Since every command is differentiated between subprocess and python, some color coding could dynamically indicate the same. Also, some other commands like ${, $[ could benefit from color distinction on a real time basis. Could be done with autocompletion suggestions to make the interactivity much better and get xonsh towards shell perfection (IMHO obviously)

**Comment by scopatz** [comment]
I think that if you use the prompt-toolkit shell (set `$SHELL_TYPE = 'prompt_toolkit'` in xonshrc, see http://xonsh.org/tutorial.html#environment-variables) you get this behaviour

**Comment by gforsyth** [comment]
Syntax highlighting is available -- please reopen if it's not working as expected.
