### ISSUE TITLE
Update Install Documentation to Include Instructions for Homebrew and Pacman

### ISSUE THREAD

**Issue by hjc1710** [scopatz/xonsh#275]
Acoording to [this tweet](https://twitter.com/scopatz/status/613383868851183616) from @scopatz, `xonsh` is actually **in** Homebrew and the AUR. Unfortunately, instructions for installing `xonsh` through either of these PM's is missing from the website, misleading users into using pip/conda when they don't have to.

Updating the docs on the site to reflect that you can use pacman or homebrew to get `xonsh` would be a good move, IMO. If I ran Arch or OSX, I would test these and add myself, but I'm a Debian man.

**Comment by kseistrup** [comment]
Xonsh can be install from AUR with

```sh
yaourt -Sa xonsh
```

or

```sh
sudo aura -A xonsh
```

**Comment by scopatz** [comment]
Awesome!  Could you open up a PR for this, please?

**Comment by kseistrup** [comment]
I haven't looked at how Xonsh is documented yet, but let me give it a try…

**Comment by scopatz** [comment]
Thanks!  I think you want to edit this file: https://github.com/scopatz/xonsh/blob/master/docs/index.rst

**Comment by kseistrup** [comment]
Perhaps I was too early when I said my pull request would close this issue, OP also wanted homebrew instructions…

**Comment by scopatz** [comment]
Yep.  Reopening.

**Comment by gforsyth** [comment]
Homebrew instructions added in #1114
