### ISSUE TITLE
sudo with xonsh (git master) on mac os x 10.10 (yosemite)

### ISSUE THREAD

**Issue by eskhool** [scopatz/xonsh#276]
when I run sudo I get the following error

xonsh: subprocess mode: permission denied: sudo

It works fine with bash.

**Comment by esafak** [comment]
This is still a problem with 0.2. Note that sudo works if you first invoke xonsh with sudo.

**Comment by scopatz** [comment]
Hmm what is the result of:

```console
$ ls -l $(which sudo)
```

**Comment by scopatz** [comment]
Also, can you turn on the full traceback and report that, please? Thanks!

**Comment by esafak** [comment]
This seems to be resolved with 0.2

**Comment by scopatz** [comment]
Awesome :)

**Comment by scopatz** [comment]
I am going to close this issue, then.  Please feel free to reopen.
