### ISSUE TITLE
Using xonsh with conda environments on windows

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#277]
Hi all

Maybe some Anaconda/Windows users will find this useful. 

I had some trouble getting xonsh to play nice with conda environments on Windows. 

On windows, the environments are controlled by two bat-file scripts that add or remove the environments from the path variable and change the prompt. I mange to get the prompt working but calling activate/deactivate from within xonsh didn't seem to change the $PATH variable in xonsh. 

So I ended fixing it by writing Python versions of the deactivate/activate scripts. Just add them to the .xonshrc file. 

``` python 

import os
import builtins

def _deactivate(args, stdin=None):
    # Cal anaconda.bat script to ensure that 'ANACONDA_ENVS' exist as an 
    # environment variable
    $(anaconda.bat)
    if args:
        print("Usage: deactivate\n"
              "\n"
              "Deactivates previously activated Conda\n"
              "environment")
        return
    if 'CONDA_DEFAULT_ENV' not in builtins.__xonsh_env__:
        return
    print("Deactivating environment "+  $CONDA_DEFAULT_ENV +"...")
    $PATH = list(filter( os.path.join($ANACONDA_ENVS,$CONDA_DEFAULT_ENV).__ne__, $PATH))
    $PATH = list(filter( os.path.join($ANACONDA_ENVS,$CONDA_DEFAULT_ENV,"Scripts").__ne__, $PATH))
    del $CONDA_DEFAULT_ENV
    del $CONDA_ENV_PATH

def _activate (args, stdin=None):
    # Cal anaconda.bat script to ensure that 'ANACONDA_ENVS' exist as an 
    # environment variable
    $(anaconda.bat)
    if len(args) != 1:
        print("Usage: activate envname\n"
              "\n"
              "Deactivates previously activated Conda\n"
              "environment, then activates the chosen one.")
        return
    new_environment = args[0]
    if not os.path.isdir(os.path.join( $ANACONDA_ENVS, new_environment)):
        print ("No environment named "
               + new_environment + 
               " exists in " + $ANACONDA_ENVS)
        return
    if 'CONDA_DEFAULT_ENV' in builtins.__xonsh_env__:
       _deactivate([], stdin)
    $CONDA_DEFAULT_ENV = new_environment
    $CONDA_ENV_PATH = os.path.join($ANACONDA_ENVS, $CONDA_DEFAULT_ENV)
    print("Activating environment " + $CONDA_DEFAULT_ENV + "...") 
    $PATH.insert(0,os.path.join($ANACONDA_ENVS,$CONDA_DEFAULT_ENV,"Scripts"))
    $PATH.insert(0,os.path.join($ANACONDA_ENVS,$CONDA_DEFAULT_ENV))

aliases['deactivate'] = _deactivate
aliases['activate'] = _activate
   
$FORMATTER_DICT['conda'] = lambda: "["+$CONDA_DEFAULT_ENV+"]" if 'CONDA_DEFAULT_ENV' in builtins.__xonsh_env__ else ""
$PROMPT = '{conda}'+$PROMPT 

```

**Comment by scopatz** [comment]
Hi @melund! Thanks for letting us know about this!  Where do you think that the right place for this to live is?  My sense would be that it would be great for conda itself to have these, but perhaps xonsh could provide them too.

**Comment by melund** [comment]
Well. I don't know. I hope xonsh will grow enough so that the conda project can't ignore it. Any way they are really only useful for conda users on windows. The activate/deactivate bat-scripts in windows are horrible. But it probably couldn't be done in any other way. 

Using the conda environments from xonsh can be a little awkward. Since xonsh only lives in a single environment, changing the environment only changes the behavior of the subprocess part. 

Btw. I noticed that when I run `conda install <some package>` then I can't import the package until I restart the xonsh shell. Not a big deal though. 

Thanks for an awesome tool. Suddenly, my python skills have made me a shell master :) I wish I had more time to contribute.

/Morten

**Comment by scopatz** [comment]
> Using the conda environments from xonsh can be a little awkward. Since xonsh only lives in a single environment, changing the environment only changes the behavior of the subprocess part. 

We should work to eliminate any of the awkwardness. I never use different conda virtual environments, personally, so I'm relying on other to report and to help out with this.

> Btw. I noticed that when I run conda install <some package> then I can't import the package until I restart the xonsh shell. Not a big deal though. 

Yeah, I think this is a conda-specific issue. Maybe there is a way to refresh the `sys.path`

> Thanks for an awesome tool. Suddenly, my python skills have made me a shell master :) I wish I had more time to contribute.

Thanks :)

**Comment by melund** [comment]
I would like to have the conda installer to add the activate/deactivate scripts somewhere. But writing to  the user .xonshrc is not nice. Is there any system wide xonshrc file that could be used for that purpose?

**Comment by scopatz** [comment]
Hi @melund.  There is not currently a system-wide xonshrc file, only the user one.  That said, there probably should be...  PRs welcome.

**Comment by gforsyth** [comment]
@melund @scopatz 
I'm playing around with adding in a system-wide xonshrc file.  I have a toy example working on linux.  

I figure for Linux, the system-wide file should live in `/etc/xonshrc`.  
Is this a reasonable choice for OSX, too?

And @melund, do you have thoughts on where a system-wide xonsh file would live on Windows?

**Comment by scopatz** [comment]
> I'm playing around with adding in a system-wide xonshrc file. I have a toy example working on linux

Awesome. Thanks

**Comment by melund** [comment]
@tritemio I saw you request for an conda activate script for windows https://github.com/scopatz/xonsh/issues/488 . I haven't tested this for while and the activate scripts in anaconda have been update few times since. So there may be some work in updating the script.

My original plan was to have the conda packages for windows add these scripts to the user or system xonshrc file. That would be the nice solution. You welcome to help with task, as I haven't go much time before christmas...

**Comment by melund** [comment]
Considering the changes that are being made at the moment to the activate/deactivate scripts https://github.com/conda/conda/pull/1727 It may be better to wait. It may become trivial to get conda environements working with xonsh

**Comment by scopatz** [comment]
Thanks for letting us know about that conda issue @melund. It would be super nice for conda to have better xonsh support too.

**Comment by melund** [comment]
I think this is made obsolete by the ability to source bat files. https://github.com/scopatz/xonsh/pull/790

The PR also adds aliases that calls the activate/deactivate bat scripts
