### ISSUE TITLE
Path auto complition for vim returns error

### ISSUE THREAD

**Issue by pdavydov108** [scopatz/xonsh#28]
Hi, thanks for this new cool shell, I realy like it! The only problem I've got so far is when I type 'vim ' and then press tab button it prints error message "/usr/share/bash-completion/bash_completion: line 1856: compopt: not currently executing completion function" instead of list of files in a directory. If I press tab again, it shows files as usual, but the error message is still printed to command line, so path becomes unreadable. Example:

    pablo@alien /some/path branch $ vim /usr/share/bash-completion/bash_completion: line 1856: compopt: not currently executing completion function
    /usr/share/bash-completion/bash_completion: line 1856: compopt: not currently executing completion function
    
    .git/                 AUTHORS               GPATH                 MinSizeRel/           benchmark/            dependencies/

**Comment by scopatz** [comment]
Thanks for reporting @pdavydov108! This should be fixed now

**Comment by scopatz** [comment]
Thanks for reporting @pdavydov108! This should be fixed now
