### ISSUE TITLE
xonsh on ubuntu does not suggest missing packages

### ISSUE THREAD

**Issue by eskhool** [scopatz/xonsh#280]
In bash presently, giving any command gives us the following helpful completion. Logging the issue here to track such enhancements (somehow bash in ubuntu must be trapping the command not found and using apt to complete..it is a useful function)

The program 'nethogs' is currently not installed. You can install it by typing:
sudo apt-get install nethogs

**Comment by scopatz** [comment]
Thanks for bringing this up! I'll see if I can figure out how to get this to work.

**Comment by scopatz** [comment]
#287 adds this capability.

**Comment by scopatz** [comment]
closed by #287
