### ISSUE TITLE
Usable if system Python is not version 3.4?

### ISSUE THREAD

**Issue by reckoner** [scopatz/xonsh#29]
Will this work if my system Python is 2.7?

**Comment by xliiv** [comment]
I can't answer your question, but i think it's easy to install python 3.4 unless you don't have admin privileges. Can you describe your case, why wouldn't you want use python 3.4 :)

**Comment by reckoner** [comment]
You got it! I don't have admin rights on the machine(s) I work on :(.

**Comment by scopatz** [comment]
Hi @reckoner - this xonsh is Python 3.4 only.  If you don't have admin rights on your machine, I recommend installing Anaconda or Miniconda (stripped down anaconda), and using conda to install xonsh.  Anaconda and Miniconda both are meant to be used solely from within your userspace.

**Comment by scopatz** [comment]
I am closing this issue. Please reopen if you feel it was not addressed.
