### ISSUE TITLE
Write tab completion functionality in Python

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#298]
Right now, you have to write them in Bash, and that is no good.

**Comment by BYK** [comment]
Any pointers about where to start? I'm assuming we'd need a compatibility layer for existing bash completers.

**Comment by scopatz** [comment]
Hi @BYK. Sure thing.  There is an existing Completer class in completer.py. This implements bash-completion, man page completion (though this needs more testing), and python object introspection completion.  

What we don't have right now is a way for users or ourselves to write and register external functions with this completion class.  Such functions should probably be keyed on the command name (ls, cd, etc).  Completion functions should have to follow a well-defined API that has arguments for the line, current position, current token, etc. and should return an iterable (though a set is recommended).

Does this make sense?  Let me know if you have any more questions!

**Comment by BYK** [comment]
@scopatz it does make sense, yeah! :)

>Completion functions should have to follow a well-defined API that has arguments for the line, current position, current token, etc. and should return an iterable (though a set is recommended).

I completely agree with this. I also think we need a converter for bash-completion and potentially other strong and established completion syntax such as `zsh`. What do you think?

My main complaint right now is not being able to use any completions under Windows (except for file names).

**Comment by scopatz** [comment]
> My main complaint right now is not being able to use any completions under Windows (except for file names).

Sure that makes sense. The more ways we can get completions the better!

**Comment by gforsyth** [comment]
Closed via #1076
