### ISSUE TITLE
Feature request: loop over system results

### ISSUE THREAD

**Issue by michaelaye** [scopatz/xonsh#310]
Playing for the first time with xonsh, I was hoping something simple like this would work:
```python
for fname in ls:
    print(fname)
```
but I get this error:
```python
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/xonsh/base_shell.py", line 42, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/xonsh/execer.py", line 127, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
NameError: name 'ls' is not defined
```
which is confusing because on its own `ls` is defined, so I guess that's a grammar problem to see that I want to execute `ls` in the middle of the python code. But I thought that was the idea of xonsh?

**Comment by scopatz** [comment]
Try the following:

```bash
for fname in $(ls).split():
   print(fname)
```

This is basically the same as what Bash makes you do when looping as well. If you want to loop over a command, you have to call that command either in $() or in backticks.

**Comment by scopatz** [comment]
The difference between Bash and xonsh here is that Bash $() will split on whitespace automatically (unless you set the IFS variable), while xonsh $() will return you a Python string.

**Comment by scopatz** [comment]
Note that this exact case is the first loop example in the Bash docs: http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-7.html

**Comment by michaelaye** [comment]
Both your suggestions are not working for me:
```python
klay6683@MacL2938 ~/.ipython $ ls
README            kernels           profile_diviner   profile_profiling
cython            nbextensions      profile_iuvs      profile_pyciss
extensions        profile_default   profile_planet4   profile_pymars
klay6683@MacL2938 ~/.ipython $ for fname in `ls`:
..............................     print(fname)
..............................
klay6683@MacL2938 ~/.ipython $ for fname in ${ls}:
..............................     print(fname)
..............................
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/xonsh/base_shell.py", line 42, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/xonsh/execer.py", line 127, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
NameError: name 'ls' is not defined
```

**Comment by scopatz** [comment]
Please use the `$(ls)` operator, like in Bash, to capture a subprocess - [see here](http://xonsh.org/tutorial.html#captured-subprocess-with).  Curly braces, `${ls}` look up environment variables in both bash and xonsh, and don't execute subprocesses. 

Backticks in Bash (``` `ls` ```) are redundant (and somewhat deprecated). In xonsh, backticks are used to implement regular expression file globbing. http://xonsh.org/tutorial.html#regular-expression-filename-globbing-with-backticks

 Please try exactly the example I gave:

```python
for fname in $(ls).split():
   print(fname)
```

**Comment by scopatz** [comment]
Note that the `$(ls)` is in parentheses.

**Comment by michaelaye** [comment]
oh, damn, shouldn't have watched that last episode of Sens8 anymore, could have sworn I typed it off correctly, sorry! Can I switch xonsh to split on space automatically, like bash does? I would prefer to minimize typing efforts for standard tasks, at least that would be a great motivator for switching shells.

**Comment by scopatz** [comment]
> Can I switch xonsh to split on space automatically, like bash does? I

We don't have that feature yet.  There are a few ways to do this, one of which might be a new operator. Could you open a new issue for this feature request please? Also, pull requests very welcome :)
