### ISSUE TITLE
Auto-completion doesn't expand ~/

### ISSUE THREAD

**Issue by mbollmann** [scopatz/xonsh#33]
Pressing TAB for auto-completion doesn't expand ~, making it difficult to auto-complete filenames in the home directory.

I identified [the line that would probably need to be changed](https://github.com/scopatz/xonsh/blob/master/xonsh/completer.py#L86), but I'm not sure whether `os.path.expanduser` or some of the internally defined globbing functions from built_ins.py would be more appropriate.

**Comment by scopatz** [comment]
I think that expanduser() is correct. The `built_ins` ones are for regex globbing (which does expand user). This might also affect the `bash_complete()`method.

**Comment by mbollmann** [comment]
It does indeed. Not sure where the expansion belongs in `bash_complete()` though.

**Comment by scopatz** [comment]
Ok @mbollmann - this should now be fixed in master.

**Comment by wrywerytwreywery** [comment]
Woo-hoo!  This is great.  Seems to be working for me.

**Comment by mbollmann** [comment]
Great work, thanks!
