### ISSUE TITLE
Env variables doesn't expand to paths in sub process mode.

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#338]
Environment variables can't be used to create a path in subprocess mode: 

For example on windows: `cd $USERPROFILE` works fine. 

But `cd $USERPROFILE/Documents` does not.  Pressing tab in the shell causes the autocompleter to expand the path. 

So not a big issue in an interactive shell. But typing something like that in a file or having it in an alias doesn't work. 

@michaelaye initially reported this:
https://github.com/scopatz/xonsh/pull/319#issuecomment-125018134
```
klay6683@MacL2938 ~ $ aliases['cdsrc']
['cd', '$HOME/Dropbox/src']
klay6683@MacL2938 ~ $ cdsrc
cd: no such file or directory: $HOME/Dropbox/src
```

**Comment by scopatz** [comment]
I think that we need to start having tests for some of these aliases too.

**Comment by scopatz** [comment]
I remember this used to work.

**Comment by melund** [comment]
This has been fixed

**Comment by seanfarley** [comment]
With the latest xonsh (0.4.5) this is broken again.

**Comment by scopatz** [comment]
I think it does if you put them in quotes for some reason. Of course, it should always...
