### ISSUE TITLE
Semicolon not able to separate shell commands?

### ISSUE THREAD

**Issue by wrywerytwreywery** [scopatz/xonsh#35]
The semicolon works fine to separate Python statements, e.g.:

> ~ $ x = 7; print(x)
> 7

But it does not seem to work to separate shell commands.  For example:

> ~ $ ls ; echo "hey"
> ls: cannot access ;: No such file or directory
> ls: cannot access echo: No such file or directory
> ls: cannot access hey: No such file or directory

or

> ~ $ cd Desktop; echo "hello"
> cd takes 0 or 1 arguments, not 3

**Comment by scopatz** [comment]
This is related to #23, which I am working on a fix for now.

**Comment by scopatz** [comment]
Thanks for reporting @wrywerytwreywery! I believe I have a fix for this on my `sl` branch.  Would you be willing to try it out, please?

**Comment by wrywerytwreywery** [comment]
Looks great!  Just tried out a few things, and it seems to be working as I would expect it to.

**Comment by scopatz** [comment]
Awesome! I am going to merge it in then.
