### ISSUE TITLE
add a travis job with tests and code checks

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [scopatz/xonsh#350]
that would be a nice add-on for pull requests and in general

remember to use the non-sudo infrastructure

**Comment by scopatz** [comment]
Unless I am missing something, I believe Travis does run the tests.

**Comment by RonnyPfannschmidt** [comment]
it seems like it didn't do anything on my web ui commit, however now it happens just fine on the push

sorry for he confusion

**Comment by scopatz** [comment]
No worries!
