### ISSUE TITLE
xonsh cannot run binaries with mode 4111

### ISSUE THREAD

**Issue by larsks** [scopatz/xonsh#354]
Trying to run `sudo` with `xonsh` results in a "permission denied" error.  This is because `sudo` is often installed mode 4111:

    # ls -l /bin/sudo
    ---s--x--x. 1 root root 130824 Feb 18 05:02 /bin/sudo

This causes the call to `_is_binary(...)` to fail, since there are no read permissions on this file.

**Comment by scopatz** [comment]
Closed by #356
