### ISSUE TITLE
Prompt broken in Emacs' ansi-term

### ISSUE THREAD

**Issue by jmgrosen** [scopatz/xonsh#358]
When I try to run xonsh in Emacs' ansi-term (like `(ansi-term "/usr/bin/xonsh")`), the prompt looks like this:
```
2;john@at-at: /home/angr/angr/driller/tracer | xonshjohn@at-at /home/angr/angr/driller/tracer largescale $ 
```
Needless to say, this is not ideal :) The hexdump seems to suggest the prompt is getting put out twice, with some escape codes in the middle:
```
$ xonsh | hexdump -C
00000000  1b 5d 32 3b 6a 6f 68 6e  40 61 74 2d 61 74 3a 20  |.]2;john@at-at: |
00000010  2f 68 6f 6d 65 2f 61 6e  67 72 2f 61 6e 67 72 2f  |/home/angr/angr/|
00000020  64 72 69 6c 6c 65 72 2f  74 72 61 63 65 72 20 7c  |driller/tracer ||
00000030  20 78 6f 6e 73 68 07 01  1b 5b 31 3b 33 32 6d 02  | xonsh...[1;32m.|
00000040  6a 6f 68 6e 40 61 74 2d  61 74 01 1b 5b 31 3b 33  |john@at-at..[1;3|
00000050  34 6d 02 20 2f 68 6f 6d  65 2f 61 6e 67 72 2f 61  |4m. /home/angr/a|
00000060  6e 67 72 2f 64 72 69 6c  6c 65 72 2f 74 72 61 63  |ngr/driller/trac|
00000070  65 72 01 1b 5b 31 3b 33  31 6d 02 20 6c 61 72 67  |er..[1;31m. larg|
00000080  65 73 63 61 6c 65 20 01  1b 5b 31 3b 33 34 6d 02  |escale ..[1;34m.|
```
My guess is that ansi-term doesn't support some escape codes necessary, but it would be nice if there were some way to avoid using those when an Emacs terminal is detected, as I use them for everyday use.

The fix is probably something similar to the fix necessary for fish: https://github.com/fish-shell/fish-shell/issues/107

**Comment by jmgrosen** [comment]
...and that fish issue turned out to be exactly the issue here :) Adding `del $TITLE` to my `.xonshrc` did the trick. You might want to make that the default for `TERM=eterm-color` somewhere, but I'm closing this issue for now.

**Comment by scopatz** [comment]
Hi @jmgrosen - Thanks for reporting. Is there any way that we can detect that we are being run from within emacs and disable $TITLE?  If so, would you mind putting in a PR, please?

**Comment by emacs18** [comment]
For shell buffers within emacs created via "M-x shell" command, the TERM environment variable is "dumb".  This may be the best one to use, e.g.,
# Set $TITLE to None to prevent messed up prompt in shell running within emacs.
if $TERM == "dumb": $TITLE = None

In case it matters, the EMACS variable is also set with value of "t" within emacs.
Also INSIDE_EMACS variable is set.

**Comment by scopatz** [comment]
Pull requests welcome!

**Comment by emacs18** [comment]
The lines in my ~/.xonsh is shown below.
I'm not sure where this information should be added. 
By pull request, do you mean to update the documentation on setting up?
If not, then I'm afraid I don't understand where this ought to go.

# The default prompt is messed up in shells running within emacs.
# So set $TITLE to None as a work around.  Rely on the value of TERM
# to detect shells within emacs.
if $TERM in ["dumb", "eterm-color"]:
   $TITLE = None

**Comment by scopatz** [comment]
@emacs18, I think that the $TITLE variable may also be a function in addition to being a string. Thus it should be possible to write a simple function for $TITLE that checks the value of $TERM or any other state of the environment. Then we could have this function as the default instead of what is there currently.  Does this make sense?

**Comment by emacs18** [comment]
No, not based on my reading of the code.

The reason why setting $TITLE to None worked me is that settitle() shown below
checks for this and just returns before calling format_prompt(). However if
$TITLE is a function, then format_prompt() is called which checks to see if
$TITLE is callable or not. No matter what happens within format_prompt(), the
problem is that we end up executing the last line of settitle() which prints
"\x1b]2;{0}\x07" which is shown within emacs as "^[]2;^G", i.e., garbled
prompt.

```python
    def settitle(self):
        """Sets terminal title."""
        env = builtins.__xonsh_env__
        term = env.get('TERM', None)
        if term is None or term == 'linux':
            return
        t = env.get('TITLE')
        if t is None:
            return
        t = format_prompt(t)
        if ON_WINDOWS and 'ANSICON' not in env:
            t = escape_windows_title_string(t)
            os.system('title {}'.format(t))
        else:
            sys.stdout.write("\x1b]2;{0}\x07".format(t))
```

**Comment by emacs18** [comment]
How about the this one line change in settitle()?
Change

```python
        if term is None or term == 'linux':
```
to

```python
        # Shells running in emacs sets TERM to "dumb" or "eterm-color".
        # Do not set title for these to avoid garbled prompt.
        if term is None or term in ["dumb", "eterm-color", 'linux']:
```
If this is ok with you, I'll submit a pull request.
