### ISSUE TITLE
prompt-toolkit shell displays raw color escape codes in prompt

### ISSUE THREAD

**Issue by rbrewer123** [scopatz/xonsh#360]
Currently when using the prompt-toolkit shell (`$SHELL_TYPE='prompt_toolkit'`), xonsh displays what appear to be raw color escape codes when using a prompt that contains color formatting.  The current workaround (suggested by @melund in #339) is to set a non-color prompt, e.g. `$PROMPT='$ '`.  He also reports that this problem may be due to prompt-toolkit using pygments escape codes for highlighting.

**Comment by rbrewer123** [comment]
Looks like there is some more discussion of the color escape codes toward the end of #214.

**Comment by melund** [comment]
@rbrewer123 ... I think it was the other way around. @jonathanslenders  mentioned that we ought to use pygments tokens to avoid hard-coded color codes which is not supported in all teminals.

**Comment by jonathanslenders** [comment]
That's true. Have a look at this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/b396ccc3778d120f893e421a3342a92641c541f0/examples/colored-prompt.py

But of course, if it is really, really important to have hard-coded ANSI colors in configurations or in the code, it should be possible to parse them, and turn it into a list of (Token, text) Pygments tuples.

**Comment by melund** [comment]
This was fixed in https://github.com/scopatz/xonsh/pull/368  .
