### ISSUE TITLE
prompt-toolkit shell jumps around

### ISSUE THREAD

**Issue by rbrewer123** [scopatz/xonsh#362]
As first noticed by @melund in #339, the line you are typing on tends to jump around while using the prompt-toolkit shell.  This is due to the completion box popping up and down and changing size.  @melund mentions that ptpython reserves 5 lines at the bottom of the screen to prevent this issue, and he speculates there may be a prompt-toolkit setting to enable this.

**Comment by scopatz** [comment]
Should be a quick fix, if we can find it :)

**Comment by melund** [comment]
It turned out to be a prompt_toolkit issue, which was partly solved. It is still there in a different form: https://github.com/jonathanslenders/python-prompt-toolkit/issues/149

**Comment by scopatz** [comment]
I believe that this has been addressed in recent versions. Please feel free to reopen.
