### ISSUE TITLE
tab-completion launches executables

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#364]
I observed this error on windows. If I press tab to autocomplete an executable, then xonsh lauches it. 

[xonsh]~\Anaconda3\Scripts
$ spyder.e \<pres tab\>

That starts the exe file.

**Comment by adqm** [comment]
I have noticed a similar issue on GNU/Linux as well.  For me, it was with the following:

`git commit -m "always import local markdown" _markdown<tab>`

This called `import local` (subprocess mode, so taking a screenshot) and/or `import _markdown` (also subprocess mode), so I ended up with screenshots.

Not sure when this started happening, but I'm pretty sure it wasn't always this way.

**Comment by scopatz** [comment]
This seems bad :(

**Comment by Carreau** [comment]
+1, just experienced with `python3.<tab>`

**Comment by scopatz** [comment]
I think that this is happening because the '.' is getting tab-completed as attribute access, which triggers an evaluation.

**Comment by scopatz** [comment]
@melund et al., Thanks to @adqm can we now close this issue?

**Comment by denfromufa** [comment]
for me tab completion does not work on windows at all. it works like a tab instead.

**Comment by scopatz** [comment]
That sounds like a bug. Can you provide more information, @denfromufa about your setup.

**Comment by denfromufa** [comment]
@scopatz python 2.7.9 in root conda, then conda env. for python 3.4 (xonsh fails on pip, python 2.7, python 3.5). activated python 3.4 - launched xonsh, no luck with tab, although other features work.

```
$ pip list
pip (7.1.2)
ply (3.8)
prompt-toolkit (0.54)
Pygments (2.0.2)
setuptools (18.5)
six (1.10.0)
wcwidth (0.1.5)
wheel (0.26.0)
xonsh (0.2.3)


$ conda list
# packages in environment at C:\Python\Python27\envs\py34:
#
msvc_runtime              1.0.1                    vc10_0  [vc10]
pip                       7.1.2                    py34_0
ply                       3.8                       <pip>
prompt-toolkit            0.54                      <pip>
pygments                  2.0.2                     <pip>
python                    3.4.3                         5
setuptools                18.5                     py34_0
six                       1.10.0                    <pip>
wcwidth                   0.1.5                     <pip>
wheel                     0.26.0                   py34_1
xonsh                     0.2.3                     <pip>
```

**Comment by scopatz** [comment]
Hmm let's wait until we get a new release out in the next couple of days.

**Comment by denfromufa** [comment]
@scopatz ok, I installed curses and windows and now both bpython-curses and xonsh autocomplete work. the only problem is that 'Import' is capitalized when I call tab completion on it.

https://github.com/bpython/bpython/issues/509

**Comment by scopatz** [comment]
even if you do a from-import?

**Comment by denfromufa** [comment]
complete crap:

```
[py34] C:\Users\...>xonsh
 ~ # from sy
SyntaxError   SyntaxWarning SystemError   SystemExit
 ~ # from sys
SystemError SystemExit
 ~ # from sy
SyntaxError   SyntaxWarning SystemError   SystemExit
 ~ # from sys import p
PROP.OUT                  PsiData\                  pow
PendingDeprecationWarning PycharmProjects\          print
PermissionError           pass                      property
Pictures\                 pip\                      pushd
PrintHood\                pipwin\
ProcessLookupError        popd
 ~ # from sys import path
 ~ # impor
ImportError   ImportWarning import

```

**Comment by scopatz** [comment]
Oh, I see. In the last case you are actually getting three options (ImportWarning, ImportError, and import).  This is because you are in Windows which defaults to `$CASE_SENSITIVE_COMPLETIONS = False` as seen in http://xonsh.org/envvars.html.  You can set `$CASE_SENSITIVE_COMPLETIONS = True` at the command line or in the xonshrc to disable this.

**Comment by denfromufa** [comment]
@scopatz ok, this is great and fixed by problem, but can't xonsh distinguish between python and command-line case-sensitivity for autocompletion?

also this autocompletion does not work:

```
from sys import pat
```

only `import module_name` works.

**Comment by scopatz** [comment]
Ok, the release is out which should address the original issue. Feel free to close @melund and feel free to open up new issues @denfromufa

**Comment by ph-hs** [comment]
Any arriving here from Google search should also see https://github.com/xonsh/xonsh/issues/1198
