### ISSUE TITLE
history command not found

### ISSUE THREAD

**Issue by eldamir** [scopatz/xonsh#375]
I just tried a fresh install of Xonsh with python3.4.0 on ubuntu

```bash
virtualenv -p /usr/bin/python3 env
env/bin/pip install xonsh
env/bin/xonsh
```

Running `history` yields `xonsh: subprocess mode: command not found: history`. Havn't had a version where this worked. Tried both 0.1.3 and 0.1.6

**Comment by melund** [comment]
Hi Eldamir

The new advanced history feature is only in the development version. You can either install xonsh from source: 

```
git clone https://github.com/scopatz/xonsh.git
cd xonsh
python setup.py install
```

Or if you use the conda package manager then you can just do:
```
conda install -c melund xonsh
```
to install the newest development version from my channel. 

/Morten

**Comment by scopatz** [comment]
Yeah, we will try to get this out in a release version soon.

**Comment by eldamir** [comment]
Alright then. I just figured that it was in the production version, since it was mentioned on xonsh.org.

If you want to take some time before releasing the feature into production, you may want to drop a notice at the top of http://xonsh.org/tutorial_hist.html stating that it is still in development ;)
