### ISSUE TITLE
Tab completion for alias

### ISSUE THREAD

**Issue by rgaiacs** [scopatz/xonsh#391]
I use

~~~
alias g="git"
~~~

at my `~/.bashrc` and

~~~
[alias]
        ck = checkout
~~~

at my `~/.gitconfig`.

With `zsh`'s tab completion I have

~~~
$ g ck
HEAD    master
~~~

but with `xonsh`'s tab completion I have

~~~
$ g ck 
../  ./   bar
~~~

Could tab completion be add for alias?

**Comment by scopatz** [comment]
Yes, this should probably be something that is added.  I don't think that it would be super hard.  Pull requests welcome :)

**Comment by scopatz** [comment]
I think it is a great idea, btw.

**Comment by rgaiacs** [comment]
> I don't think that it would be super hard. Pull requests welcome :)

I will give a try but will need 3-4 weeks.

**Comment by scopatz** [comment]
That is fine, no huge rush from me :)

**Comment by gforsyth** [comment]
Closing this as it has been implemented.  Please reopen if there are issues remaining.
