### ISSUE TITLE
xonsh hangs on startup

### ISSUE THREAD

**Issue by asmeurer** [scopatz/xonsh#403]
This is starting xonsh 0.2.0 from bash. When I keyboard interrupt I get

```
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/xonsh", line 6, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/xonsh/main.py", line 71, in main
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/xonsh/shell.py", line 27, in __init__
    self._init_environ(ctx)
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/xonsh/shell.py", line 56, in _init_environ
    self.execer = Execer()
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/xonsh/execer.py", line 41, in __init__
    load_builtins(execer=self)
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/xonsh/built_ins.py", line 669, in load_builtins
    builtins.aliases.update(bash_aliases())
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/xonsh/aliases.py", line 126, in bash_aliases
    value = shlex.split(value)
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/shlex.py", line 276, in split
    return list(lex)
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/shlex.py", line 266, in __next__
    token = self.get_token()
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/shlex.py", line 93, in get_token
    raw = self.read_token()
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/shlex.py", line 224, in read_token
    self.token = self.token + nextchar
KeyboardInterrupt
```

How do I debug this?

**Comment by asmeurer** [comment]
I left it running and it eventually started with `/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/xonsh/aliases.py:129: RuntimeWarning: could not parse Bash alias "emacsclient": ValueError('No closing quotation',)
  RuntimeWarning)`. My emacsclient bash alias is 

```
$command -v emacsclient
alias emacsclient='emacsclient -a '\''emacs-server-start'\'' -nw --socket-name=ttys002'
```

**Comment by scopatz** [comment]
hmm the following seems to work in both python 3.4 and 3.5

```python
>>> import shlex
>>> shlex.split("emacsclient -a '\''emacs-server-start'\'' -nw --socket-name=ttys002")
['emacsclient', '-a', 'emacs-server-start', '-nw', '--socket-name=ttys002']
>>> 
```

**Comment by scopatz** [comment]
Also, that alias seems to work just fine on my machine.

**Comment by scopatz** [comment]
Can you try migrating that alias to xonshrc to see if that is what is causing the problem.

**Comment by asmeurer** [comment]
It is migrated to xonsh. Maybe that's part of the problem?

**Comment by asmeurer** [comment]
I think the alias might be a different issue. xonsh still takes forever to startup if I unalias `emacsclient`.

**Comment by scopatz** [comment]
What are the load times like if you pass in `--no-rc`, ie `xonsh --no-rc`? Let's try to narrow this down bit.

**Comment by asmeurer** [comment]
Looks like that is hanging.

**Comment by scopatz** [comment]
try commenting out line 568 (`ctx.update(bash_env())`) of environ.py

**Comment by scopatz** [comment]
(there really should be an env var for doing that....)

**Comment by asmeurer** [comment]
xonsh --no-rc still takes a long time to startup with that commented out (and still gives that warning).

**Comment by asmeurer** [comment]
It took 53 seconds to start.

**Comment by scopatz** [comment]
Wow, that is totally unacceptable. Any chance you could run a profiler or do a git bisect?

**Comment by asmeurer** [comment]
I let it run for 9 minutes with a profiler (pyinstrument) before keyboard interrupting it. It was stuck the whole time in the place shown by my original traceback.

**Comment by asmeurer** [comment]
I bisected it to e7c8537244dbade5b3be75014be1252ad036021c. I used `PYTHONPATH=. gtimeout 10 ~/anaconda/bin/xonsh --no-rc` to do the bisection. 

This makes sense because my default shell is a login shell (my bash configuration is all in ~/.profile). However, `time bash -l -c exit` takes 0.6 seconds inside of bash. 

If I set aside `~/.profile` it does indeed start immediately.

**Comment by asmeurer** [comment]
I see what it is doing now. This must be the reason for the runtime warning:

```
alias emacsclient='emacsclient -a '\''emacs-server-start'\'' -nw --socket-name=ttys000'
```

(from bash `alias`).

**Comment by asmeurer** [comment]
Ooh, this also explains why huge binary junk from `catimg` was being put in my xonsh environment (another thing that I noticed). My bash profile [prints stuff to the screen](https://github.com/asmeurer/dotfiles/blob/abcf987c0c3cc6501ec80ec5aef2b19b976b8d1a/.profile#L1-L4) and it is being parsed by xonsh when it parses `env` and `alias`.

**Comment by asmeurer** [comment]
Maybe there's a more direct way to achieve this, but perhaps xonsh should print some marker message before and after `env` and `alias` to ignore all the other output from .bash_profile/.profile/.bashrc.

**Comment by scopatz** [comment]
Thanks a ton for this!  I think it is now past time to do a complete overhaul of this part of the code base. I'll try to flesh it out in the next couple of days.

**Comment by auscompgeek** [comment]
What if we used `/bin/sh` (or just `sh`, either should work) for sourcing shell scripts, rather than `bash`? That should avoid running `.bashrc` altogether. Hopefully any shell script that people try to source that's simply for changing the environment should be POSIX compatible.

**Comment by scopatz** [comment]
#412 should address this.

**Comment by scopatz** [comment]
Ok @asmeurer and @auscompgeek - I have merged in the PR that should address this, please let me know if it works for you.

**Comment by scopatz** [comment]
And then close this issue :) Thanks.

**Comment by asmeurer** [comment]
Seems to fix it, even if I symlink my .profile to .bashrc.
