### ISSUE TITLE
Can't type literal tab with prompt_toolkit

### ISSUE THREAD

**Issue by blarghmatey** [scopatz/xonsh#408]
In bash or zsh I would typically type `Ctl-V TAB` to insert a literal tab, however, when using prompt_tookitas my shell type this simply tries to do tab completion and there doesn't seem to be a way to create a literal tab.

**Comment by blarghmatey** [comment]
I forgot to mention that I'm running Python 3.5.0 on Manjaro LInux
`Linux kommandcenter 3.19.8.7-1-MANJARO #1 SMP PREEMPT Fri Sep 25 18:20:07 UTC 2015 x86_64 GNU/Linux`

**Comment by scopatz** [comment]
With readline, you can type Shift+Tab to get a literal tab.  Not sure about prompt-toolkit, though it seems like there definitely should be a way to do this.
