### ISSUE TITLE
Autocompletion of a class method not always working

### ISSUE THREAD

**Issue by davidbrochart** [scopatz/xonsh#417]
Say I have this class:
```
class Test:
    def testTest(self):
        print('test')

test = Test()
```
Now when I enter `test.` and press Tab, I have a proposition for testTest, which is correct. But if I enter `test.testT` and press Tab, no proposition at all. I think the issue is with the capital letter.

**Comment by scopatz** [comment]
Thanks for reporting @davidbrochart. What version of xonsh are you on?

**Comment by scopatz** [comment]
I can confirm that this happens on v0.2.2

**Comment by scopatz** [comment]
As a temporary workaround, it seems to work fine with `$CASE_SENSITIVE_COMPLETIONS = False`

**Comment by davidbrochart** [comment]
Thanks for the workaround.

**Comment by scopatz** [comment]
Potential fix in #418

**Comment by davidbrochart** [comment]
I confirm #418 fixes the bug. Thanks a lot!

**Comment by scopatz** [comment]
Great! Thanks!  it has merged into master,
