### ISSUE TITLE
xonsh requires multiple exits after an error

### ISSUE THREAD

**Issue by masasin** [scopatz/xonsh#419]
Example:

    [myprompt]$ balloon
    xonsh: subprocess mode: command not found: balloon
    [myprompt]$ exit
    
    [myprompt]$ exit

*exits*

Every subsequent error increases the `exit` amount one needs to type.

**Comment by scopatz** [comment]
I can verify this issue. Thanks for reporting. Out of curiosity, do you have `$XONSH_STORE_STDOUT = True?

**Comment by masasin** [comment]
Yes, I do.

**Comment by scopatz** [comment]
Thanks @masasin - I think that this a stdout storage issue.

**Comment by scopatz** [comment]
I have a potential fix for this in #435 @masasin. If you could test out that PR I'd really appreciate it!

**Comment by masasin** [comment]
I'd love to. How do I do that? Just pip update? (First time contributing to something like this.)

**Comment by scopatz** [comment]
Ahh Ok  - do you use git at all?  If you do, you will want to clone this repo, checkout the multi-exit branch, and then reinstall locally. If you don't, you'll probably want to [download this zip file](https://github.com/scopatz/xonsh/archive/multi-exit.zip), unzip it, and reinstall locally.

You may also want to read up on how pull requests work. Here is GitHub's documentation: https://help.github.com/articles/using-pull-requests/  If you run into problems or find this confusing, let me know!

**Comment by masasin** [comment]
I do use git basically every day, but I've never done pull requests since everyone on the project has push access, or I am the only one working on something.

I'll follow your instructions and try it out.

**Comment by masasin** [comment]
It works. Thank you.
