### ISSUE TITLE
Sourcing virtualenvwrapper has no effect.

### ISSUE THREAD

**Issue by masasin** [scopatz/xonsh#420]
I use ROS and virtualenvwrapper, both of which need to be sourced from a sh file.

Here are the relevant parts of my `.xonshrc`

    # ROS
    source-bash /opt/ros/jade/setup.bash
    source-bash ~/catkin_ws/devel/setup.bash

    # Python Virtualenv
    $WORKON_HOME = "~/.virtualenvs"
    source-bash /usr/local/bin/virtualenvwrapper.sh
    $PIP_VIRTUALENV_BASE = "~/.virtualenvs"

Sourcing ROS allows me to use `roscore`, for instance. However, what is expected for virtualenvwrapper is that, upon opening a new shell, I would be able to use commands such as `workon` or `mkvirtualenv`. Instead, I get `xonsh: subprocess mode: command not found` for all those commands.

**Comment by scopatz** [comment]
Thanks for reporting, @masasin. Do the source-bash commands work when you type them into the interactive shell, rather than sticking them into the xonshrc? Just trying to figure out where the error is coming from

**Comment by masasin** [comment]
It does not. `$WORKON_HOME` and `$PIP_VIRTUALENV_BASE` register as normal, however.

**Comment by scopatz** [comment]
Ahh Ok. I have figured this out.  So `workon` and `mkvirtualenv` are not commands, they are shell functions. We don't have great support for running external shell functions yet, but this is a pretty good use case.

**Comment by scopatz** [comment]
@masasin - could you take a look at #420 please?  It is a needed step towards getting foreign function wrapping.

**Comment by scopatz** [comment]
Actually, now please try running #459. Thanks!
