### ISSUE TITLE
Git and Mercurial checks after every command

### ISSUE THREAD

**Issue by davidbrochart** [scopatz/xonsh#424]
I am on a remote file system that I access with SSHFS and it is particularly slow. I noticed that xonsh checks the current Git and Mercurial branch we are in after each command. In my case it takes like one second.
It would be nice to be able to disable the branch monitoring.

**Comment by scopatz** [comment]
Hi @davidbrochart, you should be able to remove these checks by removing the `{curr_branch}` portion of the `$PROMPT` environment variable. Let us know if this doesn't work for you, and please close this issue if it does.

**Comment by davidbrochart** [comment]
It worked. Thanks a lot!

**Comment by davidbrochart** [comment]
Actually that was not enough, I also had to remove the `{branch_color}` portion of the `$PROMPT` environment variable.

**Comment by scopatz** [comment]
Ahh yeah, I would expect that too.  Sorry.
