### ISSUE TITLE
can't find '__main__' module in 'xonsh'

### ISSUE THREAD

**Issue by el3ctron** [scopatz/xonsh#426]
when i execute xonsh on bash, answer is:

Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 2, in <module>
    from xonsh.main import main
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 11, in <module>
    from xonsh.shell import Shell
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 5, in <module>
    from xonsh.execer import Execer
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 10, in <module>
    from xonsh.parser import Parser
  File "/usr/local/lib/python3.4/dist-packages/xonsh/parser.py", line 6, in <module>
    from ply import yacc
ImportError: No module named 'ply'

Then, i try this command:
/usr/bin/python3.4 xonsh

and the answer is:

/usr/bin/python3.4: can't find '__main__' module in 'xonsh'

**Comment by scopatz** [comment]
Hi @el3ctron you need to install ply before installing xonsh. Let us know if this fixes the issue.

**Comment by el3ctron** [comment]
i do a
sudo pip install ply

machine respond:

Requirement already satisfied (use --upgrade to upgrade): ply in /usr/local/lib/python2.7/dist-packages

i repeat the commands to start xonsh but it give me the same output, then i link ply libraries like this:

sudo ln -s /usr/local/lib/python2.7/dist-packages/ply* /usr/local/lib/python3.4/dist-packages/

now machine responds:

/usr/bin/python3.4: can't open file 'xonsh': [Errno 2] No such file or directory

**Comment by scopatz** [comment]
Hmm I don't think that you can just soft-link a Python 2 package into a Python 3 installation directory. I believe the write way to do this is to switch to using the Python 3 version of pip, rather than your system's Python 2 version.

**Comment by el3ctron** [comment]
excelent!!

command was sudo pip3 install ply

now i have a new shell that i want to probe. Nice project! 

thanks

**Comment by scopatz** [comment]
Whoohoo! Thanks @el3ctron
