### ISSUE TITLE
Short circuiting operators (&& and ||)

### ISSUE THREAD

**Issue by masasin** [scopatz/xonsh#434]
I cannot seem to be able to run them.

**Comment by scopatz** [comment]
From yesterday, in #431:

> This is a duplicate of #137. Furthermore, as discussed there, I believe that and, or, and not are better choices, though I am open to a compatibility layer using &&. #253 is a partial implementation that could use some love and support. This is low on my personal priority list, and so it is more than fair game to implement. Pull requests very welcome.
