### ISSUE TITLE
Entering a directory name should cd to that directory

### ISSUE THREAD

**Issue by kseistrup** [scopatz/xonsh#439]
Amiga's `WShell` had a sweet future that I haven't seen implemented in any of the shells I've encountered on POSIX systems: entering a directory name would cd to that directory.

E.g.,
```sh
kseistrup@home ~ $ /usr/bin
kseistrup@home /usr/bin $ 
```
It would be a nice feature to have in `xonsh`.

**Comment by scopatz** [comment]
Cool idea! Pull requests welcome, especially if it is optional.

**Comment by mdraw** [comment]
This behavior is built into the fish shell.
The function in fish that checks if an entered string can be interpreted as an implicit cd can be found here: https://github.com/fish-shell/fish-shell/blob/master/src/path.cpp#L225
Maybe this will help implementing it in xonsh.

**Comment by scopatz** [comment]
Thanks @mdraw, this looks like it checks specific directory prefixes and suffixes. It would probably be easier  to check if `len(args) == 1 and os.path.isdir(args[0]) and not on_path(args[0])`.  The last part is psuedo-code for now, but I think we already have a functions somewhere that does that.

**Comment by mdraw** [comment]
Yes,

    len(args) == 1 and os.path.isdir(os.path.expanduser args[0]))
should do the trick for any possible path if I am not missing something.
Fish's implementation is probably only more complex because it doesn't have access to the awesome Python standard library :)

**Comment by mdraw** [comment]
What do you mean by `on_path(args[0])`, @scopatz?

**Comment by auscompgeek** [comment]
I'll also note that this is also builtin toggleable behaviour in zsh (the autocd option).

**Comment by kseistrup** [comment]
It seems I have been very superficial when trying out other shells than `bash`… :wink:

**Comment by scopatz** [comment]
> What do you mean by on_path(args[0]), @scopatz?

Whether there is a program in `args[0]` that lives in one of the directories of the `$PATH` variable.

**Comment by gforsyth** [comment]
@kseistrup this should be working now (see #463).  You can set `$AUTO_CD=True` in your `xonshrc` and it should work

**Comment by auscompgeek** [comment]
Can we close this issue now?

**Comment by kseistrup** [comment]
I have problems building the `xonsh-git` package on Arch because of Jupyter requirements (which is already installed, so I don't quite understand why it attempts to install it again…).  I'll look into it as soon as I've had some breakfast.

**Comment by kseistrup** [comment]
Just for the record:

It seems that `shopt -s autocd`” in `bash` v4+ enables just that feature. :smile:
