### ISSUE TITLE
Line wrap covers up prompt

### ISSUE THREAD

**Issue by wrywerytwreywery** [scopatz/xonsh#44]
I haven't yet figured out exactly when/why this happens, but sometimes the input line wraps around to cover the prompt, rather than wrapping onto a different line.  Even when making the terminal much larger, the input seems to want to wrap around the original size of ther terminal or something like that, rather than wrapping at the current size.

![xonsh_wraparound](https://cloud.githubusercontent.com/assets/549404/6657203/7f93ef9a-cb1a-11e4-9b68-d4b4c1f26dda.png)

![xonsh_wraparound2](https://cloud.githubusercontent.com/assets/549404/6657204/a4b8974e-cb1a-11e4-86ee-a7031dd057cf.png)

**Comment by scopatz** [comment]
I can't reproduce this locally, but I bet this comes from readline not computing the size of the line properly.  This might be because the title line is not being ignored. I am going to put in a potential fix in a few min.

**Comment by scopatz** [comment]
What terminal are you using? I have tried this in both xterm and gnome-terminal... My potential fix caused other problems.

**Comment by scopatz** [comment]
Just tried with rxvt and rxvt-unicode and can't trigger this.

**Comment by scopatz** [comment]
For reference the fix was to change the settitle() line to the following:

```python
sys.stdout.write("\001\x1b]2;{0}\x07\002".format(t))
```

Maybe you could try this out and see if it works for you.

**Comment by wrywerytwreywery** [comment]
I am not sure whether there are other ways to trigger this, but I have been able to reproduce consistently by doing the following:

* Open new terminal (small, e.g., 80*24)
* Type enough characters to force wrap
* Before hitting return, resize window to be larger
* Hit Return
* Type enough characters to wrap the old terminal's size

I will try your fix in a few.

**Comment by wrywerytwreywery** [comment]
Changing `settitle` as above didn't seem to fix, nor does removing the call to `settitle`.  

It does seem like a readline issue, since once it is in this failure mode, a whole bunch of readline-ish things (up arrow, for example) break down.  Worse, these errors seem to persist when opening a new terminal window.

Not sure when I'll have a chance, but I will try to poke around and gather some more info.  I don't remember it breaking in this way yesterday; not sure whether that was just luck, or whether something we changed yesterday dit this, or whether it's something specific to my machine.

**Comment by scopatz** [comment]
Well we did revert back to using the `PROMPT` variable from `XONSH_PROMPT`...

**Comment by icarito** [comment]
I can confirm that I can trigger the failure with @wrywerytwreywery 's procedure.

I'm running Manjaro (ArchLinux based OS), using Terminator terminal.

**Comment by wrywerytwreywery** [comment]
I'm going to back up through the history to see if this issue started showing up after a particular changeset yesterday...

**Comment by wrywerytwreywery** [comment]
I rolled back as far as c836c7eb786100e859e8df8bd1d188e420ab6934 and still saw this issue, so I don't think it is something we did yesterday.

Poking around a bit, it almost seems like `cmd` might want to wrap around the width of the terminal _when the program was started_ rather than on its current width.  If I start xonsh in a big window, then I can resize with impunity (make the window smaller, then bigger again, no problem, and the wrapping seems to change itself as the window's size changes), but if I start it in a small window and then try to make it bigger, that doesn't work.

**Comment by scopatz** [comment]
I wonder, does this issue show up if you run a basic Cmd() loop:

```console
$ python -c 'from cmd import Cmd; Cmd().cmdloop()'
```

Also, add terminator to the list of terminals that I am not able to reproduce this on.

**Comment by wrywerytwreywery** [comment]
Yep, still broken for me in the same way on the basic Cmd loop...

**Comment by scopatz** [comment]
Ok great! this is definitely a readline issue. I'll try to come up with a hacky work around.  Out of curiosity, where did you get Python from (your distro, conda, etc.), @wrywerytwreywery and @icarito?

**Comment by wrywerytwreywery** [comment]
Right now I'm running Python 3.4.0 from `apt` on Ubuntu 14.04.

I can try in a bit building 3.4.3 and seeing whether it could be as simple as that...

**Comment by scopatz** [comment]
Ok.  For reference, I am on Ubuntu 14.10 using conda's Python 3.4.3

**Comment by wrywerytwreywery** [comment]
No luck after compiling 3.4.3.
My version of `libreadline-dev` is 6.3-4ubuntu2

**Comment by icarito** [comment]
Here is the full info for my python3 version, installed from
distribution packages, originally from Archlinux. BTW I remember having
a similar problem like a year ago with bash, so it may be tricky.

    icarito@aiki ~ $ python
    Python 3.4.3 (default, Feb 26 2015, 16:19:21)
    [GCC 4.9.2 20150204 (prerelease)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>>
    icarito@aiki ~ $ pacman -Qi python
    Name           : python
    Version        : 3.4.3-1
    Description    : Next generation of the python high-level scripting
    language
    Architecture   : i686
    URL            : http://www.python.org/
    Licenses       : custom
    Groups         : None
    Provides       : python3
    Depends On     : expat  bzip2  gdbm  openssl  libffi  zlib
    Optional Deps  : python-setuptools [installed]
                     python-pip [installed]
                     sqlite [installed]
                     mpdecimal: for decimal
                     xz: for lzma [installed]
                     tk: for tkinter [installed]
    Required By    : blender  cython  hplip  libreoffice-still 
    media-player-info
                     menulibre  mono  namcap  novacut  opencolorio
                     pacman-mirrorlist  pastebinit  pep8  py3parted  pyalpm
                     pyskein  python-argparse  python-cairo  python-dbus
                     python-decorator  python-docopt  python-docutils
                     python-fusepy-git  python-gobject  python-gobject2
                     python-markdown  python-markups  python-markupsafe
                     python-mccabe  python-microfiber  python-numpy 
    python-pillow
                     python-pip  python-psutil  python-pycups  python-pycurl
                     python-pyelftools  python-pygame-hg  python-pyglet
                     python-pyqt5  python-pyside  python-requests
                     python-setuptools  python-shiboken  python-simplejson
                     python-sip  python-six  python-tornado  python-tqdm
                     python-userwebkit  python-virtualenv  python-xdg 
    python-yaml
                     python3-xlib  shiboken  usbformatter  waf  youtube-dl
    Optional For   : boost  hexchat  libnewt  lirc  systemd  util-linux
    Conflicts With : None
    Replaces       : python3
    Installed Size :  85.99 MiB
    Packager       : Felix Yan <felixonmars@archlinux.org>
    Build Date     : Thu Feb 26 11:43:06 2015
    Install Date   : Sat Mar 14 19:34:47 2015
    Install Reason : Installed as a dependency for another package
    Install Script : No
    Validated By   : Signature

**Comment by scopatz** [comment]
I have added some diagnostic information to the shell that should print out on startup on the `wrap` branch.  Could you try it out and tell me what it says? Thanks!

**Comment by wrywerytwreywery** [comment]
Here are mine:
RL_CATCH_SIGNALS: 1
RL_CATCH_SIGWINCH: 1
RL_CHANGE_ENVIRONMENT: 1

**Comment by scopatz** [comment]
OK I have two ideas, then.  I have pushed the first one up to wrap.  Can you try reproducing this issue?  Sorry for all the back and forth. I wish I could reproduce this.

**Comment by scopatz** [comment]
Also, does this happen on all prompts? Or just the first one?

**Comment by wrywerytwreywery** [comment]
No luck on that one.  And no worries on the back-and-forth; I'd be happy to help try and implement a fix if I knew anything about cmd and/or readline.

Once it happens once, it seems to happen for all subsequent prompt as well (even after increasing the window size again).

**Comment by scopatz** [comment]
Ok, try it now please.

**Comment by scopatz** [comment]
And thanks for understanding.

**Comment by wrywerytwreywery** [comment]
Still the same problem, unfortunately.

**Comment by scopatz** [comment]
How about now?

**Comment by wrywerytwreywery** [comment]
Okay, this is getting closer now (and I see what you are doing in the code).  And in some sense, it seems to work (the width of the wrapped text seems to change).

It does, though, have a mysterious side-effect, which I can't really explain in words.  After running a command (or sending a keyboard interrupt), a second prompt appears (despite the `PROMPT` variable not being changed).  In fact, it's not just a duplicate, but rather, it's something like cascaded xonsh-es.  For example, changing a directory changes the second prompt, then running another command causes the first prompt to reflect that change...

![cascaded_xonshes](https://cloud.githubusercontent.com/assets/549404/6659914/74f05772-cb65-11e4-96cc-a7d32649c8a0.png)


I am going to have to call it a night, but I may be able to play with this some tomorrow (either testing or playing with it myself, now that I have an idea of where to look).

**Comment by scopatz** [comment]
Hahah! This happens to me too.  I will try to figure out how to suppress it.  Also note that I have been looking at [this section of the readline docs](http://cnswww.cns.cwru.edu/php/chet/readline/readline.html#SEC44) and then using ctypes to call the functions or set the variables.

Have a good rest of your night @wrywerytwreywery!

**Comment by scopatz** [comment]
It seems that `lib.rl_resize_terminal()` is what is causing the doubling. I have commented these out in the latest version.  If you play around with it tomorrow and let me know what works, that'd be great!

**Comment by wrywerytwreywery** [comment]
Commenting out those lines seems to have fixed it.  Thanks!

**Comment by scopatz** [comment]
Great! Now figure out the minimal number of times we need this.  I have pushed some code up to `wrap` that only resizes once.  Can try this out and let me know how it goes?  Try to resize after a couple of lines of input too. Thanks!

**Comment by scopatz** [comment]
OK, a fix for this is now available on 8a5dad4.  Please close once confirmed.

**Comment by wrywerytwreywery** [comment]
Working fine on the machine I am using now, but this is not the one that was having issues before.  I will try that other machine tomorrow, and will close this if everything seems alright there.  Thanks for all the work you put in on this!

**Comment by wrywerytwreywery** [comment]
Looks good; closing.  Thanks!
