### ISSUE TITLE
Add 'edit and execute command` function

### ISSUE THREAD

**Issue by gforsyth** [scopatz/xonsh#445]
bash and zsh (and I'm sure others) have an edit and execute command that is invoked with Ctrl-e + Ctrl-x which opens the current contents of the command prompt in the system editor.  Edits made to the command are then run on save and quit.  

It could be this functionality is already baked in and I'm missing it?  In any case, it's especially handy for longer commands -- and given xonsh's multi-line input capabilities this seems like a good fit.

Thoughts?

**Comment by scopatz** [comment]
This is not currently present, but it sounds like a reasonable idea.

**Comment by gforsyth** [comment]
This _should_ be trivial to implement in the `prompt_toolkit` shell, at least, because there's an `enable_open_in_editor` kwarg when setting up the prompt.  But when I enable it, I'm still not able to get the xonsh prompt to respond to the C-X C-E command.  

@jonathanslenders do you have any idea why xonsh might prevent this from working?

**Comment by jonathanslenders** [comment]
The following patch works for me:
```diff
diff --git a/xonsh/prompt_toolkit_shell.py b/xonsh/prompt_toolkit_shell.py
index 9d2ee23..0cd88cc 100644
--- a/xonsh/prompt_toolkit_shell.py
+++ b/xonsh/prompt_toolkit_shell.py
@@ -48,6 +48,7 @@ class PromptToolkitShell(BaseShell):
         self.pt_completer = PromptToolkitCompleter(self.completer, self.ctx)
         self.key_bindings_manager = KeyBindingManager(
             enable_auto_suggest_bindings=True,
+            enable_open_in_editor=True,
             enable_search=True, enable_abort_and_exit_bindings=True)
         load_xonsh_bindings(self.key_bindings_manager)
 ```
Normally, C-X C-E should work after that.

**Comment by gforsyth** [comment]
Awesome.  Thanks!  I was sticking it in the call to `prompt()` and not getting much traction.  The phrase "KeyBindingManager" probably should've been a clue.
