### ISSUE TITLE
doesn't install properly on Windows

### ISSUE THREAD

**Issue by lewisl** [scopatz/xonsh#457]
Instead of getting xonsh.bat in the scripts directory, you get xonsh--which is appropriate for 'nix.

I manually created a suitable script.

When you run python -m xonsh.main, xonsh comes up, but with characters that are unprintable in the windows console.  You can then change the $PROMPT environment variable and get something clean.  From the documentation it is not clear where the .xonshrc file should be placed as the documentation addresses 'nix style systems.

Guess this isn't targeted to Windows.

**Comment by lewisl** [comment]
.xonshrc in the user's root works as it does on 'nix.  Could improve the windows doc page.  Seems out of date.

**Comment by scopatz** [comment]
Thanks for reporting @lewisl. I know that there are folks out there who use xonsh on windows daily.  I will happily take any PRs that make the user experience better.  Sorry that you are running in to so many issues....

**Comment by scopatz** [comment]
It seems that the install issues have been addressed by #464.  If that was the main purpose of this issue, please close this @lewisl. Thanks!

**Comment by krader1961** [comment]
PR #468 should address this issue in an even more robust solution than #464 did; at least if you use Anaconda for your installs (which I highly recommend).

**Comment by scopatz** [comment]
closing due to age.
