### ISSUE TITLE
xonsh.bat shouldn't be installed on non-Windows platforms

### ISSUE THREAD

**Issue by auscompgeek** [scopatz/xonsh#466]

**Comment by scopatz** [comment]
This was done as a convenience for conda convert to be able to generate windows packages on Linux and to hot fix people not being able to use xonsh on windows. A pull request fixing this would be very welcome. I completely agree.

**Comment by krader1961** [comment]
@auscompgeek Please add a "Resolves #466" line to the description. Also, I'm a bit confused by the problem statement since I don't see a xonsh.bat script in my Anaconda tree (it is, of course, in my git repository). Having said that I agree that your proposed change is preferable to handcrafted scripts for invoking xonsh.

**Comment by auscompgeek** [comment]
@krader1961 This *is* #466. It doesn't make sense for an issue to reference itself.

**Comment by krader1961** [comment]
@auscompgeek you're correct. I intended to ask @uranusjr to add that line in his PR #468. The close proximity of the IDs resulted in my getting confused as I bounced between browser pages.

**Comment by auscompgeek** [comment]
1. Make sure you have the latest `HEAD` checked out.
2. `pip install -e .`
3. Look in your `/usr/local/bin` to find a `xonsh.bat`.

I use `pip install --user` and `~/.local/bin`, but the issue is the same, nevertheless.

**Comment by selepo** [comment]
Tried to issue a fix for this with this PR.
The only way I know to handle this is to check for platform in setup.py. 

https://github.com/scopatz/xonsh/pull/510

**Comment by auscompgeek** [comment]
IMO, this was already fixed in #468. I've yet to come across anyone that doesn't have setuptools installed. Closing.

**Comment by scopatz** [comment]
I personally try to avoid setuptools if I can :)
