### ISSUE TITLE
Multiline Code does not Auto Indent in Windows

### ISSUE THREAD

**Issue by degustaf** [scopatz/xonsh#467]
When attempting to type the following as in the tutorial
if True:
    print(1)
else:
    print(2)

The shell defaulted to 
if True:
print(1)
else:
print(2)

**Comment by scopatz** [comment]
Thanks for reporting. Can you give us more detail about what kind of shell you are using (readline or prompt toolkit) and what terminal emulator you are using? Thanks

**Comment by degustaf** [comment]
I am using prompt-toolkit (Documentation says that this is required for Windows.  Is that not true?)  I am not using a terminal emulator.  I am running it within the windows command prompt (cmd.exe)

**Comment by scopatz** [comment]
This might be a cmd.exe issue.  Maybe @BYK or another windows user knows more....

**Comment by henryiii** [comment]
I'm not seeing an auto-indent with `prompt-toolkit` on Mac, either. I do see it with `readline`. Latest and master.

**Comment by scopatz** [comment]
This might be a prompt-toolkit issue then. You could try reportinf it there.

**Comment by BYK** [comment]
Yeah, same here with Python 3.4 and prompt-toolkit. prompt-toolkit started to act strangely after I upgraded it so it may be related. Defnitely not a `cmd.exe` issue though. I use python directly in ConEmu.

**Comment by gforsyth** [comment]
Does anyone have multiline indenting working with prompt_toolkit?  I know that PT supports multiline inputs, but xonsh doesn't use it -- and there is the `postcmd` routine in the `readline_shell` to take care of the indents.  Maybe this just hasn't been implemented in the PT shell?

**Comment by henryiii** [comment]
I was looking at the code and came to the same conclusion. It would be very nice if it if it supported the multi line system. It would be especially nice if it allowed backspaces past lines. :)

**Comment by scopatz** [comment]
Much agreed.

**Comment by gforsyth** [comment]
I believe this has been rectified in #601 -- please reopen if you feel otherwise.
