### ISSUE TITLE
~, completion and expandsuser issues

### ISSUE THREAD

**Issue by Carreau** [scopatz/xonsh#469]
I suppose that some kind of os.path.expanduser migh be needed somewhere as `cp '~/source' target` will not work, though `cp ~/s<tab>` will complete to `cp '~/source' `. Which is confusing. 

```
(root) ~ $ cd dev/tpllib/
(root) ~/dev/tpllib $ cp '~/Advance python-Copy1.ipynb' ./
cp: ~/Advance python-Copy1.ipynb: No such file or directory
(root) ~/dev/tpllib $ cp @(os.path.expanduser('~/Advance python-Copy1.ipynb')) ./
(root) ~/dev/tpllib $ cd
(root) ~ $ cp 'Advance python-Copy1.ipynb' dev/tpllib/
(root) ~ $
```

![homeexpansion](https://cloud.githubusercontent.com/assets/335567/10953716/5edeef10-82fe-11e5-9823-c93220386caa.gif)

**Comment by scopatz** [comment]
Thanks for reporting. I don't think that we are calling expand user on string args in subproc mode, which you need because of the space in the filename. The interface could use improvement, either by allowing backslash escapes or by calling expand user on all arguments always.

**Comment by scopatz** [comment]
If they start with a tilde

**Comment by scopatz** [comment]
Also we probably don't expandvars where we need to either.

**Comment by Carreau** [comment]
Yeah, I also expect expanduser to break with user complaining "cannot create filename named `~`" if we fix this one :-P

**Comment by scopatz** [comment]
The `xonsh.built_ins.expand_path()` function seems to do what we need. It just needs to be put in the right place.

**Comment by scopatz** [comment]
And anyone who really wants to create a file named "~" will have to learn to love absolute paths :)

**Comment by scopatz** [comment]
Hmmm I wonder why [this line](https://github.com/scopatz/xonsh/blob/master/xonsh/parser.py#L2410) isn't being hit.

**Comment by scopatz** [comment]
Ohhh Probably becase `p0.s` is a nested string (`"'~/hello'"`) not just `'~/hello'`
