### ISSUE TITLE
"history show" slice notation should allow negative subscripts

### ISSUE THREAD

**Issue by krader1961** [scopatz/xonsh#471]
You can show the n'th most recent command. For example:

    history show -5

But you can't show the n most recent commands. For example:

    history show -5:-1

or just

    history show -5:

produces this error:

**history: error: unrecognized arguments: -5:-1**

By default when I'm showing the history I typically want just the most recent 20 commands shown. Yes, I can write a function that uses `len(__xonsh_history__)` and some math to construct positive slice indexes but that shouldn't be necessary.

**Comment by scopatz** [comment]
Thanks for reporting @krader1961 - I thought that this worked already, but I guess not.

**Comment by scopatz** [comment]
Ahh Ok.  This is because argparse is interpreting this as an option.

**Comment by scopatz** [comment]
This is actually a bug in argparse. Trying to figure out a workaround.

**Comment by scopatz** [comment]
Closed by #476
