### ISSUE TITLE
commit e78564b1689338a783e137ae6085934d21d343d2 broke tests/test_replay.py

### ISSUE THREAD

**Issue by krader1961** [scopatz/xonsh#479]
While working on a change to make the history code lint clean I ran all the unit tests and was surprised to find that nosetests hung. Long story short: The problem is that commit e78564b1689338a783e137ae6085934d21d343d2 interacts badly with my ~/.xonshrc file that contains a `source` command. If I revert that change or remove the `source` command from my ~/.xonshrc  the replay unit test runs to completion.

My first observation is that unit tests must be hermetic. They should never, ever, be affected by things like an individuals .xonshrc config file. At my day job this isn't an issue because unit tests never run on someones workstation (they always run "in the cloud" on a server with a borg standard config). Achieving a similar result in the context of a project like xonsh almost certainly will require a wrapper around nosetests that sets environment variables and/or run-time options to ensure that the local configs do not affect the test. For example, running the test via

XONSHRC=/dev/null nosetests -v tests/test_replay.py

runs to completion and passes. My recommendation is a Makefile that contains a "test" target that does what is needed so a developer can simply type "make test". Similarly for "make lint".

**Comment by krader1961** [comment]
So people don't have to figure out how to display the relevant part of the change which caused the problem on my worstation it is this:

```
diff --git a/xonsh/shell.py b/xonsh/shell.py
index 152d336..71a4f3e 100644
--- a/xonsh/shell.py
+++ b/xonsh/shell.py
@@ -59,7 +59,7 @@ class Shell(object):
         if ctx is not None:
             self.ctx = ctx
         else:
-            rc = env.get('XONSHRC', None)
+            rc = env.get('XONSHRC')
             self.ctx = xonshrc_context(rcfile=rc, execer=self.execer)
         builtins.__xonsh_ctx__ = self.ctx
         self.ctx['__name__'] = '__main__'
```

**Comment by scopatz** [comment]
Hi @krader1961 - thanks for bringing this up.  There are probably a bunch of places where the test (accidentally or on purpose) call into the user's environment. @asmeurer brought this up in #430 and there are other places as well.  The long of the short of it is that this should be fixed to be "hermetic" as you say.  I really welcome any changes made in this direction.  

I think the hermeticity of the test suite is independent of the interface.  If you want to add a simple makefile (in the tests dir) that calls out to nose, that would be fine. But I think all of the tests should be nose compliant, and hopefully eventually also py.test compliant as well.

**Comment by krader1961** [comment]
Closing as a dup of issue #430 (into which I pasted the info above).
