### ISSUE TITLE
implement dirstack

### ISSUE THREAD

**Issue by TheJJ** [scopatz/xonsh#48]
`cd -` and `cd -%d` would be awesome.

This allows switching to some previous directory.

**Comment by scopatz** [comment]
I'd happily accept a PR that implemented this kind of feature :)

**Comment by wrywerytwreywery** [comment]
I'm happy to work on this unless somebody else wants dibs.

**Comment by mbollmann** [comment]
I think it would be great if this functioned as a proper stack similar to `pushd` and `popd` by default. I have functions in my .bashrc that basically replace `cd` with `pushd` and provide functionality to view the full dirstack and easily travel to a specific dir in the stack. Just a suggestion.

**Comment by TheJJ** [comment]
jup, the like the zsh cd feature completes the - with the last n directories visited, so e.g. typing `cd -3` visits the third-last one. `cd -<tab>` shows the whole stack and completes the number.

**Comment by mbollmann** [comment]
That sounds even better than my bash aliases. I'm not familiar with zsh, but this behaviour sounds great.

I won't have the time to implement this before the weekend though, so go ahead @wrywerytwreywery if you like. :)

**Comment by scopatz** [comment]
@TheJJ - #116 has been merged.  Does this satisfy the issue here?

**Comment by TheJJ** [comment]
Nice! `cd -` works now, but `cd -$number` is still missing :wink:
Completion for the number with display of the associated stack value would be ideal.

**Comment by scopatz** [comment]
I think that you can do `cd -number`.

**Comment by TheJJ** [comment]
```
cd -2
cd: no such file or directory: -2
```

**Comment by scopatz** [comment]
Ahh, seems like there might be a bug.  @wrywerytwreywery?

**Comment by wrywerytwreywery** [comment]
`pushd`, `popd`, and `dirs` have been implemented, but `cd -n` hasn't been implemented yet, nor has `$AUTO_PUSHD`.  Those are on my queue.

**Comment by scopatz** [comment]
I believe that this is now implemented.  Please re-open if I am in error
