### ISSUE TITLE
Multi-line statements in Windows

### ISSUE THREAD

**Issue by johndcook** [scopatz/xonsh#486]
Multi-line statements fail on Windows. For example, if I type `if True:` then I get an error message as soon as I hit Return. The same holds for `if`, `for`, or `def` statements.

I've seen this launching xonsh from cmd.exe and from PowerShell, on Windows 8.1 and on Windows 10. Running the latest released version at the time of writing, 0.2.3.

$ if True:
pre_input_hook failed
Readline internal error
Traceback (most recent call last):
  File "C:\bin\Anaconda3\lib\site-packages\pyreadline\modes\basemode.py", line 124, in readline_setup
    self.pre_input_hook()
  File "C:\bin\Anaconda3\lib\site-packages\xonsh\readline_shell.py", line 81, in inserter
    readline.redisplay()
AttributeError: 'module' object has no attribute 'redisplay'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bin\Anaconda3\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "C:\bin\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 569, in readline
    self.readline_setup(prompt)
  File "C:\bin\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 564, in readline_setup
    BaseReadline.readline_setup(self, prompt)
  File "C:\bin\Anaconda3\lib\site-packages\pyreadline\rlmain.py", line 253, in readline_setup
    return self.mode.readline_setup(prompt)
  File "C:\bin\Anaconda3\lib\site-packages\pyreadline\modes\basemode.py", line 127, in readline_setup
    traceback.print_exc()
NameError: name 'traceback' is not defined
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<string>", line None
SyntaxError: None: no further code

**Comment by gforsyth** [comment]
Hi @johndcook , you might try using prompt_toolkit instead of pyreadline as it's better supported in windows.

**Comment by tritemio** [comment]
Same error here on Windows 7. How do you switch to prompt_tookit?

**Comment by krader1961** [comment]
On Mon, Nov 9, 2015 at 4:25 PM, Antonino Ingargiola <
notifications@github.com> wrote:

> Same error here on Windows 7. How do you switch to prompt_tookit?
>
Simply install the package using "conda install prompt-toolkit". Xonsh will
use it if present in preference to readline.

-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by krader1961** [comment]
On Mon, Nov 9, 2015 at 5:18 PM, Kurtis Rader <krader@skepticism.us> wrote:

> On Mon, Nov 9, 2015 at 4:25 PM, Antonino Ingargiola <
> notifications@github.com> wrote:
>
>> Same error here on Windows 7. How do you switch to prompt_tookit?
>>
> Simply install the package using "conda install prompt-toolkit". Xonsh
> will use it if present in preference to readline.
>

Oops! That isn't true. You not only have to, obviously, have prompt-toolkit
installed you also have to tell xonsh to use it via the SHELL_TYPE
environment var or --shell-type=prompt_toolkit CLI flag.

-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by tritemio** [comment]
Ok, `--shell-type=prompt_toolkit` works. But the color scheme is not very legible:

![screenshot](https://cloud.githubusercontent.com/assets/4156237/11051789/ed2df7d2-8706-11e5-91fc-baed4d565744.png)

Is there a way to use the readline color scheme?

**Comment by johndcook** [comment]
I installed prompt_toolkit 0.47. When I type

$ xonsh --shell-type prompt_toolkit

I get the following error:

Traceback (most recent call last):
  File "C:\bin\Anaconda3\Scripts\xonsh-script.py", line 6, in <module>
    sys.exit(main())
  File "C:\bin\Anaconda3\lib\site-packages\xonsh\main.py", line 83, in main
    args = premain(argv)
  File "C:\bin\Anaconda3\lib\site-packages\xonsh\main.py", line 72, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "C:\bin\Anaconda3\lib\site-packages\xonsh\shell.py", line 41, in __init__
    ctx=self.ctx, **kwargs)
  File "C:\bin\Anaconda3\lib\site-packages\xonsh\prompt_toolkit_shell.py", line 51, in __init__
    enable_search=True, enable_abort_and_exit_bindings=True)
TypeError: __init__() got an unexpected keyword argument 'enable_abort_and_exit_bindings'

When I set the environment variable SHELL_TYPE to prompt_toolkit I get the same error when I start xonsh.

**Comment by krader1961** [comment]
On Mon, Nov 9, 2015 at 6:49 PM, John Cook <notifications@github.com> wrote:

> I installed prompt_toolkit 0.47. When I type
>

That is quite old. On my system prompt-toolkit is version 0.54. and the
KeyBindingManager class in that version has a  enable_abort_and_exit_bindings
keyword arg. If you update your prompt-toolkit software to something more
recent I'm confident your problem will be resolved.

I'm curious why you're using an ancient version of prompt_toolkit. The most
likely reason is you are working in an environment that requires manual
upgrades and you simply haven't done an update in a long time. I found
myself having similar problems so I wrote a "swupdate" script which
automates the process of updating Homebrew and Anaconda software on my Mac
OS X and Linux servers.

> $ xonsh --shell-type prompt_toolkit
>
> I get the following error:
>
> Traceback (most recent call last):
> File "C:\bin\Anaconda3\Scripts\xonsh-script.py", line 6, in
> sys.exit(main())
> File "C:\bin\Anaconda3\lib\site-packages\xonsh\main.py", line 83, in main
> args = premain(argv)
> File "C:\bin\Anaconda3\lib\site-packages\xonsh\main.py", line 72, in
> premain
> shell = builtins.*xonsh_shell* = Shell(*
>
> *shell_kwargs) File "C:\bin\Anaconda3\lib\site-packages\xonsh\shell.py",
> line 41, in init ctx=self.ctx, **kwargs)
> File "C:\bin\Anaconda3\lib\site-packages\xonsh\prompt_toolkit_shell.py",
> line 51, in *init*
> enable_search=True, enable_abort_and_exit_bindings=True)
> TypeError: *init*() got an unexpected keyword argument
> 'enable_abort_and_exit_bindings'
>
> When I set the environment variable SHELL_TYPE to prompt_toolkit I get the
> same error when I start xonsh.
>

-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by johndcook** [comment]
I installed the most recent version of prompt_toolkit that I could via conda.

prompt_toolkit is not part of the main conda repository, so you cannot simply run `conda install prompt_toolkit` as suggested above. When I searched anaconda.org for the package, it listed the most recent version as that owned by prkrekel, version 0.52. However, conda would not install this version, saying that it conflicts with python 3.4*. So I tried the next most recent version available for Windows on anaconda.org.

**Comment by krader1961** [comment]
On Tue, Nov 10, 2015 at 4:18 AM, John Cook <notifications@github.com> wrote:

> I installed the most recent version of prompt_toolkit that I could via
> conda.
>
> prompt_toolkit is not part of the main conda repository, so you cannot
> simply run conda install prompt_toolkit as suggested above. When I
> searched anaconda.org for the package, it listed the most recent version
> as that owned by prkrekel, version 0.52. However, conda would not install
> this version, saying that it conflicts with python 3.4*. So I tried the
> next most recent version available for Windows on anaconda.org.
>

You're right. Looking at the output of "conda list" on my machine I see
that I installed it via pip rather than conda. Still, that should give you
the current version, which for my conda python 3.4.3 environmen, is 0.54.


-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by johndcook** [comment]
That worked. So in summary, here's the fix that worked for me:

1. Install prompt_toolkit via pip (not conda).
2. Set an environment variable SHELL_TYPE to prompt_toolkit.

**Comment by scopatz** [comment]
So maybe we need to do the following:

1. have a conda package for prompt-toolkit that is more up-to-date
2. make the windows conda package for xonsh dependent on prompt-toolkit
3. change the windows default for `$SHELL_TYPE` to prompt-toolkit.

Does this seem reasonable to everyone?

**Comment by johndcook** [comment]
Sounds good to me.

**Comment by tritemio** [comment]
@scopatz, yes, and possibly change the default prompt-toolkit colorscheme to match readline (see screenshot above).

**Comment by scopatz** [comment]
> possibly change the default prompt-toolkit colorscheme to match readline (see screenshot above)

Yes, I am hoping that someone will PR all this color stuff :)

**Comment by scopatz** [comment]
I have bumped the version number for pt in conda/conda-recipes#478

**Comment by scopatz** [comment]
I have implemented the proposed windows changes in #501

**Comment by scopatz** [comment]
@johndcook - do this this is ready to close?

**Comment by melund** [comment]
@scopatz @johndcook 

> So maybe we need to do the following:
> 
> 1. have a conda package for prompt-toolkit that is more up-to-date

I keep an updated version of prompt_toolkit and its dependencies on my conda channel. 
`conda install -c melund prompt_toolkit`

It is setup to build automatically on anaconda.org's build server. So it is a one click solution to build new versions. 

> 2. make the windows conda package for xonsh dependent on prompt-toolkit

It already is  https://github.com/scopatz/xonsh/blob/master/recipe/meta.yaml#L23 . Maybe conditional dependency is dropped when running the packages through conda convert. I wouldn't be suprised. 

I also build the xonsh package automatically on anaconda.org. 
`conda install -c melund xonsh`
We really should create a xonsh 'organisation' on anaconda.org. If we set it up to build automatically, we could install development versions with `conda install -c xonsh/channel/dev xonsh` and official versions with `conda install -c xonsh xonsh`. We can also add prompt_toolkit to these channels, so everything just works. 

@scopatz you can also do this under your own user name as I do. But then you are on your own setting it up.

/Morten
 

> 3. change the windows default for `$SHELL_TYPE` to prompt-toolkit.

**Comment by asmeurer** [comment]
+1 for uploading things under the xonsh username on anaconda.org. An advantage there is that you could give permissions to multiple people (similar to GitHub organizations). 

You also might want to ask Continuum if they will add prompt-toolkit support to their official repos.

**Comment by scopatz** [comment]
Ok, Just created a xonsh org on anaconda.org.  Who wants admin access?

**Comment by melund** [comment]
I do :)

**Comment by scopatz** [comment]
Done!

**Comment by scopatz** [comment]
I think that this is now closable. Please reopen if you object.
