### ISSUE TITLE
make vi mode configurable when using prompt-toolkit

### ISSUE THREAD

**Issue by krader1961** [scopatz/xonsh#491]
The readline module automatically determines which key-bindings to use by reading `~/.inputrc`. Prompt-toolkit does not appear to have anything analogous. Vi mode can be enabled by passing `vi_mode=True` to the `prompt()` function. But a better option for xonsh is to pass `enable_vi_mode=True` to the `KeyBindingManager()` call.

To be determined is how to tell xonsh to use vi or emacs mode. It could parse `~/.inputrc` for compatibility with readline. But it's probably simpler to use a xonsh specific config option and or CLI argument.

**Comment by gforsyth** [comment]
Looking at [the docs on vi-mode](http://python-prompt-toolkit.readthedocs.org/en/latest/pages/building_prompts.html#dynamically-switch-between-emacs-and-vi-mode) there's an example of dynamically switching between emacs mode and vi mode.  So it shouldn't be too difficult to have an `$ENABLE_VI_MODE` variable that can be set in session, in a `.xonshrc` or via CLI argument.

**Comment by scopatz** [comment]
Thanks for the suggestion. Very open to having this!
