### ISSUE TITLE
Making an alias that uses itself does not work. (aliases["ls"] = "ls --color=auto -B")

### ISSUE THREAD

**Issue by masasin** [scopatz/xonsh#499]
Changing the alias to lb, for instance, functions as intended.

Incidentally, ls gives colour without needing any `--color=auto` in the options.

**Comment by krader1961** [comment]
Need more details. Works for me on Mac OS X.

```
krader@macpro ~/test $ aliases['ls'] = 'ls --color=auto -B'
krader@macpro ~/test $ aliases['ls']
['ls', '--color=auto', '-B']
krader@macpro ~/test $ touch z z~
krader@macpro ~/test $ ls
z
krader@macpro ~/test $ /bin/ls
z	z~
```

**Comment by masasin** [comment]
These are in my .xonshrc:

    aliases["lb"] = "ls --color=auto -B"
    aliases["ls"] = "ls --color=auto -B"

`ls` is not defined anywhere below this.

When I open a new terminal, this is what happens:

    [masasin:~]$ aliases["lb"] 
    ['ls', '--color=auto', '-B']
    [masasin:~]$ aliases["ls"] 
    ['ls', '--color=auto']
    [masasin:~]$ mkdir /tmp/test
    [masasin:~]$ cd /tmp/test
    [masasin:/tmp/test]$ touch z z~
    [masasin:/tmp/test]$ lb
    z
    [masasin:/tmp/test]$ ls
    z  z~

**Comment by scopatz** [comment]
Hi @masasin - It seems that your `ls` alias is getting reset somewhere. This may be in your bashrc or some other foreign shell that you have configure to read or source on startup. xonsh's default `ls` alias for mac is actually `ls -G`, so it seems more likely that this is coming from something on your system.

**Comment by masasin** [comment]
Beautiful. It was indeed in my .bashrc. I hadn't realized that it was importing it later. (I just import ROS- and virtualenv-related things at the very end.) Thanks!
