### ISSUE TITLE
Multiline statements in prompt_toolkit

### ISSUE THREAD

**Issue by gforsyth** [scopatz/xonsh#507]
This should supercede #467 as multiline code does not indent on prompt_toolkit on any OS, as it isn't yet implemented.  

This is actually two issues, but I believe they're linked closely enough that they need to be dealt with together.  If we want to be able to edit multiline statements in PT, then the prompt should always be a `multiline=True` prompt and will require a custom keybinding to determine when to execute vs. when to create a newline, as mentioned by @jonathanslenders in [here](https://github.com/scopatz/xonsh/pull/490#issuecomment-156034024).  

Since multiline prompts don't do indentation automatically, we also need to use something like `postcmd` found in [`readline_shell.py`](https://github.com/scopatz/xonsh/blob/master/xonsh/readline_shell.py#L129) to handle indenting and dedenting as needed.

In terms of when to execute vs. add a new-line, one criteria for adding a newline is if there's a non-closed parens statement.  Beyond that, what do we need?  We can follow xonsh's current behavior, I think, and always add a newline unless the previous line is only `\n`, i.e. a double-return will execute the statement.

**Comment by gforsyth** [comment]
Ah, one more thing -- as per @scopatz [comment](https://github.com/scopatz/xonsh/pull/490#issuecomment-156713074) -- if the multiline prompt input is properly formatted, we can pass the entire line to `BaseShell.default()` and it should execute without issue.

**Comment by krader1961** [comment]
> In terms of when to execute vs. add a new-line, one criteria for adding a newline is if there's a non-closed parens statement. Beyond that, what do we need? We can follow xonsh's current behavior, I think, and always add a newline unless the previous line is only `\n`, i.e. a double-return will execute the statement.

I definitely want to see multiline statements handled by PT so that they can be edited as a block. But how to do this given the hybrid nature of xonsh is unclear.

In addition to the non-closed parenthesized sequence (by which I assume you mean `$(...)`) we also want to continue accepting input if the previous line ends with a bare backslash since that means the statement is continued whether we're in shell or python mode. Beyond that if we've determined we're in shell syntax mode then a single newline should be sufficient. If we're in python syntax mode then a double-return should be required (and matches the iPython behavior) if the text so far is incomplete or part of a `def`, `class`, or similar block.

Would looking at iPython and similar programs for ideas help?

**Comment by scopatz** [comment]
> Would looking at iPython and similar programs for ideas help?

IPython uses readline, so it might help the readline shell but it would not help prompt-toolkit.  Also, theoretically with the Jupiter integration,you should be able to use a xonsh kernel with the IPython terminal interface. I haven't tried this myself though.

> I definitely want to see multiline statements handled by PT so that they can be edited as a block. But how to do this given the hybrid nature of xonsh is unclear

I'd like to see this happen as well. I don't want different Shell frontends to interfere with each other.

**Comment by gforsyth** [comment]
> In addition to the non-closed parenthesized sequence (by which I assume you mean $(...)) 

Yes, but also any set of parens, to allow breaking long lines without the backslashes, e.g.

```Python
my_var = (foo +
         bar +
         fiddlesticks)
```



> Beyond that if we've determined we're in shell syntax mode then a single newline should be sufficient.

Yeah.  I think we can take a cue from the readline xonsh behavior on this -- try to execute the first line of a multiline statement and if there's an exception, add a newline, indent as needed, etc

If we're always in a multiline environment (which we will be) then I think it's possible to try executing the existing line without "losing" the whole input buffer -- add a keybinding (ref [here](http://python-prompt-toolkit.readthedocs.org/en/latest/pages/full_screen_apps.html#filters-reactivity)) 

```Python
from prompt_toolkit.key_binding.manager import KeyBindingManager
from prompt_toolkit.filters import Condition

manager = KeyBindingManager.for_prompt()

is_multiline = Condition(lambda cli: cli.is_multiline)

@manager.registry.add_binding(Keys.Enter, filter=is_multiline)
def _(event):
    try:
      BaseShell.default()
    except SyntaxError:
      new_line...
```

something along those lines, anyway

**Comment by adqm** [comment]
I think a good first step might be trying to replicate the current behavior of the readline shell (even though it doesn't have the nice feature of bringing the whole block of code back from a single "up" arrow press).

It seems to me like almost everything from the readline shell could be used here, if we knew how to programmatically add to the prompt_toolkit prompt's input buffer.  I just did a quick read-through of what I thought were some relevant pieces of the prompt_toolkit source, but I couldn't find anything.

Anyone know more than I do about that kind of thing?

**Comment by gforsyth** [comment]
I've been playing around with it -- I can, for instance, have the buffer insert a tab and move the cursor down if the last character on the previous line is a colon with 

```
@self.key_bindings_manager.registry.add_binding(Keys.F10, filter=IsMultiline())
def _(event):
    b = event.cli.current_buffer
    if b.document.char_before_cursor == ':':
        b.document = b.document.insert_after('\n'+env.get('INDENT'))
        b.cursor_down()
```

The problem I'm running into now is how to tell the `prompt` to just run what it currently has, so users aren't required to hit meta+Enter to exit the multiline prompt

**Comment by gforsyth** [comment]
Also, most of the stuff for editing `document` of the current buffer is here:  http://python-prompt-toolkit.readthedocs.org/en/latest/pages/reference.html#prompt_toolkit.document.Document
