### ISSUE TITLE
Feature-request: Static configuration file as a command line option

### ISSUE THREAD

**Issue by selepo** [scopatz/xonsh#511]
I suggest that an option to the commandline --config_file is added that allows the user to specify a file location for a static configuration file. (http://xonsh.org/xonshconfig.html)

This would allow portable usage of xonsh, e.g. install python and xonsh on a usb and bring the shell on a stick.

**Comment by scopatz** [comment]
Yup I agree with this.  Only thing to add would be that the option should be called `--config-file`.

**Comment by scopatz** [comment]
or maybe `--config-path` or `--config`
