### ISSUE TITLE
xonsh prompt issue

### ISSUE THREAD

**Issue by migueldvb** [scopatz/xonsh#516]
When I start xonsh on my python 3.5 system I get the following prompt instead of the usual default one.

```
%B%(?..[%?] )%b%n@%U%m%u>
```

**Comment by scopatz** [comment]
Thanks for reporting @migueldvb. Can you tell us a bit more about your system, please?

**Comment by Russell-Jones-OxPhys** [comment]
I get similar on OS X 10.10 in a 3.5 VE.

```
$ pyvenv-3.5 py35ve
$ cd py35ve/
$ source bin/activate
(py35ve) $ pip install --upgrade xonsh
Collecting xonsh
  Downloading xonsh-0.2.3.tar.gz (135kB)
    100% |████████████████████████████████| 139kB 2.9MB/s 
Collecting ply (from xonsh)
  Downloading ply-3.8.tar.gz (157kB)
    100% |████████████████████████████████| 159kB 2.5MB/s 
Installing collected packages: ply, xonsh
  Running setup.py install for ply
  Running setup.py install for xonsh
Successfully installed ply-3.8 xonsh-0.2.3
(py35ve) $ xonsh
[1;32muser@host[1;34m /path/to/ve[1;32m [1;34m$[0m
```

**Comment by migueldvb** [comment]
I am running xonsh 0.2.3 on Arch linux with PLY 3.8 and prompt_toolkit 0.54. Everything works normally except for the prompt that looks like that.

**Comment by gforsyth** [comment]
Hey @migueldvb -- your prompt looks like `$PS1` is being interpreted as a literal string, maybe?  What happens if you enter 

```
$PROMPT = '{user}@{hostname}:{cwd} > '
```

in xonsh?  Does the prompt fix itself?

**Comment by scopatz** [comment]
@migueldvb are you also in a virtual env? And what terminal are you using?

**Comment by scopatz** [comment]
@Russell-Jones-OxPhys - In `[1;32muser@host[1;34m /path/to/ve[1;32m [1;34m$[0m` it looks like `\001...\002`  are being removed around the color codes.  Not sure why this would happen. Are you sshing into an Ubuntu box from Mac OSX?

**Comment by migueldvb** [comment]
@gforsyth that sets the prompt correctly, thank you.

@scopatz I am not using a virtual env and the terminal is termite ($TERM is set to `xterm-termite`)

**Comment by scopatz** [comment]
@migueldvb do you see the same issue when you use a different terminal (xterm, terminator, gnome-terminal, etc) or when you start xonsh directly as the default shell or from within bash?

**Comment by scopatz** [comment]
@migueldvb - I see what is happening! You are inheriting the zsh prompt, which also uses the `$PROMPT` environment variable but with a completely different syntax.  You should be able to recover the xonsh default prompt by 

```console
del $PROMPT
```

Or set your own custom one as @gforsyth mentioned.

**Comment by scopatz** [comment]
Either of these you can put in your xonshrc file.

**Comment by migueldvb** [comment]
Fantastic, thank you very much for figuring out the problem.

**Comment by Russell-Jones-OxPhys** [comment]
@scopatz No, either to OS X from Ubuntu, or using OS X's Terminal.app.

**Comment by Russell-Jones-OxPhys** [comment]
Same after `pip install --upgrade git+https://github.com/scopatz/xonsh.git`. `del $PROMPT` gives `KeyError: 'PROMPT'` which makes sense as it's not set. Using xonsh &> t gives
```
00000000  1b 5d 32 3b 75 73 65 72  40 68 6f 73 74 6e 61 6d  |.]2;user@hostnam|
00000010  65 3a 20 2f 70 61 74 68  2f 74 6f 2f 70 79 33 35  |e: /path/to/py35|
00000020  76 65 20 7c 20 78 6f 6e  73 68 07 01 1b 5b 31 3b  |ve | xonsh...[1;|
00000030  33 32 6d 02 75 73 65 72  40 68 6f 73 74 6e 61 6d  |32m.user@hostnam|
00000040  65 01 1b 5b 31 3b 33 34  6d 02 20 2f 70 61 74 68  |e..[1;34m. /path|
00000050  2f 74 6f 2f 70 79 33 35  76 65 01 1b 5b 31 3b 33  |/to/py35ve..[1;3|
00000060  32 6d 02 20 01 1b 5b 31  3b 33 34 6d 02 24 01 1b  |2m. ..[1;34m.$..|
00000070  5b 30 6d 02 20 0a                                 |[0m. .|
```

**Comment by scopatz** [comment]
@Russell-Jones-OxPhys your problem is definitely different from @migueldvb.  Your encapsulation characters are getting removed somehow.  Does @gforsyth's suggestion of `$PROMPT = '{user}@{hostname}:{cwd} > '` for for you?  We should probably have a system info command to make reporting this stuff easier....

**Comment by Russell-Jones-OxPhys** [comment]
@scopatz It fixes the prompt, but the need for a reset after exiting remains.

**Comment by scopatz** [comment]
Where does the reset command come from?

**Comment by Russell-Jones-OxPhys** [comment]
ncurses 6.0, from MacPorts There's also /usr/bin/reset linked to /usr/bin/tset from com.apple.pkg.BaseSystemBinaries 10.10.0.1.1.1411459885 which works as well.

**Comment by scopatz** [comment]
@Russell-Jones-OxPhys OK, so let me see if I understand this.  You do the following:

1. open terminal in another shell (bash?)
2. activate virtual env
3. start xonsh
4. (do stuff in xonsh)
5. `exit` xonsh
6. Have to reset terminal

Does the same kind of thing happen if instead of xonsh you go through this and use bash?  Do you still need to reset?

**Comment by Russell-Jones-OxPhys** [comment]
@scopatz That's correct. I don't need a reset for /bin/bash or /opt/local/bin/bash.
I also get the prompt above if I don't set $PROMPT in xonsh.

**Comment by scopatz** [comment]
What if you run xonsh from outside of a virtual env?  I think that the virtual env and your native env might be picking up different versions of ncurses.  Or what if (in virtual env) you use prompt-toolkit instead?

**Comment by Russell-Jones-OxPhys** [comment]
It's the same if I install prompt-toolkit. Do I need to add anything to my ~/.xonshrc? (I don't have one at the moment)

**Comment by scopatz** [comment]
To use ptk you either need to set `$SHELL_TYPE = 'prompt_toolkit'` (http://xonsh.org/envvars.html) in your xonshrc or you can start it from the command line with the right argument, namely `xonsh --shell-type=prompt_toolkit`

**Comment by Russell-Jones-OxPhys** [comment]
Prompt-toolkit makes it work perfectly when enabled. Thanks :)
In case it helps with the diagnosis: If I reset, then ^D no longer exits, but after the `exit` command reset is not required. `reset` is required with ^D and `exit` otherwise.

**Comment by scopatz** [comment]
Ahhh OK great! Thanks @Russell-Jones-OxPhys! That is definitely something weird capturing the ^D keypress then.  There are a lot of layers here so it is hard to track down what is going on.  Glad we found something that works for you though!

@migueldvb - do you think that this is ready to close?

**Comment by migueldvb** [comment]
@scopatz yes the issue is solved and can be closed. Thanks!
