### ISSUE TITLE
-l and -i command line options

### ISSUE THREAD

**Issue by tkossak** [scopatz/xonsh#517]
If xonsh should be BASHwards compatible, maybe it could be worth introducing -l (login) and -i (interactive) options? At least as fake arguments, because when I set xonsh as my default shell (Linux Mint) and run [Spacemacs](https://github.com/syl20bnr/spacemacs) I get error:

```
Error (use-package): exec-path-from-shell :init: Non-zero exit code from shell /usr/local/bin/xonsh invoked with args ("-l" "-i" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s' \"${PATH-a421311e83eccdcf118d7f98b41e20d8}\" \"${MANPATH-a421311e83eccdcf118d7f98b41e20d8}\"").  Output was:
"usage: xonsh [-h] [-V] [-c COMMAND] [--no-rc] [-D [ITEM [ITEM ...]]]
             [--shell-type {readline,prompt_toolkit}]
             [script-file] [args [args ...]]
xonsh: error: unrecognized arguments: -l -i
"
```

**Comment by scopatz** [comment]
Thanks for reporting @tkossak. Gladly accept a PR that implemented this.  It shouldn't be too hard.

**Comment by tkossak** [comment]
Thank you.
