### ISSUE TITLE
dark blue against grey black

### ISSUE THREAD

**Issue by stonebig** [scopatz/xonsh#536]
On my 'not high quality' desktop screen, dark blue is weakly distinguishible over grey black.

Would it be possible to change to a `better` color ? light blue, light orange,  light yellow, light pink, ... whatever light

![xonsh_blues](https://cloud.githubusercontent.com/assets/4312421/11456060/3e3b6b0e-967b-11e5-9973-d74134666dcc.GIF)

**Comment by scopatz** [comment]
Yes, this is definitely needed! Thanks for reporting @stonebig. I had thought that there was an open issue for this already, but I was wrong...

**Comment by scopatz** [comment]
@stonebig please see if #541 fixes your problem.

**Comment by melund** [comment]
@stonebig Put 
`$PROMPT_TOOLKIT_COLORS = {'BLUE': '#00d8ff'}` 
in your .xonshrc file. Cmd.exe only supports a few different colors. So even though #00d8ff is nice light blue it becomes kind of turquise. But atleast it is readable. 

If you install something like [cmder](http://cmder.net/) then xonsh looks much nicer.

**Comment by stonebig** [comment]
cmder is a little too big to my taste: 4 Mo for a console.

**Comment by melund** [comment]
I am not sure I follow. ConEmu upon which it is based is a little confusing when it comes to configuration. But 4Mb doesn't seem big to me.

**Comment by stonebig** [comment]
1Mo is the size I would have expected, comparing to SciTE.exe.

**Comment by stonebig** [comment]
with @melund suggestion I get this, which is better, just now I feel the green is also too dark.

![xonsh_green](https://cloud.githubusercontent.com/assets/4312421/11484214/167ff98a-97ad-11e5-99f6-8daa1b5afb3b.GIF)

**Comment by adqm** [comment]
What works for me to force `cmd.exe` to use its "light" blue and "light" green colors is:
```
$PROMPT_TOOLKIT_COLORS = {'BLUE': '#1E90FF', 'GREEN': '#00FF18'}
```

For me, that makes both come out readable for me.  Can you give that a shot?

May be that we'll want to adjust the default values based on platform (or just use these as the defaults everywhere).  Or, really, maybe we should have two sets of defaults: one for white backgrounds, and one for "reverse video," since the colors I just posted don't look great on a white background.

**Comment by scopatz** [comment]
> Or, really, maybe we should have two sets of defaults: one for white backgrounds, and one for "reverse video,

Yeah, IPython has some mechanism for toggling light and dark color schemes.  It would be nice to have for xonsh as well :)

**Comment by melund** [comment]
@adqm . 'BLUE': '#1E90FF' gives a dark blue color again but the green color is good. At least in my win10 cmd.exe.

@stonebig ... Can you test how the following works on your system: 
$PROMPT_TOOLKIT_COLORS = {'BLUE': '#00d8ff', 'GREEN': '#00FF18'}

These colors look good in both cmd.exe and cmder on my win10. If they work for you, then I will make a PR to make them default for Prompt_toolkit.

/Morten

**Comment by melund** [comment]
I made a PR for it https://github.com/scopatz/xonsh/pull/546

**Comment by stonebig** [comment]
With @melund proposal:
- `$PROMPT_TOOLKIT_COLORS = {'BLUE': '#00d8ff', 'GREEN': '#00FF18'}` 
- green and blue are no 'light',
- and I have a bunch of little red '1's.


![xonsh_red](https://cloud.githubusercontent.com/assets/4312421/11508155/8900fc48-9857-11e5-9751-3adb998cd16e.GIF)

**Comment by melund** [comment]
@stonebig I also updated the red color in the PR, and it is merged to master. I will close this. Feel free to re-open if you think something is missing.
