### ISSUE TITLE
RuntimeWarning on Windows: Could not parse functions, malformed pairs

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#545]
I get this error every time I start xonsh. 

```
C:\Users\mel\Documents>xonsh
c:\users\mel\documents\xonsh\xonsh\foreign_shells.py:208: RuntimeWarning: could not parse functions, malformed pairs
  warn('could not parse functions, malformed pairs', RuntimeWarning)
mel@PC ~\Documents $
```

I think it is because I have Git installed with the MSys tools available. Thus, it picks up bash and tries to use the DEFAULT_BASH_FUNCSCMD. https://github.com/scopatz/xonsh/blob/master/xonsh/foreign_shells.py#L130

Maybe there are some problems with backslashes and whitespaces in the windows directory names. 

Here is snippet of the environment string that it tries to parse: 
```
__XONSH_FUNCS_BEG__
__git_aliased_command C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash 757 C:\Program __git_commands 621 Files\Git\mingw64/share/git/completion/git-completion.bash __git_complete C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash 522 C:\Program __git_complete_force_with_lease 1612 Files\Git\mingw64/share/git/completion/git-completion.bash __git_complete_index_file C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash 532 C:\Program __git_complete_revlist 527 Files\Git\mingw64/share/git/completion/git-completion.bash __git_complete_revlist_file C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash 604 C:\Program __git_compute_all_commands 643 Files\Git\mingw64/share/git/completion/git-completion.bash __git_compute_merge_strategies C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash 736 C:\Program __git_config_get_set_var
```

**Comment by scopatz** [comment]
Ahh yeah, so this does not confrm to the format required (see https://github.com/scopatz/xonsh/blob/master/xonsh/foreign_shells.py#L105), which is basically function name followed by the function that the file is defined in.  This seems to have line numbers too.  

If you can come up with an alternative to the `DEFAULT_BASH_FUNCSCMD`, that does work for your setup that would be ideal.  Let me know if you need any help.

**Comment by melund** [comment]
If I am to fix this. I need help. I have no idea what this part of the code does. I am really a noob at bash. What is DEFAULT_BASH_FUNCSCMD supposed to return?

**Comment by melund** [comment]
I am quite sure the error is in the bash code. https://github.com/scopatz/xonsh/blob/master/xonsh/foreign_shells.py#L50

It extracts the function name, line number, and filenames. It then loops over the string `$namelocfile`  eliminating line numbers. The implementation doesn't work if there are spaces in the file names. 

The variable `$namelocfile` looks like this on my computer: 
`__git_aliased_command 763 C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash __git_aliases 757 C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash __git_commands 621 C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash __git_complete 2713 C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash __git_complete_file 522 C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash __git_complete_force_with_lease 1612 C:\Program Files\Git\mingw64/share/git/completion/git-completion.bash` ... 

I don't think I have enough bash-foo to fix this.

**Comment by melund** [comment]
Well the Xonsh way is to do it in Python instead of bash. So I did just that. @scopatz  can you test that it doesn't have not any side-effects on linux.

**Comment by melund** [comment]
Fixed by https://github.com/scopatz/xonsh/pull/553
