### ISSUE TITLE
flake8 to python code style (PEP8)

### ISSUE THREAD

**Issue by juanpabloaj** [scopatz/xonsh#55]
@scopatz , maybe you will like check [flake8](https://pypi.python.org/pypi/flake8) to verify the python code style (PEP8)

https://www.python.org/dev/peps/pep-0008/

to install 

    pip install flake8

a use example:

```bash
$ flake8 xonsh/aliases.py
xonsh/aliases.py:8:1: E302 expected 2 blank lines, found 1
xonsh/aliases.py:28:1: E302 expected 2 blank lines, found 1
xonsh/aliases.py:34:1: E302 expected 2 blank lines, found 1
xonsh/aliases.py:43:69: W291 trailing whitespace
```

**Comment by scopatz** [comment]
Hi @juanpabloaj - yeah, the two blank lines issue is a problem for me, as is trailing whitespace. I'll try to clean this up and be better in the future. :)

**Comment by mbollmann** [comment]
@scopatz, what editor do you use? I have my Emacs set up to automatically remove trailing whitespace before saving, though I usually have to turn it off when working with other people's code because it creates too much noise in the commits ;-)

**Comment by juanpabloaj** [comment]
@mbollmann I don't like start a editor holy war ... but :p 

If you use vim + [syntastic](https://github.com/scrooloose/syntastic) automatically detect if flake8 is installed and use it to mark the python code style issues.

**Comment by scopatz** [comment]
@mbollmann I wrote my own, of course :). It is called xo (http://exofrills.org/).  We can all be text editor friends here, @juanpabloaj!

**Comment by scopatz** [comment]
With landscape.io I believe that this has been fixed.

**Comment by juanpabloaj** [comment]
and https://codeclimate.com/ ?

**Comment by scopatz** [comment]
nope we didn't set that up, but I wouldn't mind it if we did.
