### ISSUE TITLE
Take over bash aliases?

### ISSUE THREAD

**Issue by ivh** [scopatz/xonsh#56]
Custom bash aliases (eg. in ~/.bash_aliases) do not work after starting xonsh from bash.

Maybe documenting how to best port them to xonsh-aliases ist enough.

**Comment by mbollmann** [comment]
Not sure about the automatic porting (xonsh doesn't have to be started from bash after all), but `alias ll='ls -l'` in bash is equivalent to `aliases['ll'] = ['ls', '-l']` in xonsh, which is [documented in the tutorial](http://xonsh.org/tutorial.html#aliases). You can put the respective lines in a ~/.xonshrc file to execute them automatically when xonsh starts. Do you have any suggestions how to make this clearer in the tutorial maybe?

**Comment by ivh** [comment]
I understand that automatic porting might not be a good idea. What about an alias (similar to source-bash) to a function that can swallow a .bash_aliases as argument and parse it to xonsh-aliases?

For the documentation, maybe mention potential pit-falls when naively parsing/converting bash-aliases? Being new to xonsh, I was reluctant to just run a loop over the lines and split the right-hand-side.

Anyway, thank for xonsh! :)

**Comment by scopatz** [comment]
Hi all, this is a feature that I do want to have, I just haven't gotten around to it yet.  I would be happy if someone else did :). Here is how I would do it.  In `xonsh.environ.bash_env()` or a similar function I would add the bash built-in command `alias` to the input (ie `env && alias`).  The alias command in bash prints all your current aliases like follows:

```console
scopatz@athenaie ~ BA$H alias
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias git-commit-count='git log --pretty=format:'\'''\'' | wc -l'
alias git-fat='nice git-fat'
alias grep='grep --color=auto'
alias ipynb='ipython notebook --no-browser'
alias ipynb2='ipython2 notebook --no-browser'
alias ipynb3='ipython3 notebook --no-browser'
alias ls='ls --color=auto -v'
alias mocp='mocp -T transparent-background'
alias nano='xo'
alias pep8='pep8 --ignore=E501 -r'
alias scp-resume='rsync --partial -h --progress --rsh=ssh'
alias screenshot='import -window root'
```

From here you can parse out the name and alias string easily.  The alias string should then be passed through the `shlex.split()` function in the Python standard library before being set in the xonsh aliases.

You should not try to parse the `bash_aliases` file directly for a couple reason. (1) who knows what is written in there (crazy conditional aliases etc), (2) aliases can be defined outside of this file too (ie bashrc).  It is much better to let bash figure all that stuff out.

The reason for doing this in the `bash_env()` function is that it would need to start up in `bash -i` mode, and I have found that time can be noticeable. Better to do this once during xonsh startup than multiple times.

**Comment by wrywerytwreywery** [comment]
There is also a question, though: will `shlex.split` and subprocess handle things like pipes, ${...}, etc?  My initial reaction is that it will be hard to make something that robustly handles all cases, but I could be missing something.

**Comment by scopatz** [comment]
shlex would correctly handle parsing things like `${}` and it would parse the pipe correctly.  The current `subproc_run()` probably would not correctly deal with a pipe in an alias though.  Of course if a bash alias was to a bash function, that would be pretty broken here too.  

I don't think the point here is to have 100% bash-compatibily.  That would involve making a lot of concessions in xonsh that would decrease usability.  Rather, I think that the goal should be to incorporate the parts of bash that are reasonable and useful.  This way we provide a transition out of bash into something better.

**Comment by wrywerytwreywery** [comment]
I think that's absolutely right, but it does mean that if xonsh moves toward something that tries to automatically grab aliases from bash, it should fail gracefully on those aliases that can't be converted.

**Comment by scopatz** [comment]
Yup! I totally agree, @wrywerytwreywery

**Comment by TwonkyHardware** [comment]
> You can put the respective lines in a ~/.xonshrc file to execute them automatically when xonsh starts. Do you have any suggestions how to make this clearer in the tutorial maybe?

I've just installed Xonsh and this was basically my first question.  I know this is an older issue, but as of right now the tutorial doesn't mention .xonshrc at all except in a brief note near the very bottom:

> When executing commands this way [the run control (“xonshrc”) files](https://xon.sh/xonshrc.html) are not applied.

which I would never notice while looking for information about aliases.

I have just over decades of experience with Linux and Bash both personally and professionally, and I have never, not once, literally and exactly zero times, ever wanted to define an alias that was good only for the life of a single session, so it seems strange to me to have so much documentation covering only that use.  A line near the top of the "Aliases" section of the tutorial to the effect of "to make these aliases permanent, put them in your .xonshrc file, which is Xonsh's equivalent of .bashrc or .bash_aliases" would go a long way to clarify this issue for users like me.
