### ISSUE TITLE
Problems with TAB completion

### ISSUE THREAD

**Issue by tiagoantao** [scopatz/xonsh#574]
Consider this:

$ ls Output/
URSO 12-7-2015 10.07.31 PM  URSO 12-7-2015 9.34.58 PM
URSO 12-7-2015 10.15.05 PM  URSO 12-7-2015 9.55.48 PM

[These are directory names that have dates on them - with lots of spaces :( ]

If I do:
$ ls Output/URSO 12-7-2015

And I now hit <Tab> I get the contents of the **current directory** instead of the 4 alternatives above (10.07.31 PM, 9.34.58 PM, ...)

**Comment by scopatz** [comment]
This is definitely because of the spaces. @ajhatz has an open or that is working on this.

**Comment by adqm** [comment]
Thanks for reporting, @tiagoantao.  The pull request @scopatz mentioned has been merged in; can you try this on the current master and see if that fixes the issue?

**Comment by tiagoantao** [comment]
I will report on this as soon as the conda version allows me to test.

**Comment by scopatz** [comment]
I think we are just waiting on the release PR

**Comment by scopatz** [comment]
The conda version should now be updated to v0.2.4

**Comment by tiagoantao** [comment]
This works now, thanks!
