### ISSUE TITLE
from module_name import object_name tab-completion

### ISSUE THREAD

**Issue by denfromufa** [scopatz/xonsh#590]
@scopatz this tab-completion does not work:

from sys import pat<tab here>

Only `import module_name` works.

https://github.com/scopatz/xonsh/issues/364#issuecomment-168070874

**Comment by scopatz** [comment]
We don't currently inspect modules to find their contents.  This should be a relatively easy fix, I would guess.

**Comment by thomasballinger** [comment]
Seems like one could go the IPython route and import the module to find out what names it provides (IPython seems to do this on hitting tab), try to stay safe by only providing completion on modules that have already been imported (this is currently what bpython does for fear of module import side effects - but the user is about to run that code anyway, so this is probably fine). Or do fancy things like AST analysis to guess what objects will be available, which I assume is out of the question.

A separate issue is `from package_name import module_name` which sidesteps these decisions, which would just would leverage existing "knowing what packages exist" infrastructure.

**Comment by scopatz** [comment]
I am pretty sure that we forked some of the IPython code, but don't import the module for the same reasons a bpython.  Fancy AST things are not out of the question if someone wants to implement them. Xonsh is all about the fancy AST things :).  

Thinking out loud, looking for a literal `__all__` would be pretty easy.  If this is not defined, it is pretty easy to accumulate every module-level definition.  This would only apply to pure python and xonsh code, of course. Extension modules would still not be able to be inspected.  

It might be worth looking into the standard library inspect module for tools too. I think that this is what IPython is based on.

**Comment by asmeurer** [comment]
Fixing https://github.com/scopatz/xonsh/issues/344 would also fix this. I would hate for xonsh to end up reimplementing Jedi.

**Comment by scopatz** [comment]
Having jedi as an optional completer would be great if someone wanted to implement it.

**Comment by denfromufa** [comment]
BTW, i used ptpython with autocompletion from jedi and in general it was much smoother experience with installation than xonsh and bpython at least on windows due to python 2 compatibility (yes, it still exists). and it supports jedi already. also built on prompt_toolkit like xonsh, but not bpython.

**Comment by scopatz** [comment]
We have a long-standing issue with Python 2 support, so see the discussion at #66 for more details.  I wil say, though, that the difference between bpython or ptpython and xonsh is pretty significant. Xonsh has its own lexer and parser and targets Python-version specific ASTs. bpython and ptpython can just use whatever interpreter they get. If someone wants to go through the effort of porting to python 2, great!

As far as this affects the installation for Python 2 users, I am sorry. Until we have a port, this is one of those places where the language incompatibilities are really important.  

Again, I'd love for a port to happen.

**Comment by scopatz** [comment]
I believe that this was addressed by #597.  Closing.
