### ISSUE TITLE
xonsh getting killed on Ctrl-C with Iterm2

### ISSUE THREAD

**Issue by eskhool** [scopatz/xonsh#596]
I have the latest code from git and  I am using xonsh as the login shell on Mac OS El Capitan

The same doesn't happen with the Terminal.app but I am sure iTerm2 on mac is popular enough that it warrants a look into.

I have looked and it doesn't seem to be the profile being used in Iterm.

**Comment by scopatz** [comment]
Thanks for reporting @eskhool!  I don't have a mac so I can't test this out.  Can you describe more in detail what happens step-by-step and any errors that pop up?  Does this only occur when xonsh is the default shell?

**Comment by eskhool** [comment]
It happens only with a particular terminal program (iTerm) not with the
default Terminal.app that Mac comes with. iTerm is quite popular though.

I can tell you that when I start xonsh inside a xonsh session the Ctrl-C
does not kill the nested session. It seems to be happening when xonsh is
the first shell.

Will try changing the login shell to bash and report

**Comment by eskhool** [comment]
No luck with making bash the login shell. As long as Iterm.app uses the command as /usr/local/bin/xonsh...it gets killed on a Ctrl-C with the message:
Session Ended (broken pipe). Restart it? from Iterm.

Let me know how I can help debug.

**Comment by scopatz** [comment]
@asmeurer - does this happen to you?

**Comment by scopatz** [comment]
@eskhool - are you using the prompt-toolkit shell or the readline shell?  My guess is that you are using the readline shell and that this is some weird libedit issue. A reasonable fix at this point would then to just use the prompt-toolkit shell.

**Comment by eskhool** [comment]
@scopatz, you are right...I was using the readline shell. Have switched to the prompt-toolkit and so far I don't see that behavior. On the other hand, I distinctly feel a lag with it

**Comment by scopatz** [comment]
> On the other hand, I distinctly feel a lag with it

Hmm that is not good.  Maybe you should report that to @jonathanslenders and prompt-toolkit.

**Comment by jonathanslenders** [comment]
@eskhool, Are you using the latest prompt_toolkit?  0.57?

**Comment by eskhool** [comment]
Yup, the lag is what feels like a typical interpreted language
sluggishness. Its not crisp if you know what I mean. my machine is a
macbook pro retina, 15" so decent configuration.

On Fri, Jan 8, 2016 at 12:34 AM, Jonathan Slenders <notifications@github.com

**Comment by Achimh3011** [comment]
Hi, I have the same problem: OSX, Iterm2 - works with prompt_toolkit, does not work with readline. So, it still is a bug, isn't it?

**Comment by gforsyth** [comment]
Hi @Achimh3011 -- it's still a bug, but so far as we can tell it's an upstream problem, so we aren't going to be able to fix it. If you have any insights on a reasonable workaround (beyond just using prompt_toolkit) we're happy to dive in.
