### ISSUE TITLE
Aliases return repr output (also pipes do not work properly)

### ISSUE THREAD

**Issue by jamiees2** [scopatz/xonsh#6]
I added a function which returns a simple string into the aliases, `aliases["hello"] = lambda arg, stdin=None: ("Hello World!", None)` returns `'Hello World!'` and not `Hello World!` as expected.

Piping this output to cat gives an error `AttributeError: 'str' object has no attribute 'fileno'`

**Comment by scopatz** [comment]
Thanks for reporting @jamiees2. Are you working from the repo or pip or conda?

**Comment by jamiees2** [comment]
From the repo.

**Comment by scopatz** [comment]
Ok! I think I have this working now and subprocess and callable aliases playing nicely together.  Would you mind checking out my 'pipes' branch?

**Comment by jamiees2** [comment]
Neat! works very well!. Only issue i noticed is that running `hello` outputs with a newline, while `hello | cat` does not. This isn't a big problem, bot maybe it should be unified?

**Comment by jamiees2** [comment]
See this pull request: https://github.com/scopatz/xonsh/pull/10
I used output redirection instead of returning a tuple, this makes it way easier to write aliases.

**Comment by scopatz** [comment]
fixed with cdc039c, thanks for all the help @jamiees2!
