### ISSUE TITLE
pyinstaller or cx_freeze bundle to avoid creating new environment for py2 users

### ISSUE THREAD

**Issue by denfromufa** [scopatz/xonsh#602]

**Comment by scopatz** [comment]
Hi @denfromufa, I don't understand what this means. Could you be more specific, please? It seems like you want a binary package for xonsh?  I'd be open to pull requests of this nature.  Most of our install options that we list are maintained by third parties...

**Comment by scopatz** [comment]
Only pypi and conda are maintained by us.

**Comment by denfromufa** [comment]
Let's close this issue, since this does not solve problems with importing py2 modules even if stand-alone binary is used.
