### ISSUE TITLE
`name in __xonsh_env__` always evaluates to True

### ISSUE THREAD

**Issue by riccardomurri** [scopatz/xonsh#610]
Containment test `name in __xonsh_env__` always evaluates to Python
``True``, even if no key `name` is defined in `__xonsh_env__`.

The reason seems to be that `Mapping.__contains__` (inherited by `Env`
through `MutableMapping`), relies on `self[key]` to throw a `KeyError`
if a key is not defined::

    426     def __contains__(self, key):
    427         try:
    428             self[key]
    429         except KeyError:
    430             return False
    431         else:
    432             return True

However, `Env.__getitem__()` is basically an alias for `Env.get()` and
will return ``None`` when asked for a non-existing key.

Trying to fix this by having `Env.__getitem__()` raise an exception
when a key is not found makes xonsh crash when trying to execute a
command in subprocess mode::

    $ echo $FOO
    Traceback (most recent call last):
      File "/home/rmurri/sw/src/xonsh/xonsh/base_shell.py", line 136, in default
        self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
      File "/home/rmurri/sw/src/xonsh/xonsh/execer.py", line 127, in exec
        return exec(code, glbs, locs)
      File "<xonsh-code>", line 1, in <module>
      File "/home/rmurri/sw/src/xonsh/xonsh/environ.py", line 293, in __getitem__
        raise KeyError
    KeyError

This shows IMHO that in the code calls to `Env.__getitem__` and `Env.get`
are used interchangeably thought they should not be.  Unfortunately,
the traceback makes it impossible to understand where I should start,
so I'm opening this issue now :-)

**Comment by scopatz** [comment]
Thanks for reporting @riccardomurri! #611 should address this once it is merged in.

**Comment by scopatz** [comment]
@riccardomurri could you please confirm that this works for you and close. Thanks!

**Comment by riccardomurri** [comment]
I've checked branch `env_contains` and it works.

Thanks!

**Comment by adqm** [comment]
Fantastic!  Closing now.  Please feel free to reopen if you feel like there is still something missing.
