### ISSUE TITLE
Bug in PTK completion for filenames with single-quotes

### ISSUE THREAD

**Issue by gforsyth** [scopatz/xonsh#613]
This only effect `prompt_toolkit` as the bug stems from how `lprefix` is processed by `xonsh.Completer.complete`

Take another terrible filename
```
gil@bad_cat ~/test $ ls
gil's.less.terrible.filename
```

Since there's only one file in the directory, tab-completion works if I type a single letter and then hit tab, but if I type `cat gil's<TAB>` it completes to

```
cat gilgil's.less.terrible.filename
```

The issue stems from [_path_from_partial_string in completer.py](https://github.com/scopatz/xonsh/blob/master/xonsh/completer.py#L24) -- it calls `tools.check_for_partial_string` which does find a partial string because of the `'` in the filename.  

Reporting so I remember about this -- not sure of a fix yet but it should hopefully be relatively trivial.  And in any case, `'` in filenames is a terrible idea.

**Comment by scopatz** [comment]
Thanks for reporting @gforsyth!  

> And in any case, ' in filenames is a terrible idea.

Much agreed!

**Comment by scopatz** [comment]
closing due to #615
