### ISSUE TITLE
xonsh hangs when resuming suspended jobs

### ISSUE THREAD

**Issue by willsALMANJ** [scopatz/xonsh#616]
In a fresh `xonsh` shell launched with no `.xonshrc` file, using `fg` after suspending a command with `<ctrl>+Z` causes `xonsh` to hang. Further input to the keyboard, including `<ctrl>+C` and `<ctrl>+D` is printed to the terminal but does not do anything. Here is an example of the terminal output for one such case:

```
user@machine ~ $ man git

*[1] stopped: man git & (5743)
user@machine ~ $ fg
*[1] running: man git (5743)
^C^C^C^Cjjflakjdakjl

d
d
d
d
```

Everything after the `running: man git` line is me mashing on the keyboard.

I see this for version 0.2.4 on Arch Linux (installed via the package in the AUR) in GNOME Terminal. I lauched xonsh by creating a new profile in GNOME Terminal and having it launch `xonsh` as a custom command (i.e. I didn't change my system's shell but I am also not invoking xonsh from within another shell).

Since installing from the AUR is one of the suggested ways of installing `xonsh`, hopefully someone else is using `xonsh` this way and can help debug what is going on. I tried to make sure this was reproducible on the most basic set up possible. I was just trying out `xonsh` for the first time so I am not too familiar with it, but the inability to suspend and resume jobs makes it pretty much unusable as a shell for me.

**Comment by adqm** [comment]
Thanks for reporting, @willsALMANJ ! I can confirm that this is happening, but, in fact, it seems like I can _only_ reproduce it with `man` (stopping/resuming other programs seems fine from here). Can you try with some other programs and see whether they work for you?

Regardless, I can try to look in and see what is going on.

**Comment by willsALMANJ** [comment]
I first encountered this using `vim` and then checked that it also showed up for `man` since that seemed like a little bit simpler example.

Trying out other commands, I see similar issues though they're not quite identical. `emacs -nw` suspends and resumes okay once, but `xonsh` hangs when I suspend `emacs` a second time. `less` is the same. Suspending `python` returns to the `xonsh` prompt but keyboard input is no longer echoed to the terminal. Resuming `python` a second time and then suspending it again causes `xonsh` to hang.

I tried a few other commands. I couldn't find any that would cleanly suspend and resume more than once. Either the first resume or the second suspend hung. Also, I tested in `xterm` just to try a different terminal emulator but the behavior seemed to be the same.

**Comment by gforsyth** [comment]
I believe this has been fixed in master by #962 and #867 and I can no longer reproduce these issues.  Closing, but please let us know if the issue persists.  Thanks!

**Comment by willsALMANJ** [comment]
Issue seems to be fixed for me as well. Thanks for linking back to this issue so I would know about the fix. I was just starting to try out xonsh but job control is very important to my workflow so xonsh wasn't really usable for me to try out until now.

**Comment by scopatz** [comment]
Thanks @willsALMANJ - glad these things seemed to have worked out.  Please continue to let us know if you encounter issues - or of course, feel free to put in PRs too!

**Comment by willsALMANJ** [comment]
I'd say open a separate ticket and reference this one there. It seems like possibly a slightly different issue because in the original issue even `^C` did not work after suspending and resuming a job whereas it seems that it still works for you. 0.4.0 seems to be the first release that includes the patches that closed this issue. It might be worth testing in that version or one shortly after it to see if there was a regression in the job control features since then or if this is a separate issue that has always been present.

**Comment by scopatz** [comment]
Yes, please open a new issue @jaraco so we don't lose this one. Thanks!
