### ISSUE TITLE
Hangs when attempting to group activities with parenthesis in subproc-mode. 

### ISSUE THREAD

**Issue by icarito** [scopatz/xonsh#62]
![captura de pantalla_2015-03-16_07-52-22](https://cloud.githubusercontent.com/assets/199755/6666902/790ca2b0-cbb6-11e4-9179-a76bb1dc6f4f.png)

After this, vim becomes unresponsive and xonsh uses up 99% CPU.

This is with xonsh as default shell.

**Comment by wrywerytwreywery** [comment]
Able to reproduce with the following directly from bash:
`xonsh -c "(ls) > /tmp/test"`

The following works:
`xonsh -c "ls > /tmp/test"`

But the following doesn't:
`xonsh -c "(ls)"`

```...NameError: name 'ls' is not defined```

Similarly, running `(ls)` from a xonsh prompt fails.

**Comment by icarito** [comment]
I found out because my .vimrc contained a call to system. I don't know the proper term for using all CPU, sorry for using words like crazy, bezerk.

**Comment by scopatz** [comment]
Ahh yeah, This is a parser issue.  I am not sure it is a bug per-say, though.  Right now subproc-mode does not allow you to group activities with parentheses.  It shouldn't just hang, though. That is bad.  I don't know much about the details of how vim is implemented.  Are the parentheses just inserted for you automatically?

**Comment by icarito** [comment]
Yes, there was a line in my .vimrc which I had to comment, it was to
make vim maximized by default.

call system('wmctrl -i -b add,maximized_vert,maximized_horz -r '.v:windowid)

It was an ugly hack, and, come to think of it, I like it better not
maximized, so thank you.

Just then let's change the name of the issue again to better reflect it.

Agreed it shouldn't just hang. Instead, it should fail in a verbose manner.

**Comment by icarito** [comment]
I dont' know if this is related, but the following just triggered
another crash:
sudo apt-get update && apt-get upgrade

this time on debian testing

El 16/03/15 a las 18:58, Anthony Scopatz escibió:

**Comment by scopatz** [comment]
What was the crash?

**Comment by icarito** [comment]
using 100% cpu

**Comment by icarito** [comment]
i.e. going bezerk

**Comment by scopatz** [comment]
Ok.  Same code that caused it, though?

**Comment by icarito** [comment]
um, doing:

    sudo apt-get update && apt-get upgrade

crashed xonsh

**Comment by scopatz** [comment]
Ohhhhh! Sorry. Yeah.  `&&` is not valid xonsh syntax.  Use semicolons (`;`) to separate instead.  ie

```console
sudo apt-get update; apt-get upgrade
```

Again, it shouldn't hang.

**Comment by scopatz** [comment]
Ok!  On master now (637702f), it should not hang.  At the prompt, it should enter a multiline mode.  And with `xonsh -c` it will fail silently (which should be fixed). But it doesn't hang!

**Comment by icarito** [comment]
Confirmed, it doesn't hang now! Thanks! Also, it does fail silently.

**Comment by scopatz** [comment]
Great!  Progress!

**Comment by scopatz** [comment]
I believe that this has been more or less addressed with the and/or stuff.  Feel free to reopen.
