### ISSUE TITLE
.xonshrc file

### ISSUE THREAD

**Issue by eldamir** [scopatz/xonsh#63]
I am sorely missing a .xonshrc file or similar. Something like what the .bashrc is to BASH.
I could not find anything on the matter in the documentation or while googling.

I'd love to have something like the following:

```
$PROMPT = '{BLUE}{user}{WHITE}@{GREEN}{hostname}{WHITE}:{RED}{cwd}{YELLOW}{curr_branch}{WHITE}\n $ '
aliases['gits'] = ['git', 'status']
aliases['gitl'] = ['git', 'log']
```

So that when I open a terminal, this code is executed

**Comment by eldamir** [comment]
Right, nevermind. It is actually mentioned here: http://xonsh.org/tutorial.html#environment-variables

**Comment by scopatz** [comment]
Hi @eldamir, yup it is there!  Thanks for using xonsh!
