### ISSUE TITLE
Multiline input does not work on OS X/iterm2

### ISSUE THREAD

**Issue by bkeroack** [scopatz/xonsh#64]
Unless I'm missing something obvious, multiline input does not seem to work:
![image](https://cloud.githubusercontent.com/assets/1949804/6669417/032d362c-cbb6-11e4-927b-cecf593ba58b.png)

I cannot get the command to execute. Hitting enter just creates another line. I have to Ctrl-C to break back to a normal  prompt.

This is on OS X with iterm2. The same behavior occurs with Terminal.

**Comment by justyns** [comment]
FWIW, I am able to get your two examples working with iterm2 (Build 2.0.0.20141103) and xonsh 0.1.2.

**Comment by bkeroack** [comment]
I tested with master HEAD and multiline works. The problem must be with
whatever is pushed to PyPI.

**Comment by scopatz** [comment]
I wasn't able to reproduce this either.  If HEAD works, great.  We'll do another micro release before the end of the week, I am sure.

**Comment by scopatz** [comment]
Are you still experiencing this on master, @bkeroack?

**Comment by bkeroack** [comment]
:+1: Looks good to me. Installed 0.1.4 via pip.

**Comment by scopatz** [comment]
Awesome!
