### ISSUE TITLE
Install error - cannot import name TemporaryDirectory

### ISSUE THREAD

**Issue by QwertyJack** [scopatz/xonsh#646]
$ sudo python setup.py 
    Traceback (most recent call last):
      File "setup.py", line 10, in <module>
        from tempfile import TemporaryDirectory
    ImportError: cannot import name TemporaryDirectory

**Comment by scopatz** [comment]
Are you using a python that is before v3.4? TempDir only appeared in 3.2 https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory

**Comment by QwertyJack** [comment]
I'm using 2.7. Thank you very much!
Anyway, I hope Xonsh will support python2.

**Comment by scopatz** [comment]
Thanks. As per Python 2, we have an open issue and anyone is free to tackle it :)

**Comment by tmbdev** [comment]
What about mentioning on the home page that it is Python 3 only, and checking for that in the installer and giving a better error message?

**Comment by gforsyth** [comment]
Hey @tmbdev -- I put in a PR to address your comment.  There has been a check in `setup.py` for supported Python version since way back, but it was never reached since we import a submodule that doesn't exist for Python < 3.2.  That should be fixed shortly.

**Comment by scopatz** [comment]
Fir the record @tmbdev, two statements on the version are on the home page. The first is in the second sentence on the home page:

```
Xonsh is a Python-ish, BASHwards-looking shell language and command prompt. The language is a superset of Python 3.4+ with additional shell primitives that you are used to from Bash and IPython.
```

The second is in the dependencies listing: http://xon.sh/#dependencies

If you have ideas on how to increase the visibility of this statement, please let us know!  Happy to make the more clear if we can.
