### ISSUE TITLE
Custom $PATH additions not available in os.environ

### ISSUE THREAD

**Issue by moigagoo** [scopatz/xonsh#661]
I added `$PATH.insert(0, '/usr/local/bin')` to .xonshrc. In xonsh, $PATH is `['/usr/local/bin', '/usr/bin', '/bin']`. However, `import os; os.environ['PATH']` yields `'/usr/bin:/bin'`.

Due to this, [hg_dirty_working_directory](http://xonsh.org/_modules/xonsh/environ.html#hg_dirty_working_directory) doesn't work properly showing false negatives. hg is in /usr/local/bin, so it raises FileNotFoundError when called.

**Comment by scopatz** [comment]
Thanks for reporting @moigagoo. Potential fix is in #663

**Comment by moigagoo** [comment]
@scopatz It fixes the hg issue, but os.environ['PATH'] is still not changed. It doesn't cause any trouble for now, but you may want to keep that in mind.
