### ISSUE TITLE
Weird differences between cmd.exe and cmder 

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#666]
I use cmder a lot as alternative console emulator on windows. I see some weird difference between cmd.exe and cmder. I don't see the git branch names in the prompts when working on cmder. Also, I am quite sure this worked at some point.

On cmder `get_git_branch()` returns `''` with cmder and `'master'` with cmd.exe. It happens even though the direct command `git rev-parse  --abbrev-ref HEAD` returns `master` on both. 

Investigating this came down to a different behaviour in the subprocess call. 

On cmder including/excluding the `stderr=subprocess.PIPE` makes the difference: 
```
mel@ANYBODY-MEL ~/Documents/xonsh $ subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD'])
b'master\n'
mel@ANYBODY-MEL ~/Documents/xonsh $ subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD'],stderr=subprocess.PIPE)
b''
```

Starting xonsh through cmd.exe
```
mel@ANYBODY-MEL ~/Documents/xonsh master $ subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], stderr=subprocess.PIPE)
b'master\n'
mel@ANYBODY-MEL ~/Documents/xonsh master $ subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD'])
b'master\n'
```

Can anyone help me figure why there is this difference...

**Comment by scopatz** [comment]
This is very weird.  What happens if you say `stderr=subprocess.STDOUT` instead?

**Comment by melund** [comment]
I will try tomorrow when I am back at my laptop. Getting late here.

**Comment by melund** [comment]
It is the same result.
```
mel@ANYBODY-MEL ~/Documents/xonsh $ cmd = ['git', 'rev-parse', '--abbrev-ref', 'HEAD']
mel@ANYBODY-MEL ~/Documents/xonsh $ cwd = os.getcwd()
mel@ANYBODY-MEL ~/Documents/xonsh $ subprocess.check_output(cmd, cwd=cwd, universal_newlines=True)
'master\n'
mel@ANYBODY-MEL ~/Documents/xonsh $ subprocess.check_output(cmd, stderr = subprocess.STDOUT, cwd=cwd, universal_newlines=True)
''
```

But it is not really xonsh related. I just realized that it also happens in pure python.

**Comment by scopatz** [comment]
Agreed that it is not xonsh's fault, but if we can find can find a work around we should probably include it :).  

What if you set `shell=True`? You might need to set `cmd = ' '.join(cmd)` for this.

My thought is that maybe cmder might not be flushing the stdout buffer fully or it is perhaps getting stuck in a psuedo terminal somewhere.

**Comment by melund** [comment]
@scopatz , No difference:
```
mel@ANYBODY-MEL ~/Documents/xonsh $ cmd = ['git', 'rev-parse', '--abbrev-ref', 'HEAD']
mel@ANYBODY-MEL ~/Documents/xonsh $ cmd = ' '.join(cmd)
mel@ANYBODY-MEL ~/Documents/xonsh $ subprocess.check_output(cmd, stderr = subprocess.PIPE, cwd=cwd, universal_newlines=True, shell=True)
''
```

**Comment by scopatz** [comment]
hmm, continuing through the Popen options, what about if `start_new_session=True`?

**Comment by melund** [comment]
Nope. It still only works if I remove the `stderr` redirection. 
```
mel@ANYBODY-MEL ~/Documents/xonsh $ subprocess.check_output(cmd, stderr = subprocess.PIPE, cwd=cwd, universal_newlines=True, start_new_session=True)
''
```

**Comment by scopatz** [comment]
OK, one last thing and then I suggest that we implement a check to see if the result is empty and if so rerun without the redirection.  Can you try to see if `stderr = subprocess.DEVNULL` works?  I doubt it will at this point.

**Comment by melund** [comment]
DEVNULL didn't do anything either. I agree with your idea for a workaround. I will make a PR.

**Comment by scopatz** [comment]
Great! Thanks!

**Comment by scopatz** [comment]
Closing give #667

**Comment by JanSchulz** [comment]
This looks more or less like a bug I worked around in matplotlib when I run it in debug mode. Any idea what is causing this?

**Comment by scopatz** [comment]
No idea what is causing it, as you can see from the conversation here.  We tried a bunch of stuff but ultimately decided to use this hot-fix because we don't grok the underlying cause. If you ever figure it out, let us know!  We think it is a ConEmu / cmder bug.  However, it might also be a CPython bug.  Hard to say without diving into a stack trace..

**Comment by JanSchulz** [comment]
I opened https://github.com/Maximus5/ConEmu/issues/546 to ask what this could be...

**Comment by ilius** [comment]
I have some troubles with Cmder but not ConEmu:
Make sure to test on ConEmu as well.

https://github.com/Maximus5/ConEmu/issues/546#issuecomment-1416917284
