### ISSUE TITLE
error when tty login

### ISSUE THREAD

**Issue by arkhan** [scopatz/xonsh#676]
Hello again, but it happens that when I try logearme a tty with a user whose shell xonsh default throws me this error:

![photo_2016-02-12_20-20-00](https://cloud.githubusercontent.com/assets/3141865/13024824/1607bf46-d1c9-11e5-8cd5-e7bc987d9847.jpg)

Thanks for the help

**Comment by gforsyth** [comment]
Hey @arkan -- is the native encoding of your terminal ASCII?  That can cause trouble like this.  

What's the output of `localectl`?

As a quick(ish) check, you can try adding this to your `xonshrc` (assuming you want US english encoding...)

```
$LANG="en_US.UTF-8"
$LC_ALL="en_US.UTF-8"
```

**Comment by arkhan** [comment]
~ $ localectl 
   System Locale: LANG=es_EC.UTF-8
       VC Keymap: n/a
      X11 Layout: n/a

**Comment by scopatz** [comment]
This might be a legitimate encoding error on our part, looking at the traceback. Can you please post the contents of your config file please?

**Comment by scopatz** [comment]
@arkhan - If you wouldn't mind trying the fix in #677, I'd really appreciate it. Thanks

**Comment by arkhan** [comment]
@scopatz I tried the #677 and fix the unicode error

**Comment by scopatz** [comment]
Sorry @arkhan, I don't understand.  It *does* fix the error?

**Comment by arkhan** [comment]
Yes...

**Comment by scopatz** [comment]
Great!

**Comment by tgoodlet** [comment]
@scopatz I'm seeing this same problem (mind you different offending characters) when I set `xonsh` as my default shell and start a tty.

I'm pretty sure all my locale stuff is correct as well.

What can I get you to help?

**Comment by laerus** [comment]
Hey @tgoodlet can you please post the output of `xonfig` and/or the traceback you get, thank you!

**Comment by tgoodlet** [comment]
@laerus hehe so I lied. 

It is a different [traceback](https://drive.google.com/file/d/0B4eTDpaO9mj7ZnA0b05oLVlxUU0).

`xonfig` is:
```
 >>> xonfig                                                             
+------------------+---------------------------------------------------+
| xonsh            | 0.4.7                                             |
| Git SHA          | 8870fd9                                           |
| Commit Date      | Nov 27 14:19:34 2016                              |
| Python           | 3.5.2                                             |
| PLY              | 3.7                                               |
| have readline    | True                                              |
| prompt toolkit   | 1.0.9                                             |
| shell type       | prompt_toolkit                                    |
| pygments         | 2.1.3                                             |
| on posix         | True                                              |
| on linux         | <xonsh.lazyasd.LazyBool object at 0x7f73338f4128> |
| distro           | arch                                              |
| on darwin        | False                                             |
| on windows       | False                                             |
| on cygwin        | False                                             |
| is superuser     | False                                             |
| default encoding | utf-8                                             |
| xonsh encoding   | utf-8                                             |
| encoding errors  | surrogateescape                                   |
+------------------+---------------------------------------------------+
```

**Comment by scopatz** [comment]
Can you try setting `xon.sh` as your login shell instead?  Also note that your locale may be different if you login to a tty outside of desktop / X / unity / whatever the kids draw with these days environment. The windowing systems set a lot of envvars.

**Comment by astronouth7303** [comment]
Yup. This is a thing that can happen with unicode on VTs, SSH,  etc. My experiences and debugging are documented in #1471. Basically, unicode in `$PROMPT` won't give you trouble, but unicode in `$TITLE` _will_.  My [xonshrc](https://gist.github.com/astronouth7303/33d5e61cdb1db435526b01ad140f14fb#file-xonshrc-L27) is written for this.

**Comment by tgoodlet** [comment]
@scopatz tried and didn't work :(

@astronouth7303 aha! you helped me find the problem.

I added that `$TITLE`line from your config and it caused `xonsh` to fail at `rc` parse time thus falling into the default config. At that point checking `locale` showed incorrect settings! 

Assigning `LANG=en_US.UTF-8` in my `~/.pam_environment` fixed it :)

@astronouth7303 I've still got something else weird though. When I try to use that `"\N{SPIRAL SHELL}"` in front of my prompt like in your config it displays an unknown symbol...

```
 >>> xonsh
 🐚>>>
```

Also doing a utf-8 test:
```python
# zsh
 >>> perl -le 'print "\x{c3}\x{94}"'
Ô
 
 >>> xonsh                          

xonsh >>> perl -le 'print "\x{c3}\x{94}"' 
# no output?
```

Any ideas?

**Comment by astronouth7303** [comment]
Unicode support is complicated. It depends on your terminal emulator and declared locale. RC parsing may also depend on your locale setting, which is why I used the `\N` escape instead of embedding the unicode directly.

Setting your locale globally should clear up a number of issues.

I can, however, reproduce the perl printing bug. Please raise that as a separate issue.

**Comment by tgoodlet** [comment]
@astronouth7303 made that issue.

This definitely so far seems to be `xonsh`:
```
xonsh >>> echo -e "\xE2\x98\xA0"                                 
â 

xonsh >>> zsh                                                                                                                    
 >>> echo -e "\xE2\x98\xA0"
☠

 >>> bash
[tyler@goodboy-xps ~]$ echo -e "\xE2\x98\xA0"
☠

```
^ a skull and bones if you can't see it.
