### ISSUE TITLE
Handle paths with spaces

### ISSUE THREAD

**Issue by jessejoe** [scopatz/xonsh#68]
When you tab complete folders with spaces in them, the spaces are not delimited with `\ `, so you have to instead put quotes around them:

```
jesse@rmbp13 ~/xonsh $ mkdir "folder with spaces"
jesse@rmbp13 ~/xonsh $ ls
folder with spaces
jesse@rmbp13 ~/xonsh $ cd folder with spaces/
                             ^ Hit tab to complete
cd takes 0 or 1 arguments, not 3
jesse@rmbp13 ~/xonsh $ ls folder with spaces/
                             ^ Hit tab to complete
ls: folder: No such file or directory
ls: spaces/: No such file or directory
ls: with: No such file or directory
jesse@rmbp13 ~/xonsh $ cd "folder with spaces"
jesse@rmbp13 ~/xonsh/folder with spaces $
```

Adding the the `\ ` instead doesn't work either (maybe why they aren't added during tab completion?):
```
jesse@rmbp13 ~ $ cd folder\ with\ spaces/
................
...
SyntaxError: <xonsh-code>:1:10: Invalid token '\\'
```

This is on OSX with xonsh `0.1.2`.

**Comment by scopatz** [comment]
Ahh super interesting.  Maybe the tab-completion should add the quotes.  How do you feel about that?

**Comment by scopatz** [comment]
Thanks for reporting @jessejoe!

**Comment by wrywerytwreywery** [comment]
To me, having the completer add the quotes feels like the right thing.  I started working on this, but it looks like it is going to be difficult to get something that feels "right."

That is, it's easy to make the completer add the quotes.  But it seems like it will be hard to get it to complete halfway-finished quoted strings (particularly after a space).  So if we have a directory called `name with spaces`, then it will complete `na` or `"na` or `'na`, but not `"name wi`.

This is maybe fine, but the downside is if we do: tab complete, backspace, tab; then it will not re-complete to the right value.

I will submit a pull request with what I have now in case it helps, but it isn't perfect.

**Comment by scopatz** [comment]
Cool, It seems like the right thing to do to me would be to insert quotes on both sides, though.  I'll check out your PR.

**Comment by jessehudl** [comment]
Adding quotes seems *okay*, that's what `cmd.exe` does in Windows, however it is very annoying when it matches something else, you have to backspace, tab again, possibly backspace again, tab again, etc. This would honestly make it a little too annoying for daily use for me.

**Comment by jessejoe** [comment]
Adding quotes seems *okay*, that's what `cmd.exe` does in Windows, however it is very annoying when it matches something else, you have to backspace, tab again, possibly backspace again, tab again, etc. This would honestly make it a little too annoying for daily use for me.

**Comment by scopatz** [comment]
Adding quotes or not seems like the kind of thing that could easily be configure by an environment variable. If you wanted to add that behavior, that would be great!

**Comment by scopatz** [comment]
I am closing this in favor of #181.
