### ISSUE TITLE
dir on Windows

### ISSUE THREAD

**Issue by Siecje** [scopatz/xonsh#686]
I'm using Git CMD on Windows 10.

I installed xonsh with pip (0.2.3).

If I do
```shell
$ dir
<function dir>
```
Because of the Python function. ```dir .``` works.

One solution might be adding ```ls```, just like how ```which``` does ```where``` on Windows..

**Comment by melund** [comment]
I am not a big fan of that solution. `ls` and `dir` doesn't behave similarly, the same way `which` and `where` does. Also, I have `ls` and all the other Unix tools on my PATH (msys from the git installer). So that would make for an annoying default. 

You can of course easily make your own alias if you want: `aliases['gp'] = ['dir', '.']`

**Comment by scopatz** [comment]
Also, if you really want to live life on the edge you can do 

```
import  builtins
del builtins.dir
```

That said, xonsh itself uses dir in the execer and so this may not be the wisest move.

**Comment by scopatz** [comment]
By the way, thanks for reporting this issue @Siecje.

To echo @melund's concerns, though, there is a fundamental namespace collision between Python and Windows commands in the case of `dir`.  I am open to suggestions, but I think that the best that we can do is give people the tools to choose how to resolve this issue on their particular system.

I am think we can and should make choosing between different solutions as painless as possible. That said, literally all you have to do to alias ls to dir is stick the following line in your xonshrc file.

```python
aliases['ls'] = 'dir'
```

I've known people who do the opposite on posix systems.

**Comment by Siecje** [comment]
@melund After installing xonsh, I was able to use it from Git CMD but not Git Bash.
I tried adding ```$PATH=$PATH:/c/Users/Cody/Anaconda3/Scripts``` to my ```~/.profile``` but I get ```:/c/Program: No such file or directory``` I guess because ```Program Files``` is in my path with a space.

Thanks for the alias, super convenient to just set them.
I set ```aliases['ls'] = dir .``` and was surprised when ```ls ..``` worked.

```ls``` doesn't do anything in ```cmd```. But were are in ```xonsh``` just like ```1 + 1``` doesn't do anything in ```cmd```.

@scopatz What are the different solutions? How would users select which solution to use?

**Comment by scopatz** [comment]
> I tried adding $PATH=$PATH:/c/Users/Cody/Anaconda3/Scripts to my ~/.profile but I get :/c/Program: No such file or directory I guess because Program Files is in my path with a space.

Try putting it in quotes or using a backslash to escape the space, `Program\ Files`.

> Thanks for the alias, super convenient to just set them

No problemo!

> @scopatz What are the different solutions? How would users select which solution to use?

Well it really depends what the User's system looks like.  xonsh is in sort of a funny place in that it is *natively* supposed to be a cross platform shell.  I see the following three major different use cases:

- Posix system (Linux, Mac OS X, BSD,etc)
- Pure NT or Windows 
- Windows with posix components installed (via msys or git-bash or whatever)

Unfortunately it is very hard to distinguish between the last two.  For posix and windows-with-posix, users don't need to do much  to customize their system.  For windows without posix systems, user still don't need to do much, but it might be very different depending on whether they want posix-like functionality and even what terminal emulator they are using (uggh). 

I think that the best that we can do right now as a project is help document these differences.  This is one reason that we have the [Windows Guide](http://xon.sh/windows.html) page.  This should probably be updated with things like the ls/dir alias for people who want posix like functionality without insalling the actual coreutils package. 

I'd really appreciate it if you (or anyone else) helped in updating the docs in this way.  It sounds like you found it useful.  Please let me know if you need any help.
