### ISSUE TITLE
More intelligent intermix between python and bash pipes

### ISSUE THREAD

**Issue by k-bx** [scopatz/xonsh#69]
I'd like this example to not hang, if you know what I mean:

```
$ print("2") | grep "2"
```

**Comment by scopatz** [comment]
This example, should not hang, I agree.  However, I don't think it is entirely valid either. Subprocess  pipes are meant to explicitly operate on constructs that accept an argument list and stdin and return stdout and stderr.  Without this interface, subprocess piping is not valid.  You could always do something like this, though:

```console
scopatz@athenaie ~ $ aliases['print'] = lambda args, stdin: print('\n'.join(args))
scopatz@athenaie ~ $ print 2 | grep 2
2
scopatz@athenaie ~ $ print "2" | grep "2"
2
```

Maybe we could add an alias wrapper function into the builtins, even?

**Comment by k-bx** [comment]
@scopatz yeah, probably would be best to add:

- error-message that one of pipes is not valid
- suggest putting it inside some wrapper like `to_pipe = lambda f: lambda args, stdin: f()`

**Comment by scopatz** [comment]
That seems right to me. Pull requests welcome :).

**Comment by scopatz** [comment]
OK @k-bx. This should not longer (637702f) hang.  It should enter multiline mode at the prompt.

**Comment by k-bx** [comment]
Perfect then, thanks!
