### ISSUE TITLE
Dependencies should be declared by package metadata

### ISSUE THREAD

**Issue by dahlia** [scopatz/xonsh#7]
xonsh requires ply both at runtime and install-time.  It makes hard to install xonsh using [pipsi][].  There are `install_requires` (runtime dependencies) and `setup_requires` (dependencies for invoking setup.py script) keywords provided by setuptools.  It would be better if dependencies are declared using these keywords.

[pipsi]: https://github.com/mitsuhiko/pipsi

**Comment by scopatz** [comment]
These are setuptools only, correct?

**Comment by scopatz** [comment]
Ok @dahlia, can you try it now please?

**Comment by dahlia** [comment]
@scopatz Now it does work well!

**Comment by scopatz** [comment]
Great!
