### ISSUE TITLE
Getting a name when using a global name inside a local scope without passing it in.

### ISSUE THREAD

**Issue by justanr** [scopatz/xonsh#70]
I'm brand new to xonsh and it's pretty freaking awesome. However, I've noticed something odd when attempting to use an imported class (haven't tried it with other things). All this code is run inside xonsh:

```python
from markovchains.chain import MarkovChain

def make_chain(corpus):
    return MarkovChain.from_corpus(corpus.split(), order=2)
```

Simple enough.

````
make_chain("mary had a little lamb")
Traceback (most recent call last):
  File "/home/justanr/.virtualenvs/xonch/lib/python3.4/site-packages/xonsh/shell.py", line 109, in default
    self.execer.exec(code, mode='single', glbs=None, locs=self.ctx)
  File "/home/justanr/.virtualenvs/xonch/lib/python3.4/site-packages/xonsh/execer.py", line 110, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
  File "<xonsh-code>", line 258, in make_chain
NameError: name 'MarkovChain' is not defined
```

But...

```
MarkovChain.from_corups(corpus="mary had a little lamb".split(), order=2)
# output: MarkovChain(order=2)
```

It seems like my imported class is in a quantum state of defined and not defined, only collapsing once xonsh tries to invoke it.

Any ideas what could be going on?

Relevant (Maybe?) details:

* Python 3.4.0
* xonsh 0.1.2
* Inside of venv
* Installed by pip
* No xonshrc
* [markovchains repo](https://github.com/justanr/markov-chains) -- in case something here is causing it

**Comment by scopatz** [comment]
Ahh wow. Ok this is a serious scope issue.  Thanks for reporting @justanr! I think this might be happening because we are evaluating in a local scope, rather than a global one.  It might be a one line fix.

**Comment by scopatz** [comment]
Hi @justanr - the current master (d9b3cc3) should resolve this issue.  Please confirm and let us know!

**Comment by justanr** [comment]
Alright, I'll clone it down when I get home. I figured local execution was the problem, but I was being ushered out the door when I reported this. Allegedly, some things are more important than bug reports.

**Comment by justanr** [comment]
I'm gonna play with it more, but it seems fixed.

**Comment by scopatz** [comment]
Ok! Please close the issue when you feel it has been addressed.

**Comment by justanr** [comment]
Closed.
