### ISSUE TITLE
[Feature request] Make $[cmd] return cmd's returncode instead of None

### ISSUE THREAD

**Issue by piotrjurkiewicz** [scopatz/xonsh#701]
Now the only way to check command returncode is to access it via `__xonsh_history__.rtns[-1]`. I think that there is a need for a simpler scheme for doing this. `$?` environment variable was proposed, but was rejected as ugly and limited.

I've came up with an idea to use `$[cmd]` for accessing returncodes. 

Now `$[cmd]` construct always returns `None`:

``` python
>>> x = $[/usr/bin/true], $[/usr/bin/false]
>>> x
(None, None)
```

I propose to make it return command returncode instead of `None`:

``` python
>>> x = $[/usr/bin/true], $[/usr/bin/false]
>>> x
(0, 1)
```
This approach isn't more complicated to use than `$?` and, moreover, is fairly more extensible. For example you can assign returncodes of many commands to a tuple, like above.

Or you can use it in loops:

``` python
def wait_until_google_responds():
    while $[ping -c 1 google.com] != 0:
        sleep 1
```

Or you can use it in comprehensions:

``` python
# Ping all neighbors from ARP table and store whether each of them responds in a dict
>>> neigh_responds = {address: $[ping -c 1 @(address)] == 0 for address in $(ip neigh | cut -f1 -d' ').splitlines()}
>>> neigh_responds
{'192.168.48.1': False, '192.168.48.2': False, '192.168.48.3': True}
# Calculate fraction of neighbors which responds
>>> sum(neigh_responds.values()) / len(neigh_responds)
0.3333333333333333
```

**Comment by adqm** [comment]
I like it!  I have actually written the code to do this a long time ago (and to hide the returncode when the command isn't explicitly invoked with `$[...]` so that the command line doesn't always display the return code).  I can try to find it and put in a PR tonight.

**Comment by scopatz** [comment]
Hi @piotrjurkiewicz! Thanks a million for this feature request.  I am in full support for something like this.  I haven't looked at @adqm's PR yet, and maybe that is a better place to have this discussion.  However, my initial impression is that it would be best to have new syntax for this rather than overloading `$[]` to sometimes return the return code and sometimes not.  Maybe `?[]`

**Comment by scopatz** [comment]
@piotrjurkiewicz - does the current master now satisfy your use case?

**Comment by piotrjurkiewicz** [comment]
Yes, it covers pretty much all use cases I can think about. However, I still think that `?()` syntax would be better, for the reasons I stated [here](https://github.com/scopatz/xonsh/pull/702#issuecomment-191500983).

**Comment by scopatz** [comment]
Ok. Well feel free to close this issue.  If a compelling reason comes up to change it, we can certainly do so if we need to.
