### ISSUE TITLE
Long line dots

### ISSUE THREAD

**Issue by gforsyth** [scopatz/xonsh#703]
With the new dots continuation in the `prompt_toolkit` shell, the dots are drawn whenever a newline is created, but also when a long line in a tiny terminal wraps around.  There's no `\n` in the picture below.

![2016-02-25-174319_440x237_escrotum](https://cloud.githubusercontent.com/assets/3596999/13337114/babb765e-dbe7-11e5-8753-bc38872b66a4.png)

I don't think this is necessarily a problem, I actually kind of like it, but I wanted to mention it to see if other folks have cases where it will cause trouble.

**Comment by melund** [comment]
So do I. I don't know if it will be a problem that I can't see if it is a newline or a wrap-around. I will have to use it a little more to get a feeling for it. 

Is there a way to change the dots depending on if the line wraps or not? Sort of like this....

```` 
mel@home ~ $ for i in range(10):
...........⏎    print('this is very long line that wraps around
........... to the next line)
```

**Comment by melund** [comment]
It seems like the output is over writing some of the previous prompt. 

![image](https://cloud.githubusercontent.com/assets/1038978/13353473/f6578fec-dc94-11e5-8fe7-681972bb5104.png)

When I execute the last line in the previous prompt is overwritten by the output

![image](https://cloud.githubusercontent.com/assets/1038978/13353525/563961f6-dc95-11e5-8924-d568510081ae.png)

**Comment by gforsyth** [comment]
Hey @melund -- I can duplicate the line overwriting in `xonsh` and also in plain `prompt_toolkit` so I think this is a PTK bug.  I'll report it there.

**Comment by scopatz** [comment]
Thanks for reporting @gforsyth. I have also noticed some strange behaviour with long prompts, long input, and multiline.  I agree that this is almost certainly a PTK issue and so that is the right place to report it.

**Comment by gforsyth** [comment]
Hey @melund, I think this has been resolved by jonathanslenders/python-prompt-toolkit@0c3b0c7 and @jonathanslenders is going to push out a new release shortly.

**Comment by melund** [comment]
That was fast :)

**Comment by scopatz** [comment]
Nice!

**Comment by melund** [comment]
It also fixed it for me:

![image](https://cloud.githubusercontent.com/assets/1038978/13371960/b7be6c34-dd33-11e5-8291-1d12b39b93c3.png)

**Comment by scopatz** [comment]
Great! Feel free to close @gforsyth
