### ISSUE TITLE
Environment section in Wizard looks weird

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#707]
It looks like the environment section of the wizard is formatted wrong. It looks like it is printing the line feed characters. 

![image](https://cloud.githubusercontent.com/assets/1038978/13364317/723eba02-dcce-11e5-9f2c-89dfd43b31f5.png)

The closest I could get to the problem is that this section is beeing set by the `YesNo` node. This node sets the entire text into the PROMPT variable. .
https://github.com/scopatz/xonsh/blob/f51227e90ad1144ff842e03c235ea5b0dbbb2ee3/xonsh/wizard.py#L529

**Comment by scopatz** [comment]
Thanks for reporting @melund. I think this is an issue with the multiline prompt and having newlines in the prompt...maybe.  The fix is to just have a shorter prompt and make the first a message.  I'll try to fix it tomorrow

**Comment by melund** [comment]
@scopatz .. The first part of the environment section looks fine now. But there is a similar problem when setting the individual environment variables: 

![image](https://cloud.githubusercontent.com/assets/1038978/13375579/d2d0f54e-dda3-11e5-8981-03c59c66091a.png)

**Comment by scopatz** [comment]
Hi @melund - OK, I think I have fixed this issue too now.

**Comment by melund** [comment]
Looks good. 
![image](https://cloud.githubusercontent.com/assets/1038978/13376006/624ecd9e-ddaf-11e5-9955-8dcc688abf9f.png)

An unrelated question. What is ANSICON and why the value '79x10000'???

**Comment by scopatz** [comment]
ANSICON seems to be [a library](https://github.com/adoxa/ansicon) that allows usage of ANSI escape sequences in Windows terminal emulators.  If the envvar is present, then you can use these escape sequences.  Right now it is just used to set the title.  This should probably not be configurable.
