### ISSUE TITLE
utf-8 on windows

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#708]
This not a bug but more a question. What are people's experience with utf-8, xonsh on windows? It should be possible to make it work even in the default windows terminal. But it seems a bit complex 

http://stackoverflow.com/questions/878972/windows-cmd-encoding-change-causes-python-crash/3259271

I mostly use cmder/conemu (which supports unicode) but it doesn't work with xonsh. I saw that @BYK had some Unicode stuff working in conemu on windows, so maybe you can share your secrets...

**Comment by BYK** [comment]
I've been using Xonsh, ConEmu and UTF-8 for a long time without issues. Didn't even know if that was thing. I'm using Meslo LG fonts in conjugation with PowerLine Symbols font for the unicode characters I'm using. Here's my `ConEmu.xml` file if it helps: https://gist.github.com/BYK/39a9109a29755da25dd5

**Comment by melund** [comment]
Yes. Setting `chcp 65001` or `chcp utf-8` in the environment tab actually did the trick. The problem was that I was trying to show characters that were not in the default fonts. I only realized this later. 

Even changing the fonts didn't do the trick at first. Turned out that I couldn't set the 'unicode ranges' in the ConEmu settings GUI. 

![image](https://cloud.githubusercontent.com/assets/1038978/13375155/b149e4f4-dd98-11e5-861a-470bb6b3badb.png)

Maybe a bug? However, when I changed range directly in the XML files, then it started to work. 

Getting it to work work in the default cmd.exe terminal would be great, but it may not be easy...

**Comment by melund** [comment]
Maybe we could integrate something like this. I will test if it works with xonsh
https://github.com/Drekin/win-unicode-console/tree/development

**Comment by melund** [comment]
I just figured how to get bold fonts in ConEmu by using the 'Extended fonts' setting. It sacrifices a few background colors to trigger bold fonts or italic fonts. 
´´´ 
$FORMATTER_DICT['CONEMU_BOLD'] = '{bg#110000}'
´´´
Maybe we should put together some tips/tricks documentation on how to use ConEmu with xonsh....

**Comment by melund** [comment]
@BYK . I just tried the package [win_unicode_console](https://pypi.python.org/pypi/win_unicode_console). It fixes the whole utf-8 problem on windows.

Adding ´win_unicode_console.enable()´ to premain and ´win_unicode_console.disable()´ to post main just fixes all the unicode issues. No need to change the code page in the console or any other tricks. It also works with ConEmu without manually setting anything. 

@scopatz ... Could we integrate something like this, or maybe just add it as an option dependency on conda.

**Comment by scopatz** [comment]
I think having better default support would be awesome.  Please open a PR! I am happy with either an optional dependency or with an integration. It seems like it might evolve further and so an optional dependency makes more sense to me.

**Comment by melund** [comment]
I have made a PR for this #714, where win_unicode_console is an optional dependency.

**Comment by BYK** [comment]
@melund - would you be interested in joining the #xonsh IRC channel  on OFTC so we can talk more on the UTF-8 stuff?

**Comment by melund** [comment]
I haven't used IRC in ages. Timing is going to be tricky. I always use the play with xonsh as procrastination, so I never know when I am on.

**Comment by BYK** [comment]
@melund if you prefer Gitter, we can use that too :)
