### ISSUE TITLE
Replace readline and rlcompleter

### ISSUE THREAD

**Issue by TheJJ** [scopatz/xonsh#71]
In order to massively boost the autocompletion awesomeness, the standard readline completion used in bash and rlcompleter has to be replaced by something more sophisticated.

I can once again point at zsh providing a grid of possible choices, even showing documentation for available options temporarily.

An idea would be creating this grid dynamically using ncurses-stuff, without ever using the rlcompleter.

This would also solve the completion for something like:
```python
$ import math
$ math.<tab>
```

**Comment by scopatz** [comment]
I would love for there to be another front-end, ideally an urwid one.  This is even in the docs (http://xonsh.org/todo.html#urwid-based-command-prompt) ~_~.   I think that this should be parallel to the readline interface though. Folks should be able to use xonsh with a minimum of dependencies (python and ply).  Pull requests always welcome!

**Comment by blink1073** [comment]
This may be of interest for an alternative: https://github.com/davidhalter/jedi/blob/master/jedi/utils.py#L17

**Comment by scopatz** [comment]
Cool, thanks @blink1073

**Comment by gforsyth** [comment]
I'm going to go ahead and close this -- we have pretty robust completion in the `prompt_toolkit` frontend and we can't use ncurses since it isn't windows compatible.
