### ISSUE TITLE
Semicolon-Separated Commands Fail with SyntaxError

### ISSUE THREAD

**Issue by moigagoo** [scopatz/xonsh#710]
For example:
```
$ hg pull; hg up
           
  File "<string>", line None
SyntaxError: <xonsh-code>:1:3: ('code: pull',)
```

After I type `hg up; hg pull` and press Enter, a blank line is started. Another Enter press leads to the error.

I'm on Mac OS X El Capitan.

**Comment by BYK** [comment]
Same here for some time now.

**Comment by gforsyth** [comment]
Did this ever work?  `hg up; hgpull` will be in subprocess mode where `;` don't have particular meaning (I don't think).  If you force Python mode this works: `$[hg up]; $[hg pull]` which is a little silly.  Do you need semicolon support, or would you be ok with the soon-to-be-merged `and` operator in #672?  

On that PR the following works for me `git fetch and git merge`

**Comment by scopatz** [comment]
I can confirm the failure as well.  I actually expected this to work.  There are even tests for [cases like this](https://github.com/scopatz/xonsh/blob/master/tests/test_tools.py#L147) that pass in the test suite but fail at the command line. I think that this is a legitimate bug.

**Comment by scopatz** [comment]
After a a git bisect, the change that broke this behaviour is 97d8d4c69ec0dd89bef997397d5c5bb54011d390

**Comment by scopatz** [comment]
I had remembered this was working before :)

**Comment by scopatz** [comment]
Though, to be fair, I have no idea why this would rely on double wrapping an @adqm was right to remove it.  Note, that the code I used to test this was the equivalent `echo i; echo j`

**Comment by moigagoo** [comment]
@gforsyth Semicolons should work. I remember somewhere Anthony proposed it as a workaround for not implemented `&&`. `and` is great and I'm going to use it, but I think semicolons should be supported as well to make it easier to switch from bash.

Also, @scopatz confirmed it's a legitimate bug :-)

**Comment by adqm** [comment]
I just put in a PR that I think should fix.  The problem is that here we call the wrapping twice, but on different substrings.

So when we hit the `echo j` in `echo i; echo j`, we have already wrapped the first piece (we have `$[echo i]; echo j` at that point).  The original check would give up there, but this update should work.

**Comment by scopatz** [comment]
Hi @moigagoo, @adqm's fix has been pulled into master. Would you mind testing it and then closing this issue? Thanks!

**Comment by moigagoo** [comment]
@scopatz Sure, I'll test it as soon as I'm near my Mac, which is tomorrow.

**Comment by BYK** [comment]
@scopatz - I pulled the latest master and tried. Seems to be working now :)

**Comment by scopatz** [comment]
@BYK wooho! @moigagoo, thanks!

**Comment by moigagoo** [comment]
@scopatz @BYK Confirmed! Closing the issue. Thanks!
