### ISSUE TITLE
Consider creating a Gitter.im room

### ISSUE THREAD

**Issue by BYK** [scopatz/xonsh#722]
We have an IRC channel on OFTC but it is not very active. It may be good to have a Gitter.im room since people can use it easily from the web using their GitHub accounts.

**Comment by scopatz** [comment]
Hi @BYK - I think this could be good.  I have a hard time using IRC personally typically for whatever reason. I would be willing to try something else.

**Comment by gforsyth** [comment]
Hey @scopatz and @BYK -- I can set this up.  Give me a few minutes.

**Comment by gforsyth** [comment]
@BYK -- good to go now: [![Gitter](https://badges.gitter.im/scopatz/xonsh.svg)](https://gitter.im/scopatz/xonsh?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by BYK** [comment]
Yay, thanks!
