### ISSUE TITLE
Headless Shell

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#724]
I think it is a good idea to have a shell class that is strictly for running code and does not accept input from the user. This could avoid startup time from loading readline, ptk, the completer, history, etc.

**Comment by scopatz** [comment]
Naturally, this would then be used as the implementation of `xonsh -c`

**Comment by adqm** [comment]
I'm happy to give this a go.  I think all the pieces are probably in place, so should just be a matter of rearranging things, I expect...

**Comment by scopatz** [comment]
Sure thing! Have at :)

**Comment by adqm** [comment]
Interesting thing is that (at least on my machine), removing the import for readline doesn't speed things up too much.  There are some other things going on here that are affecting startup times.  As of right now, running `$ xonsh -c echo "hi"`:

* headless takes about .9 seconds
* readline takes about .9 seconds
* prompt_toolkit takes about 1.4 seconds

I'm looking into profiling now, to try to see where the biggest timesinks are, and then we can see whether there isn't a way to avoid those when we aren't going to be running interactively.

**Comment by scopatz** [comment]
Interesting... Thanks for investigating!
