### ISSUE TITLE
How to set xonsh as the default shell

### ISSUE THREAD

**Issue by Siecje** [scopatz/xonsh#730]
I just installed xonsh on a fresh debian install.

```shell
$ sudo apt-get install python3-pip
$ sudo pip3 install xonsh
$ chsh -s /usr/local/bin/xonsh
Password: 
chsh: /usr/local/bin/xonsh is an invalid shell
$ xonsh --version
('xonsh/0.2.6',)
```

**Comment by adqm** [comment]
You will need to add xonsh to the list of acceptable shells by adding its full path to the `/etc/shells` file before `chsh` will let you set it as the default.

Hope this helps!

**Comment by Siecje** [comment]
When you install xonsh can that file be modified? I didn't have to modify ```/etc/shells``` after I installed fish.

I installed via pip if that matters.

I also tried finding how to do it in the docs. Would the installation page be a good place to explain how to set xonsh as the default shell?

**Comment by gforsyth** [comment]
Yes and yes. The docs can use a little more explanation on this and we'll have the installer add xonsh to the shell list. Let us know if there are other config issues, docs can always be improved!

**Comment by adqm** [comment]
fish also doesn't seem to add itself to `/etc/shells` when installing from source (only through package managers).  See [this question in their FAQ](https://fishshell.com/docs/current/faq.html#faq-default).

I guess I need to get on that whole debian packaging thing...It may also be possible for us to automate this step through `setup.py`, but for some reason that makes me nervous.  At the least, I agree that we should definitely add this to the documentation.

**Comment by scopatz** [comment]
I tend to agree with you @adqm that this is something that should be done in the packages.  The trick with setup.py is that we'll need to check if it is being installed by pip with root permissions.

**Comment by gforsyth** [comment]
That was my thought. Or a check + a prompt to elevate privileges?

**Comment by Siecje** [comment]
There are now instructions on the Linux Guide page. http://xon.sh/linux.html

**Comment by scopatz** [comment]
Feel free to close this then @Siecje!
