### ISSUE TITLE
globpath seem not that useful

### ISSUE THREAD

**Issue by Carreau** [scopatz/xonsh#733]
found here, https://github.com/scopatz/xonsh/blob/master/xonsh/built_ins.py#L276-L282

the code is dublicate of `iglobpath`, but using `glob` instead of `iglob`, which seems weird as glob is just convenient wrapper that consume `iglob`:

```python
def glob(pathname, *, recursive=False):
    """Return a list of paths matching a pathname pattern.

    The pattern may contain simple shell-style wildcards a la
    fnmatch. However, unlike fnmatch, filenames starting with a
    dot are special cases that are not matched by '*' and '?'
    patterns.

    If recursive is true, the pattern '**' will match any files and
    zero or more directories and subdirectories.
    """
    return list(iglob(pathname, recursive=recursive))
```

Plus is seem to only be used there: `builtins.__xonsh_glob__ = globpath`.

So it might be useful to deprecate `globpath` or investigate making it only a wrapper around iglobpath if ever the logic in iglobpath is ever extended.

**Comment by scopatz** [comment]
Thanks for bringing this up @Carreau. I think it is best to continue on with this from your PR

**Comment by scopatz** [comment]
@Carreau is this closable now?

**Comment by Carreau** [comment]
sure.
