### ISSUE TITLE
Hack the color style on windows

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#746]
Is there a quick hack to change all the blue colors to cyan in a style?

On the default windows terminial blues is very hard to read and should be avoided. 

![image](https://cloud.githubusercontent.com/assets/1038978/13876025/a12f0950-ed01-11e5-9fab-0e0a188184db.png)

It is not an issue if you use something like ConEmu, but most new windows users would be starting out in cmd.exe. So we may want to make a hack to convert all blue colors to cyan. Do you have any good ideas how I could do this?

**Comment by scopatz** [comment]
is there any reliable way to tell what terminal is being used in Windows?

**Comment by scopatz** [comment]
we could always change the default style for cmd.exe

**Comment by melund** [comment]
Well. ConEmu (and also Cmder) sets some environment variables. So we can now if they are used. I don't now with other terminal emulators for windows (if there are any). I will look.

**Comment by melund** [comment]
It is sometimes hard to see what color will be mapped to blue in the terminal. That is handled by by ColorLookupTable class in prompt_toolkit: 
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/win32_output.py#L462

I imagined to loop over all colors in a style and replace all colors that maps to blue. But maybe there is a better option.

**Comment by scopatz** [comment]
Well my thought was to just change the default color map (from `'default'`) to something more readable when in cmd.exe

**Comment by scopatz** [comment]
I think that is better than trying to loop over all color names.

**Comment by melund** [comment]
Well. Maybe . But none of the existing styles are really good. We could add a new one 'default_win' style, and then enable it when cmd.exe is used. But that is kind of rude to unless we can make sure people have not asked for any specific style.

My original thought was to have a setting to replace certain of the 16 colors with other colors. That way I could still switch between existing styles while avoiding the colors that are unreadable. 

But I think I will start with your advice and create a new style.

**Comment by melund** [comment]
@scopatz . I ended up doing something else instead. #749

**Comment by scopatz** [comment]
Sounds good to me :)
