### ISSUE TITLE
Captured execution seems to be broken

### ISSUE THREAD

**Issue by BYK** [scopatz/xonsh#759]
I've been trying to understand if this is just me or the command I run but it looks like a legit problem:

When I run `$(cmd /c help)` or `!(cmd /c help)` the prompt gets stuck until I hit `^C`. The bracketed counterparts seems to be working properly though (`!()` and `![]`) so I suspect this has todo something with stdout capturing.

I get the command output once I get the prompt unstuck.

I'm on latest master (e245bc578ad766afc06f96e6c1253b03822ad573) and xonfig is as follows:
```
+------------------+-------+
| xonsh            | 0.2.7 |
| Python           | 3.5.1 |
| PLY              | 3.6   |
| have readline    | True  |
| prompt toolkit   | 0.60  |
| pygments         | 2.1.3 |
| on posix         | False |
| on linux         | False |
| on arch          | False |
| on windows       | True  |
| on mac           | False |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by scopatz** [comment]
Hmm weird.  stdout capturing should not be possible on Windows.  What is the value of `$XONSH_STORE_STDOUT`?

**Comment by scopatz** [comment]
Oh sorry, I am confusing terms.  There is a difference between storing stdout and capturing it.  You are 100% right that capture should totally work.

**Comment by melund** [comment]
I can also confirm this.

**Comment by scopatz** [comment]
On master even @melund?

**Comment by melund** [comment]
@scopatz .. Yes on master. It just hangs until I press ctrl-c, then it returns and everything is fine. 

It doesn't happen with simple commands like `!(echo 2)`

**Comment by melund** [comment]
@scopatz 

I investigated this a little further. It stalls in https://github.com/scopatz/xonsh/blob/master/xonsh/jobs.py#L42 where it is waiting for the subproc to finish. 

I get the same behaviour if I run the command in python: 

```
from subprocess import Popen, PIPE
cmd = ['C:\\Windows\\system32\\cmd.exe', '/C', 'help']
stdin = 0
uninew = False
proc = Popen(cmd, universal_newlines=uninew, stdin=0, stdout=PIPE, stderr=PIPE)
```
It doesn't just finish by it self, i.e. `proc.wait()` never returns

However, if I call `proc.communicate()` then it runs fine. I think the problem is related to the warning in the python docs https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait

> Note This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.

**Comment by melund** [comment]
I tried a very simple fix; #798

**Comment by scopatz** [comment]
Is this closeable now?

**Comment by melund** [comment]
Yes.

**Comment by melund** [comment]
Well. Maybe it should be up to @BYK to decide ;)

**Comment by BYK** [comment]
It is resolved ☺️
