### ISSUE TITLE
CTRL-C during config wizard results in loss of input to terminal

### ISSUE THREAD

**Issue by rsyring** [scopatz/xonsh#770]
Running bash in a Terminator window, when I first started xonsh, I was asked if I wanted to run the config wizard.  I chose yes, but then eventually decided I didn't want to finish, so I hit CTRL-C.  This eventually got me back to bash, but when I pressed keys, the keys didn't show up in the terminal windows.  I had to close the window and open a new one.

**Comment by scopatz** [comment]
Thanks for reporting @rsyring.  I thought that I had fixed this issue.  Do you recall which version of xonsh this was one? Does it still occur?  Sorry for taking so long to respond!

**Comment by rsyring** [comment]
I just updated to master and tried it and the bug is still present.

**Comment by scopatz** [comment]
Thanks for letting us know @rsyring.

**Comment by scopatz** [comment]
See #825
