### ISSUE TITLE
Problem with captured subprocess on Windows cmd

### ISSUE THREAD

**Issue by michelepagot** [scopatz/xonsh#788]
xonsh 0.2.6

It works like 
`User@User-PC ~ $ ping www.google.com

Esecuzione di Ping www.google.com [172.217.19.68] con 32 byte di dati:
Risposta da 172.217.19.68: byte=32 durata=193ms TTL=54
Risposta da 172.217.19.68: byte=32 durata=56ms TTL=54
Risposta da 172.217.19.68: byte=32 durata=25ms TTL=54
Risposta da 172.217.19.68: byte=32 durata=25ms TTL=54

Statistiche Ping per 172.217.19.68:
    Pacchetti: Trasmessi = 4, Ricevuti = 4,
    Persi = 0 (0% persi),
Tempo approssimativo percorsi andata/ritorno in millisecondi:
    Minimo = 25ms, Massimo =  193ms, Medio =  74ms`

And like 
`User@User-PC ~ $ $(ping www.google.com)
'\nEsecuzione di Ping www.google.com [172.217.19.68] con 32 byte di dati:\nRisposta da 172.217.19.68: byte=32 durata=26ms TTL=54\nRisposta da 172.217.19.68: byte=32 durata=27ms TTL=54\nRisposta da 172.217.19.68: byte=32 durata=27ms TTL=54\nRisposta da 172.217.19.68: byte=32 durata=27ms TTL=54\n\nStatistiche Ping per 172.217.19.68:\n    Pacchetti: Trasmessi = 4, Ricevuti = 4, \n    Persi = 0 (0% persi),\nTempo approssimativo percorsi andata/ritorno in millisecondi:\n    Minimo = 26ms, Massimo =  27ms, Medio =  26ms\n'`

But ....
`User@User-PC ~ $ !(ping www.google.com)

  File "<string>", line None
SyntaxError: <xonsh-code>:1:0: !`

**Comment by gforsyth** [comment]
Hi @michelepagot , can you try installing `0.2.7`?  I believe this issue is resolved in the latest release.

```console
gil@bad_cat ~/git/xonsh HEAD $ !(ping -c 4 google.com)
CompletedCommand(stdin=None, stdout='PING google.com (172.217.0.174) 56(84) bytes of data.\n64 bytes from yyz08s10-in-f14.1e100.net (172.217.0.174): icmp_seq=1 ttl=53 time=30.0 ms\n64 bytes from yyz08s10-in-f14.1e100.net (172.217.0.174): icmp_seq=2 ttl=53 time=37.6 ms\n64 bytes from yyz08s10-in-f14.1e100.net (172.217.0.174): icmp_seq=3 ttl=53 time=30.6 ms\n64 bytes from yyz08s10-in-f14.1e100.net (172.217.0.174): icmp_seq=4 ttl=53 time=30.1 ms\n\n--- google.com ping statistics ---\n4 packets transmitted, 4 received, 0% packet loss, time 3004ms\nrtt min/avg/max/mdev = 30.050/32.132/37.687/3.217 ms\n', stderr='', pid=7377, returncode=0, args=['ping', '-c', '4', 'google.com'], alias=None, stdin_redirect=None, stdout_redirect=None, stderr_redirect=None, timestamp=(1460222005.14806, 1460222008.231077))
```

**Comment by michelepagot** [comment]
I give a try to 0.2.7 on WinPython-64bit-3.5.1.2 ... by downloading https://codeload.github.com/scopatz/xonsh/zip/master and "python setup.py install"
Everything fine in installation process but then:
C:\>xonsh
failed to create process.

**Comment by scopatz** [comment]
Seems like this is a bug in pip or setuptools or something.  Here is a potential fix: http://stackoverflow.com/a/35246810/2312428 Let us know if you find a fix that works.

**Comment by melund** [comment]
@michelepagot If you are willing to try the anaconda python distribution, then you can install the latest master by typing this at the command prompt:

`conda install -c xonsh/channel/dev xonsh`

**Comment by michelepagot** [comment]
xonsh 0.2.7 from conda is fine

[michele_test_drive] C:\Users\Users>xonsh --version
('xonsh/0.2.7',)

User@User-PC  ~ $ ping www.google.com

Pinging www.google.com [216.58.212.68] with 32 bytes of data:
Reply from 216.58.212.68: bytes=32 time=25ms TTL=52
Reply from 216.58.212.68: bytes=32 time=23ms TTL=52
Reply from 216.58.212.68: bytes=32 time=24ms TTL=52
Reply from 216.58.212.68: bytes=32 time=24ms TTL=52

Ping statistics for 216.58.212.68:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 23ms, Maximum = 25ms, Average = 24ms

User@User-PC  ~ $ $(ping www.google.com)
'\nPinging www.google.com [216.58.212.68] with 32 bytes of data:\nReply from 216.58.212.68: bytes=32 time=93ms TTL=52\nReply from 216.58.212.68: bytes=32 time=98ms TTL=52\nReply from 216.58.212.68: bytes=32 time=85ms TTL=52\nReply from 216.58.212.68: bytes=32 time=112ms TTL=52\n\nPing statistics for 216.58.212.68:\n    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),\nApproximate round trip times in milli-seconds:\n    Minimum = 85ms, Maximum = 112ms, Average = 97ms\n'

User@User-PC ~ $ !(ping www.google.com)
CompletedCommand(stdin=None, stdout='\nPinging www.google.com [216.58.212.68] with 32 bytes of data:\nReply from 216.58.212.68: bytes=32 time=24ms TTL=52\nReply from 216.58.212.68: bytes=32 time=23ms TTL=52\nReply from 216.58.212.68: bytes=32 time=69ms TTL=52\nReply from 216.58.212.68: bytes=32 time=23ms TTL=52\n\nPing statistics for 216.58.212.68:\n    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),\nApproximate round trip times in milli-seconds:\n    Minimum = 23ms, Maximum = 69ms, Average = 34ms\n', stderr='', pid=3492, returncode=0, args=['ping', 'www.google.com'], alias=None, stdin_redirect=None, stdout_redirect=None, stderr_redirect=None, timestamp=(1460473051.2684047, 1460473054.3284047))

**Comment by scopatz** [comment]
Feel free to close this then @michelepagot
