### ISSUE TITLE
Add an example .xonshrc to the docs or repo

### ISSUE THREAD

**Issue by naufraghi** [scopatz/xonsh#79]
I tryed creating my multiplatform `.xonshrc` but perhaps I failed understending the syntax is allowed inside (weird errors defining e function inside it).

I think an example `.xonshrc` with some best practices (like putting in a pure python module some utility functions? Where?) could be very usefull.

**Comment by scopatz** [comment]
This is a good idea.  I think I just fixed the function bug you are referring to.  If you keep seeing weird errors, please report them!

**Comment by scopatz** [comment]
Thanks for the suggestion @naufraghi. I have added this to master.
