### ISSUE TITLE
Cannot break out from infinite loops

### ISSUE THREAD

**Issue by BYK** [scopatz/xonsh#799]
If you ever type

```py
while True:
    print("Hello!")
```

It is impossible to break out from the loop (say using ^C). The only way is to kill the Python process. This is not a good property for a shell :)

**Comment by lucasicf** [comment]
What system, terminal and xonsh version?

Mine worked with ^C successfully:
Fedora Linux 22 x86_64
Konsole/KDE
xonsh 0.2.3

**Comment by BYK** [comment]
It was on a friends computer. He installed from latest pip so guessing it was 0.2.7 on an Ubuntu x64 workstation.

**Comment by melund** [comment]
It works for me. I am working from master. 
``` 
mel@ANYBODY-MEL2 ~/Documents/xonsh                                                                             (master)
$ xonfig
+------------------+-------+
| xonsh            | 0.2.7 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | 0.60  |
| pygments         | 2.1.3 |
| on posix         | False |
| on linux         | False |
| on arch          | False |
| on windows       | True  |
| on mac           | False |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+
``` 
prompt_toolkit is also run from master

**Comment by scopatz** [comment]
Hi @BYK - I am also not able to reproduce this with either readline or prompt-toolkit (on master).  Can you get your friend to run `xonfig`, please?  Maybe this is a v0.2.7 issue that has since been fixed on master.

**Comment by BYK** [comment]
It is possible. He was using readline (since he just installed xonsh through pip and started going). Let's wait and see until 0.3.0 is released then :)

**Comment by scopatz** [comment]
Alright then :)
