### ISSUE TITLE
Add auto-indentation on multiline function/loops/if statements

### ISSUE THREAD

**Issue by eyalzek** [scopatz/xonsh#80]
Starting a multineline command, ie:
   if True:

should preferably start the new line indented accordingly, currently it requires me to manually enter spaces which confused me quite a bit at first because my multiline commands just didn't go through (until I realized my mistake).

**Comment by scopatz** [comment]
You can hit "Shift-Tab" to indent as well.  I am not a huge fan of auto-indentation, personally.  If someone wanted to implement it with an environment variable to turn it on/off, I would happily accept that PR.

**Comment by eyalzek** [comment]
Shiftt+Tab works well, I suggest adding it to the documentation somewhere in the meantime :)

**Comment by scopatz** [comment]
Yup @eyalzek - If you would like to add this to the docs via a PR, I would be super grateful!

**Comment by eyalzek** [comment]
https://github.com/scopatz/xonsh/pull/104
