### ISSUE TITLE
Tab completion doesn't work for nested attributes/objects in python mode

### ISSUE THREAD

**Issue by eyalzek** [scopatz/xonsh#81]
For example, after importing a module, tab completion is not available for it's methods:
$ import os
$ os.

Clicking tab in the above scenario won't offer completion.
Also happens for class attributes, define a class:
class A:
    def __init__(self, a):
        self.a = a

initialize an instance:
$ a = A(1)
$ a.
Clicking tab in the above scenario won't offer completion.

**Comment by scopatz** [comment]
Yes, this should happen! Pull requests welcome.

**Comment by scopatz** [comment]
I believe that this has now been added as of v0.1.5

**Comment by scopatz** [comment]
Would you mind checking @eyalzek?

**Comment by eyalzek** [comment]
The above use cases seem to be working very well! I'll give it a further look when I get the chance.

Thanks!

**Comment by eyalzek** [comment]
Still not getting tab completion for modules, for example; typing:
import 
and clicking tab, won't list available modules. Not sure if that's expected.

**Comment by scopatz** [comment]
module import completion is not yet implemented.  Can you make a separate issue for that?

**Comment by eyalzek** [comment]
No problem
