### ISSUE TITLE
How do you get the status of the previous command?

### ISSUE THREAD

**Issue by Siecje** [scopatz/xonsh#814]
Is this currently possible?

fish uses ```$status``` other shells use ```$!```

**Comment by scopatz** [comment]
By status, I assume that you mean the return code?  In this case it is `__xonsh_history__.rtns[-1]`

**Comment by Siecje** [comment]
Yes! I couldn't find it in the docs.

**Comment by scopatz** [comment]
Yeah, we probably need to add this more explicitly to the docs, but there is a whole page dedicated to history: http://xon.sh/tutorial_hist.html  Maybe we need to add this to the translation guide: http://xon.sh/bash_to_xsh.html

**Comment by scopatz** [comment]
See #823

**Comment by scopatz** [comment]
Closing on merger on #823.  Please reopen if you feel it wasn't addressed.
