### ISSUE TITLE
source-bash return code will always be 0

### ISSUE THREAD

**Issue by Siecje** [scopatz/xonsh#817]
Even if the file doesn't exist.

**Comment by scopatz** [comment]
Thanks a ton for noticing this and reporting it @Siecje!  This is definitely a bug / overlooked feature. Mea culpa.

**Comment by melund** [comment]
We will keep it until it has been completely fixed..

**Comment by scopatz** [comment]
@Siecje - could you please test the current master and close this issue? thanks!

**Comment by Siecje** [comment]
I just tested it and it is fixed. Thanks!
