### ISSUE TITLE
Tab completion on __xonsh_shell__.shell. fails

### ISSUE THREAD

**Issue by scopatz** [scopatz/xonsh#826]
[See this mailing list discussion.](https://groups.google.com/d/msgid/xonsh/eb9b3b50-33c0-4652-949b-f042ec160f78%40googlegroups.com?utm_medium=email&utm_source=footer) I think that this is caused by the coloring code being updated and something in the completions not taking this into account.

**Comment by adqm** [comment]
Yes, interesting.  I use the readline shell and can confirm it isn't happening there (seems to be PTK only).

**Comment by scopatz** [comment]
I bet this is because the Shell class does some weird redirection stuff to its `shell` attr, which is an instance of one of the concrete shell types.
