### ISSUE TITLE
Processes don't go to background

### ISSUE THREAD

**Issue by zommerfelds** [scopatz/xonsh#827]
I believe that launching commands in the background is currently broken.
For example `sleep 5&` waits until the command finishes.

**Comment by scopatz** [comment]
Thanks for reporting. This is certainly a bug.

**Comment by GuillaumeLeclerc** [comment]
I'm facing this too. It's really problematic when I want to start GUI applications

**Comment by GuillaumeLeclerc** [comment]
The bug does not occur in the 2.7 release

**Comment by melund** [comment]
@scopatz and @GuillaumeLeclerc 

I also get this bug. Git bisect tells me it comes the from this PR with the and/or stuff for subproc mode ( https://github.com/scopatz/xonsh/pull/789 )  .. Probably the `&&` token (echo 1 && ehco 2)  is causing this

**Comment by scopatz** [comment]
I see this bug on master as well.  I think this is real and related to all of the job control stuff.

**Comment by melund** [comment]
@scopatz So I may be wrong. I was just thinking it was related to the parser and the addition og `&&`. It stopped working when the 'andor' branch was merged.

**Comment by melund** [comment]
@scopatz ... Ahh. I just saw the fixed in in #867, so then it was just a job control issue.

**Comment by gforsyth** [comment]
This is fixed on master -- please reopen if you still have issues!
