### ISSUE TITLE
`which` takes not `-v` on OS X

### ISSUE THREAD

**Issue by Carreau** [scopatz/xonsh#833]
Only, `-a` or `s`.  Though `which_version` (the `xonsh/alias.py` function) does invoke `which` with `-v`

This is untrue if you `brew install gnu-which --with-default-names`, which I guess not many people do... and we **could** determine that by looking as wether the `gnu`string is in the output of `which` without any arguments...

Woosh, with wish which was not [a witch](https://www.youtube.com/watch?v=zrzMhU_4m-g).

**Comment by gforsyth** [comment]
Hey @Carreau -- who are you that is so wise in the ways of science?

Which command line flag should be passed to `gnu-which` to trigger the version info?  I was browsing through the source and it looks like it _should_ accept `-v` or `-V` but I gather it doesn't?

**Comment by Carreau** [comment]
> Hey @Carreau -- who are you that is so wise in the ways of science?

A duck, I'm typing, so it's duck typing. 

> Which command line flag should be passed to gnu-which to trigger the version info? I was browsing through the source and it looks like it should accept -v or -V but I gather it doesn't?

I missexpressed myself:

default OSX `which` is **not** gnu-which. 
default OSX `which` has no flag to give its version. 
default OSX is stupid and kill kittens. 

OSX user **can** install gnu-witch, if they like, 
in which case `-v` is available. 

So we have 2 ways in from of us. One is a bridge made out of wood, and one out of stone.
  - ~~turn user into a newt~~
  - assume `-V` is never available on osx.
  - run `which` without argument, and check for `gnu` in output. 
    - if it is in output, then we are lucky, user has installed `gnu-which`
    - if it is not, then out of luck, we are on default OSX `which`, and we have no way of knowing its version. 

Does that make more sens ?

**Comment by gforsyth** [comment]
> default OSX is stupid and kill kittens. 
Burn it!

Got it.  I'll take a look at it.
