### ISSUE TITLE
Getting a backtrace on TAB completion on windows

### ISSUE THREAD

**Issue by justbur** [scopatz/xonsh#835]
This is with Conemu and Anaconda3 following the instructions on the website. I initially got prompt-toolkit v0.6 I think through the anaconda repo, and then I tried upgrading to v1.0 through pip. 

When I hit TAB to complete a path I sometimes get a backtrace like the following

```
$ cd src\Exception in thread Thread-37:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\prompt_toolkit-0.60-py3.5.egg\prompt_toolkit\interface.py", line 750, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "C:\Anaconda3\lib\site-packages\xonsh\ptk\completer.py", line 38, in get_completions
    self.reserve_space()
  File "C:\Anaconda3\lib\site-packages\xonsh\ptk\completer.py", line 52, in reserve_space
    r = builtins.__xonsh_env__.get('COMPLETIONS_MENU_ROWS')
AttributeError: 'NoneType' object has no attribute 'content_height'
```

It appears to happen any time I enter that reserve_space method, although I haven't confirmed that.

Happy to provide more information

**Comment by gforsyth** [comment]
Thanks for reporting @justbur! -- could you post the output of `xonfig`, please?

**Comment by justbur** [comment]
Yep, 
```
+------------------+-------+
| xonsh            | 0.2.6 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | 0.60  |
| pygments         | 2.1.3 |
| on posix         | False |
| on linux         | False |
| on arch          | False |
| on windows       | True  |
| on mac           | False |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+
```
I guess I lied about the version of prompt-toolkit. 0.60 is the default version I got from anaconda.

**Comment by gforsyth** [comment]
No worries!  I'm confused because to my knowledge there is no version `0.60` of `prompt_toolkit`...

**Comment by justbur** [comment]
This is what I see from conda

```
conda search prompt_toolkit
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
prompt_toolkit            *  0.61a                    py35_0  xonsh
```

**Comment by melund** [comment]
Try installing the development version  xonsh from the xonsh dev channel.  

`conda install -c xonsh/channel/dev xonsh `

That should also give you prompt_toolkit 1.0.0. If not just do

`conda install -c xonsh/channel/dev prompt_toolkit `

**Comment by gforsyth** [comment]
Thanks, @melund.  I couldn't remember the channel for that -- I think the docs also need updating to point to the `conda-forge` channel, too, no?

**Comment by justbur** [comment]
This is strange. I can see v1 on the anaconda website, but I can't get it to upgrade the package. @melund after trying those commands it's not getting v1 for me.

**Comment by melund** [comment]
Remove it with with `conda remove prompt_toolkit` first...

**Comment by melund** [comment]
Afterwards you can also try to install prompt-toolkit from the conda-forge channel

**Comment by justbur** [comment]
@melund That channel worked, and this problem seems fixed. Thanks!

**Comment by justbur** [comment]
I don't see why the xonsh channel didn't work though, considering that it looks right [here](https://anaconda.org/xonsh/prompt_toolkit)

**Comment by melund** [comment]
The v61a was something I added to the development channel to have a version without a specific bug that affected coloring on Win. It is not relevant now that v1.0.0 is released.

**Comment by melund** [comment]
Are you on x86 or x64 of anaconda?

**Comment by justbur** [comment]
x64 and I just downloaded the python3 version this morning

**Comment by melund** [comment]
I will try to clean up the channels for old packages to night.

**Comment by melund** [comment]
@justbur Somehow the windows packages of prompt-toolkit had not been copied over from 'conda-forge' channel. So conda was picking up some old packages instead. It should be fixed now. Can you try the newest versions and see if you still get the traceback?

**Comment by justbur** [comment]
I checked installing from the dev channel and using the command on the xon.sh website. 

The dev channel is working, but the default command on the xon.sh website throws a warning at the moment on startup. It looks like a bad version check. This is the warning
```
C:\Anaconda3\lib\site-packages\xonsh\shell.py:97: RuntimeWarning: prompt-toolkit version < v0.57 and may not date.
 warn(msg, RuntimeWarning)
```

**Comment by gforsyth** [comment]
@justbur -- yeah, sounds like you have `prompt_toolkit 1.0.0` installed (which is good!).  We were only checking the minor version and since `0 < 57` it throws that error.  It should be fixed on master and we're pushing a release soon.

**Comment by justbur** [comment]
Great. I'm happy to close this unless you want to leave it open.

**Comment by gforsyth** [comment]
Go ahead and close it -- there are also changes to the docs to fix the issue that are merged in and will be published as soon as we push the release.  Thanks again for reporting!

**Comment by justbur** [comment]
Thanks for the help
