### ISSUE TITLE
Update conda docs to point to conda-forge

### ISSUE THREAD

**Issue by gforsyth** [scopatz/xonsh#836]
https://xon.sh still tells users to install using

```
conda install xonsh --channel xonsh
```

which is on `0.2.6`

**Comment by melund** [comment]
Yes. We should drop the xonsh channel. I can't find a way to automatically copy the packages from conda-forge without exposing the tokens to anaconda.org.

**Comment by melund** [comment]
We can still have development builds on the xonsh channel.

**Comment by gforsyth** [comment]
Closed by #837
