### ISSUE TITLE
Add support for $SHELL

### ISSUE THREAD

**Issue by sebastien** [scopatz/xonsh#840]
Right now,  `$SHELL` is inherited from the environment (on my setup, it's currently `/usr/bin/zsh`). It should be `/usr/local/bin/xonsh` (or wherever `xonsh` is installed).

**Comment by gforsyth** [comment]
Hey @sebastien -- I think that this is the expected behavior.  `$SHELL` returns the default shell on the system as set by `chsh`.  My default is `xonsh`, which persists inside `bash` and `zsh`

```console
gil@theo ~ $ $SHELL
'/home/gil/anaconda/bin/xonsh'
gil@theo ~ $ bash
[gil@theo ~]$ echo $SHELL
/home/gil/anaconda/bin/xonsh
[gil@theo ~]$ zsh
 ~  echo $SHELL
/home/gil/anaconda/bin/xonsh
```

**Comment by sebastien** [comment]
Oh, my bad -- I should have looked this up before! More info on that here http://unix.stackexchange.com/questions/4150/does-shell-store-the-path-to-the-default-shell-in-linux and http://www.cis.rit.edu/class/simg211/unixintro/Shell.html
