### ISSUE TITLE
COMPLETIONS_MENU_ROWS not working

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#846]
Hello

My value for `COMPLETIONS_MENU_ROWS` is 5 (default). But it does not seem to work. My terminal grow until the bottom of the window and when it has reached the last line then I don't get completions anymore.

I use gnome-terminal on Ubuntu 14.04

Thank you for your help !

EDIT: I installed HEAD from the git repo. I still have the problem

EDIT2+3: I also have the problem with xtrem and Terminator (It seems Terminal independant)

**Comment by melund** [comment]
I can confirm this issue on Windows.

But I do get a single row of completions when I am on the last line of cmd.exe
```
$ xonfig
+------------------+-------+
| xonsh            | 0.2.7 |
| Python           | 3.5.1 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | 1.0.0 |
| pygments         | 2.2a0 |
| on posix         | False |
| on linux         | False |
| on arch          | False |
| on windows       | True  |
| on mac           | False |
| are root user    | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by GuillaumeLeclerc** [comment]
I also get one line of completion from time to time. I tested also with the AUR package on ArchLinux with the same result.

The current workaround is to hit Ctrl-L when I want a completion but it is quite annoying.

**Comment by GuillaumeLeclerc** [comment]
I fixed it. It comes from the new version of ptk. I'm making a PR in a minute.
