### ISSUE TITLE
Error in env setting wizard

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#847]
Hello,

Sorry for posting that many issue in a day but it's my first day using it so I may find a lot of things.

When running the environment wizard. If you mispell the value for $XONSH_HISTORY_SIZE. the wizard just crash with a `KeyError`. And you loose everything so far.

**Comment by melund** [comment]
Don't worry about it. It is nice to get fresh eyes on the project :)

**Comment by scopatz** [comment]
Just to be clear, what do you mean by "misspell"? Can you provide an example, please? Thanks for reporting @GuillaumeLeclerc!

**Comment by GuillaumeLeclerc** [comment]
typing:

`6 mohts` for example

**Comment by scopatz** [comment]
PR to fix this in #876.  Mirroring @melund, thanks for bringing this up!

**Comment by GuillaumeLeclerc** [comment]
I don't have my DockerScript that simulate a newly installed machine at work. I will try it tonight. Ping me if I forget.

**Comment by GuillaumeLeclerc** [comment]
It work perfectly on a fresh environment :) thank you !

**Comment by scopatz** [comment]
great! feel free to close this issue, then
