### ISSUE TITLE
proposal: allow directories in `BASH_COMPLETIONS`

### ISSUE THREAD

**Issue by funkyfuture** [scopatz/xonsh#848]
there are a lot of bash-completion files provided by packages on my system (Manjaro / Arch) in a directory. it would be handy to just add that directory's path to `BASH_COMPLETIONS` to effectively include them all.

also, shouldn't the configuration-wizard propose default values depending on the detected OS?

i can propably submit patches for both, but rather not very soon.

**Comment by gforsyth** [comment]
hey @funkyfuture -- i'll take a look at doing that.  for the moment, you can use a workaround like this in your `xonshrc`

```console
$BASH_COMPLETIONS[0]='/usr/share/bash-completion/bash_completion'

completions = ['pacman', 'arch', 'git', 'systemctl']

for i in completions:
    comp = '/usr/share/bash-completion/completions/{}'.format(i)
    if not os.path.isfile(comp):
        continue

    if not comp in $BASH_COMPLETIONS:
		$BASH_COMPLETIONS.append(comp)
```

**Comment by scopatz** [comment]
Hi @funkyfuture - to echo @gforsyth, thanks for the suggestion.

> also, shouldn't the configuration-wizard propose default values depending on the detected OS?

It already does this if the Env defaults are OS dependent. For example, see `BASH_COMPLETIONS` https://github.com/scopatz/xonsh/blob/master/xonsh/environ.py#L157

**Comment by funkyfuture** [comment]
@gforsyth i hope you didn't work on it. i just finished it.

**Comment by gforsyth** [comment]
No worries, I got distracted.
