### ISSUE TITLE
backtick having a strange behavior when nothing match

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#850]
Hello,

When there are not match I think backticks have a strange behavior.

```
$ echo `nothing match this .*`
["nothing match this .*"]
```

I think the correct behavior would be to return an empty list.

**Comment by melund** [comment]
No. That is the correct behaviour, and it is consistent with normal globbing. However if you backtics in python mode you do get an empty list. 

```
snail@sea ~ $ x = `Not a file*`
snail@sea ~ $ x
[]
```
We have had some dicussion about this. You can read them here: https://github.com/scopatz/xonsh/pull/783

**Comment by GuillaumeLeclerc** [comment]
I get this
```
$ x = `Not a file`
$ x
['Notafile']
```

**Comment by melund** [comment]
Oh. I thought you were working from the git master. That was exactly what I changed in the PR I referenced: https://github.com/scopatz/xonsh/pull/783

I python mode it now returns  an empty list :)

**Comment by GuillaumeLeclerc** [comment]
I switch back because of the `&` issue that does make processes go to background. It's a real dealbreaker for me

Then I suppose this is fixed in master so this issue ca be closed :) 

BTW: Do you know how to run xonsh from the git repo without installing it. I would like to contribute but I don't want to install the dev version into my /bin directory

**Comment by melund** [comment]
@GuillaumeLeclerc  PRs are more than welcome. Especially now that interest is ramping up. You run from git with `python setup.py develop`

**Comment by GuillaumeLeclerc** [comment]
`python setup.py develop` installed it. I just want to run it to test. How can I do this ?

**Comment by gforsyth** [comment]
Hey @GuillaumeLeclerc -- you can use a `virtualenv` or a conda environment to install it somewhere besides your system `/bin`.  Whichever Python environment is active when you run `python setup.py install | develop` will be the installation target.

**Comment by GuillaumeLeclerc** [comment]
@gforsyth Do you have any reference about this ?

It's not possible just to run like `python main.py` ?

**Comment by gforsyth** [comment]
I always recommend `conda`.  If you aren't using it already, install [miniconda](http://conda.pydata.org/miniconda.html).  

To create a new environment
```console
conda create -n envname python=3.5 pygments ply
```

Activate it by 
```console
source activate envname
```

Then you can install `xonsh`, confirm that it's not in system `/bin`  and run it
```console
python setup.py install
which xonsh
xonsh
```

To leave the environment
```console
source deactivate
```

> It's not possible just to run like python main.py ? 

Not to the best of my knowledge, but my knowledge is full of holes.

**Comment by scopatz** [comment]
You might be able to run xonsh just by `python main.py`, but you'd probably need `..` on the PYTHONPATH

**Comment by GuillaumeLeclerc** [comment]
I ended up doing a docker script it's perfect for my needs :)
