### ISSUE TITLE
Ctrl-Z only working once

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#855]
Hello,

This workflow make xonsh hang

```
$ vim
Ctrl-z
$fg
Ctrl-z
```

the first Ctrl-z is working (I go back to the shell). But after the second one vim is paused but what I type is ignored

This might be related to #853 since the final state is the same (I type in the terminal and only display what I type)

**Comment by adqm** [comment]
I can repeat this.  Not sure what's going on.  I should be able to take a look later today or tomorrow.

**Comment by GuillaumeLeclerc** [comment]
I will take a look at it too

**Comment by GuillaumeLeclerc** [comment]
I found out why. On my way with a fix :)
