### ISSUE TITLE
DOC: Guidelines for contributing

### ISSUE THREAD

**Issue by CJ-Wright** [scopatz/xonsh#862]
It seems that the symlink for the guidelines for contributing is not getting properly rendered/linked to by github. See: [guidelines for contributing](https://github.com/scopatz/xonsh/blob/master/CONTRIBUTING)

**Comment by scopatz** [comment]
Thanks for reporting @CJ-Wright! I think we can probably switch which is the main file and which is the symlink to get this to work.

**Comment by gforsyth** [comment]
Made it a hardlink because GitHub is weird about symlinks.

**Comment by scopatz** [comment]
> Made it a hardlink because GitHub is weird about symlinks.

I doesn't follow :)
