### ISSUE TITLE
prompt-toolkit version detected incorrectly

### ISSUE THREAD

**Issue by ypekka** [scopatz/xonsh#865]
Starting xonsh with prompt-toolkit gives following warning (running within virtualenv). Warning is incorrect based on versions below.

% /opt/xonsh/bin/xonsh
/opt/xonsh/lib/python3.5/site-packages/xonsh/shell.py:97: RuntimeWarning: prompt-toolkit version < v0.57 and may not work as expected. Please update.
  warn(msg, RuntimeWarning)

Versions:
- CPython 3.5
- Xonsh: 0.2.7
- prompt-toolkit 1.0.0

**Comment by gforsyth** [comment]
Hi @ypekka -- thanks for reporting.  This is fixed on current master.

**Comment by scopatz** [comment]
We should probably get a release out fairly soon. But I'd like for the cache stuff to go in as well as another small fix for `;`-only execution.

**Comment by melund** [comment]
And a fix for the backgrounding &

**Comment by GuillaumeLeclerc** [comment]
And fix background tasks almost nothing is working with them

**Comment by scopatz** [comment]
@ypekka I am going to close this since it is fixed on master.  Please feel free to reopen if you feel it has not been addressed.
