### ISSUE TITLE
'which' alias doesn't work on Windows

### ISSUE THREAD

**Issue by Will-W** [scopatz/xonsh#880]
The reason for this is pretty obvious - Windows doesn't have 'which'. Note though, that the command fails before aliases can even be searched, due to the unconditional evaluation of which_version().

Windows does have 'where' which could be used instead. Alternatively, a pure python xonsh builtin implementation of 'which' could be written and used cross-platform.

Given it appears this isn't the first time there's been a problem, maybe the latter is the way to go?
https://github.com/scopatz/xonsh/issues/833
https://github.com/scopatz/xonsh/issues/866

**Comment by Will-W** [comment]
Addendum: If you do have a cygwin/msys implementation of 'which' on the path, then it will run and work. Except that you'll get back Linux style paths. So, in my default config if I run "which ls" I get back "/usr/bin/ls" - which is a touch surprising. Particularly surprising as the aliases seem to indicate that 'which' is a xonsh builtin (rather than just a wrapper), and xonsh producing Linux paths on Windows isn't what you'd expect.

**Comment by melund** [comment]
If people don't have which from The MSYS/Cygwin I think it is OK that the get and error trying to run it. That it outputs Linux-like paths, is not really xonsh fault. A pure python implementation of which would be nice though.

**Comment by melund** [comment]
Oh... The reason `which` is wrapped in xonsh is to extend it to also report on xonsh aliases. I.e. you can write:
```
[xonshdev] snail@sea ~\Documents\xonsh $ which activate
activate -> ['source-cmd-keep-promt', 'activate.bat']
```

I could imagine wrapping the windows `where` command in the same way.

**Comment by adqm** [comment]
Maybe in the end we should just write it in Python (e.g., as part of #742, which I'll get back to soon).  We already keep a cache of valid command names, which may help.

**Comment by Will-W** [comment]
I think this issue could have been phrased better as 'needs better handling of errors when which binary not present. This is some sample output on my machine:

```
CAMWW1@CAMWW1-W1 ~ $ which
FileNotFoundError: [WinError 2] The system cannot find the file specified
CAMWW1@CAMWW1-W1 ~ $ which -v
FileNotFoundError: [WinError 2] The system cannot find the file specified
CAMWW1@CAMWW1-W1 ~ $ which which
FileNotFoundError: [WinError 2] The system cannot find the file specified
CAMWW1@CAMWW1-W1 ~ $ which fred
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

This is because of the error thrown from the version check. If you fixed that, you'd then get it from the attempted run.

If I catch and process the error as in the above PR, the output then looks like:
```CAMWW1@CAMWW1-W1 ~\code\xonsh $ which
usage: which [-h] [-a] [-s] [-v] arg
which: error: the following arguments are required: arg
CAMWW1@CAMWW1-W1 ~\code\xonsh $ which -v
<'which' binary not found>
CAMWW1@CAMWW1-W1 ~\code\xonsh $ which which
which -> <function which at 0x039F34F8>
CAMWW1@CAMWW1-W1 ~\code\xonsh $ which fred
'which' binary not found
```

I'd argue the latter is a lot more helpful and understandable. Of course a full Python version would fix all the problems, but this is a good interim step for those of us who are handicapped on Windows.

**Comment by melund** [comment]
@Will-W Can you test the new which on windows? 
 https://github.com/scopatz/xonsh/pull/901

**Comment by Will-W** [comment]
Looks good to me. Covers all the edge cases I could think of on a first pass.

**Comment by gforsyth** [comment]
Sounds like everyone is happy?  Please reopen if there are persisting issues.
