### ISSUE TITLE
source activate conda env does not add libraries to xonsh

### ISSUE THREAD

**Issue by CJ-Wright** [scopatz/xonsh#889]
Is `source-bash source activate conda_env` supposed to add libraries to xonsh so that they would be available?
eg.
with bash
```
christopher@deepthought:~$ sa dp_dev
discarding /mnt/work-data/other_src/anaconda/bin from PATH
prepending /mnt/work-data/other_src/anaconda/envs/dp_dev/bin to PATH
(dp_dev)christopher@deepthought:~$ ipython
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import filestore

In [2]: 
```
I was expecting to be able to do the same thing in xonsh, just without the ipython, but I get an error.
```
christopher@deepthought ~ $ source-bash source activate dp_dev
[dp_dev] christopher@deepthought ~ $ import filestore
ImportError: No module named 'filestore'
[dp_dev] christopher@deepthought ~ $ 
```

**Comment by melund** [comment]
Not a Linux user but I have worked a bit with the foreign shell code. You should only need to do : `source-bash activate env` so if it isnt working there is a bug. The features you are missing are probably because of this.

**Comment by CJ-Wright** [comment]
@melund Currently that is not the case
See #864

**Comment by melund** [comment]
Yes. I gathered as much. But it is a bug. I haven't got a Linux box, so I can't really test it. 

A wild guess would be that that it doesn't reach this line: 
https://github.com/scopatz/xonsh/blob/master/xonsh/aliases.py#L216

If it runs activate script without the 'source' command prepended it could maybe result in the behaviour you describe. You can try to add a `import pdb; pdb.set_trace()` to the function and track what happens. I would like to know what you come up with

**Comment by melund** [comment]
For the windows version (`souce-cmd`) we use `locate_binary()` https://github.com/scopatz/xonsh/blob/master/xonsh/aliases.py#L216 
to look for the scipt on the entire path, and then we use the full filename. It doesn't seem to me that `source-bash` does the same, and if the script can't be found (https://github.com/scopatz/xonsh/blob/281b29f8d77d2f5e17ad500170f81862f7a9a8e7/xonsh/aliases.py#L214) then the `source` command might not be added. 

Could you try to run the command in  same directory as the activate script is located? Does that make a difference?

**Comment by CJ-Wright** [comment]
```xonsh
christopher@deepthought /mnt/work-data/other_src/anaconda/bin $ source-bash activate dp_dev
[dp_dev] christopher@deepthought /mnt/work-data/other_src/anaconda/bin $ import filestore
ImportError: No module named 'filestore'
[dp_dev] christopher@deepthought /mnt/work-data/other_src/anaconda/bin $ source-bash activate dp_dev
[dp_dev] christopher@deepthought /mnt/work-data/other_src/anaconda/bin $ 
```

**Comment by melund** [comment]
@scopatz does this make sense to you?

**Comment by CJ-Wright** [comment]
Talking with @scopatz it seems that is a problem with the env being in python 2.

>like if in xonsh, you imported numpy 1.9, then you activated an env with numpy 1.10 and tried to reimport, Python's import caching would keep v1.9

>ah, ok
what is the problem with different python versions?
the lib I am working with should do both￼

>well if you activate an env with a Python version that you didn't start xonsh with, you won't get any of those packages

>why

>Because the PYTHONPATH is tied to the version of Python that you are using. All venvs (in conda) do is switch the PATH variable to point a different location (namely the venv dir)
activate propogates that change up to the current environment, but not the current sys.path
Remember all this actiavet stuff is supposed to be used from Bash, or another shell, there is no sys.path
venv assumes you will start a new Python process that inherits the modified environment

>so if I make a env which is python 3 but has all the same libs everything should be ok?

>Perhaps, it would take some testing
But at least you should be able to do that and then also modify the python path
err sys.path
I think vox does something like this, or should

**Comment by melund** [comment]
Ahhh. I see. This also made me a little confused in the beginning. Xonsh only loads the libraries in its own environment. You can still run python scripts, subprocs etc. in the activated environment. Can we remove the 'bug' label from this?

**Comment by gforsyth** [comment]
I think so.  Also, @CJ-Wright, it's a bit of a pain, but if you want to have multiple environments with xonsh able to import different libraries, etc... if you install `xonsh` into each ENV, then run `xonsh` after activating a given ENV that should handle what you were asking about, with the obvious caveat that you can't install it in py2

**Comment by CJ-Wright** [comment]
Ah, ok. Thank you very much! I am going to close this then.
