### ISSUE TITLE
Path compression in prompt

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#895]
Hello,

When working with deep file structure. The path displayed in the prompt can be huge. 

I was thinking about a feature to solve this, we could either:

- Only display the last directory but only the first letter of the previous ones: `/d/a/a/b/test'
- add a length in the config and design an algorithm that make the path fit into the number of chars. Example
 `/ho/gui/.c/xonsh` for `/home/guillaumeleclerc/.config/xonsh`

Tell me what you think about this

( Of course it would be mandatory, we could fill a new variable and it's up to the user to add it into his prompt or not)

**Comment by melund** [comment]
It is a good idea, and one we already have. Maybe it is not well documented. Just replace `{cwd}` in your prompt with `{short_cwd}`

**Comment by melund** [comment]
It is here: http://xon.sh/tutorial.html?highlight=short_cwd#customizing-the-prompt

**Comment by GuillaumeLeclerc** [comment]
Cool ! 

What do you think about the second option. I think it would be cool to always display the full path until there are not enough space.

**Comment by melund** [comment]
Yes. I think it is a great idea It is actually one of the reasons I don't use the short prompt. A PR would be awesome

**Comment by GuillaumeLeclerc** [comment]
I will try to implement it then

**Comment by gforsyth** [comment]
Hey @GuillaumeLeclerc, I also think this is a good idea, just a thought to add on to this (that maybe you've already had!), rather than having a static max length set in a config file, you could also have it be a percentage of the current terminal width, so it wouldn't be over-zealous in contracting the working directory if you were, say, working outside of an xserver?

Some info on grabbing terminal widths here: http://rosettacode.org/wiki/Terminal_control/Dimensions#Python

**Comment by melund** [comment]
Shutil have a function for it `shutil.get_terminal_size()`

**Comment by GuillaumeLeclerc** [comment]
@gforsyth That's a great idea. I think the option will support either chars or options as a unit.

**Comment by GuillaumeLeclerc** [comment]
Where do I add a new xonsh ENV var ?

**Comment by gforsyth** [comment]
Hey @GuillaumeLeclerc, they go in `environ.py` in both the the [default ensurers](https://github.com/scopatz/xonsh/blob/master/xonsh/environ.py#L61) and [default values](https://github.com/scopatz/xonsh/blob/master/xonsh/environ.py#L155)

**Comment by GuillaumeLeclerc** [comment]
So I have implemented a first draft that have the following policy:

- display the full name of the last directory
- for all previous parts display the same amount of letters such that the path does not exceed the target. This amount is at least one
- if it is still too big then the left part is truncated

Do you think it's a good idea ? 
should I warn the path is truncated when really too big (by adding something like `...` in front ?

**Comment by scopatz** [comment]
Thanks @GuillaumeLeclerc, this is a great idea!

**Comment by scopatz** [comment]
Feel free to reopen, if needed!
