### ISSUE TITLE
How to create a Xontrib package?

### ISSUE THREAD

**Issue by Siecje** [scopatz/xonsh#896]
I'm trying to create a ```xontrib``` package.

I have a Python module. For example ```different.py```

```Python
$PROMPT = $PROMPT.replace("{cwd}", "{short_cwd}")
```

 I can't seem to load it with the ```xontrib``` command. I've tried putting it in a ```xontrib``` folder.

Should I be able to do ```import different``` while in the same folder? 

I can do ```source different.py```

**Comment by gforsyth** [comment]
Hey @Siecje -- try the following:

`mv different.py different.xsh`

`$PYTHONPATH='/home/siecje/path/to/xontrib`

then you should be able to do an `import different` from wherever (and also within the `xontrib` folder)

**Comment by gforsyth** [comment]
Also note that if you have an existing `$PYTHONPATH` you can just append the `xontrib` location to it instead of overwriting it.

**Comment by Siecje** [comment]
Okay if it is a ```.xsh`` file then I can load it with ```xontrib load``` if I am in the same folder.

I'm trying to create an installable package and be able to ```xontrib load``` it.

I have a ```setup.py``` as follows.

```Python
try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

name = "short_cwd"

setup(
    name = name,
    version = "0.1.0",
    description = "Shortens parent directories in the prompt.",
    packages=[name],
    package_dir={name: name},
    package_data={name: ['*.xsh']},
    include_package_data=True,
)
```

With a ```short_cwd``` folder with ```short_cwd.xsh``` inside.

```short_cwd/short_cwd.xsh```
```shell
PROMPT = $PROMPT.replace("{cwd}", "{short_cwd}")
```

I also tried with a ```short_cwd/__init__.py```.

After installing it I cannot load it with ```xontrib load```

```shell
p/mine/
(xonsh) cody@cody-ubuntu16 ~/Desktop/mine $ xontrib load short_cwd
(xonsh) cody@cody-ubuntu16 ~/Desktop/mine $ xontrib load short-cwd
(xonsh) cody@cody-ubuntu16 ~/Desktop/mine $ xontrib load short_cwd.short_cwd
```

However importing it does work
```shell
(xonsh) cody@cody-ubuntu16 ~/Desktop/mine $ from short_cwd import short_cwd
(xonsh) cody@cody-ubuntu16 ~/D/mine $
```

Is this normal? And users can just add the import to their ```.xonshrc``` file?

Is ```xontrib load``` only for the ```xontrib``` that come with ```xonsh```?

**Comment by scopatz** [comment]
Hi @Siecje - sorry about some of the confusion here.  [`xontribs`  is an implicit namespace package like mentioned in the docs](https://github.com/scopatz/xonsh/blob/master/docs/tutorial_xontrib.rst#structure).  Basically, this means that the dir called `xonrib` is where the xontribs should go, and that this is shared among all projects that have xontribs.  This `xontrib` package name is different from your project name.

Here is what your setup.py should look like to get this to work:

```python
try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

name = "short_cwd"

setup(
    name = name,
    version = "0.1.0",
    description = "Shortens parent directories in the prompt.",
    packages=['xontrib'],
    package_dir={'xontrib': 'xontib'},
    package_data={'xontrib': ['*.xsh']},
    include_package_data=True,
)
```

The problem was that you were applying the project name (`short_cwd`) where you should apply the package name (`xontrib`). I hope this helps.

**Comment by scopatz** [comment]
Also note, you can write your xontribs in either Python or xonsh. In this case though, I think that xonsh makes more sense.

**Comment by Siecje** [comment]
@scopatz Thanks that works! And the docs do explain it. How would it work if you had a Python package instead of a module?

Here is the working example

```shell
cody@cody-ubuntu16 ~/why $ tree
.
├── setup.py
└── xontrib
    └── short_cwd.xsh

1 directory, 2 files
cody@cody-ubuntu16 ~/why $ cat setup.py 
try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

name = "short_cwd"

setup(
    name = name,
    version = "0.1.0",
    description = "Shortens parent directories in the prompt.",
    packages=['xontrib'],
    package_dir={'xontrib': 'xontrib'},
    package_data={'xontrib': ['*.xsh']},
    include_package_data=True,
)
cody@cody-ubuntu16 ~/why $ cat xontrib/short_cwd.xsh 
$PROMPT = $PROMPT.replace("{cwd}", "{short_cwd}")
```

Would you merge a pull request with this example in the ```xontrib``` tutorial docs?

**Comment by Siecje** [comment]
Also how to you load a ```xontrib``` extension automatically?

I tried adding the following to ```.xonshrc```.

```shell
xontrib load short_cwd
$(xontrib load short_cwd)
```

**Comment by scopatz** [comment]
> How would it work if you had a Python package instead of a module?

Say you had:

```
.
├── setup.py
└── xontrib/
    └── mypkg/
        └── __init__.py
        └── helper.py
        └── short_cwd.xsh
```

You would then do something like:

```python
setup(
    name = name,
    version = "0.1.0",
    description = "Shortens parent directories in the prompt.",
    packages=['xontrib', 'xontrib.mypkg'],
    package_dir={'xontrib': 'xontrib', 'xontrib.mypkg': 'xontrib/mypkg'},
    package_data={'xontrib': ['*.xsh'], 'xontib.mypkg': ['*.xsh']},
    include_package_data=True,
)
```

This follows the normal distutils or setuptools rules for adding package data.

> Would you merge a pull request with this example in the xontrib tutorial docs?

Absolutely!

> Also how to you load a xontrib extension automatically?

You should be able to add `xontrib load short_cwd` to your xonshrc.  This is discussed [here](https://github.com/scopatz/xonsh/blob/master/docs/tutorial_xontrib.rst#loading-xontribs).  Please let us know if this doesn't work.
