### ISSUE TITLE
KeyboardInterrupt is never cleared

### ISSUE THREAD

**Issue by mbollmann** [scopatz/xonsh#91]
When a KeyboardInterrupt occurs, it seems to appear in every further exception raised:

```bash
bollmann@underberg ~/repositories/xonsh master >>> # ^C here
bollmann@underberg ~/repositories/xonsh master >>> [1,2,3][4]
Traceback (most recent call last):
  File "/home/bollmann/repositories/xonsh/xonsh/shell.py", line 154, in cmdloop
    super(Shell, self).cmdloop(intro=intro)
  File "/usr/lib/python3.4/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bollmann/repositories/xonsh/xonsh/shell.py", line 111, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/home/bollmann/repositories/xonsh/xonsh/execer.py", line 110, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
IndexError: list index out of range
```

Repeat the last command and it will show the KeyboardInterrupt every time, although CTRL+C was never pressed again.

Additionally, if you do ^C more than once, it will show the stacktrace for KeyboardInterrupt for each time you pressed it.

This happens both when you do ^C on an empty line, and when you use it to actually interrupt a running process/function.

**Comment by scopatz** [comment]
> Additionally, if you do ^C more than once, it will show the stacktrace for KeyboardInterrupt for each time you pressed it.

That is weird. That doesn't happen on my machine.  I can hit Crtl-c as many times as I want and I always just get a new empty line. Are you on mac @mbollmann? I forgot....

I am sure that there is some readline hack we can add to fix this.

**Comment by scopatz** [comment]
The fix might be to call `RL_LIB.rl_reset_line_state()` whenever an KeyboardInterrupt happens.  Can you play around with this and see if it works?

**Comment by SavinaRoja** [comment]
I would imagine that this was due to the recursion for `Shell.cmdloop()`. Each additional error would extend the Traceback of error-handling.

**Comment by scopatz** [comment]
here's hoping.

**Comment by mbollmann** [comment]
I'm not sure what changed in the meantime (there's no commit referring to this issue), but with the current master this doesn't happen for me anymore.

**Comment by scopatz** [comment]
Great! Thanks again for reporting @mbollmann
