### ISSUE TITLE
Default Ubuntu .bashrc breaks ForeignShellFunctionAlias

### ISSUE THREAD

**Issue by ned2** [scopatz/xonsh#915]
The default Ubuntu user `.bashrc` contains this snippet at the start of the file, which means that any functions defined below it will be populated into the `aliases` dictionary, but will fail on calling them since the sourcing the `.bashrc` script won't result in the functions being defined. 

```bash
# If not running interactively, don't do anything                                                                                                                                                                    
case $- in
    *i*) ;;
      *) return;;
esac
```
I began with the Ubuntu `.bashrc` some time ago, appending my customisations at the end, forgetting about what might be up above; so it took me a while to work out what was going on. Not sure if it makes sense to try and fix or not, but perhaps it could be worth documenting somewhere since I'm sure I'm not the only one basing their `.bashrc` off Ubuntu's default.

**Comment by scopatz** [comment]
Hi @ned2, thanks for reporting this!  I think that there is not much that we can do about this to make such Bash functions work, short of rewriting the bashrc in memory.  I am kind of loathe to do that, though.  

However, I think that documenting this is a good solution.  Would you mind putting in a PR to xonsh that adds some docs to this effect? I'd *really* appreciate it! Thanks!

**Comment by ned2** [comment]
Sure thing. I'll put something together. I see a Linux Guide in the docs that looks like a good place for it to live.

**Comment by scopatz** [comment]
Yup, that'd be the place!

**Comment by ned2** [comment]
Just submitted PR #951

**Comment by scopatz** [comment]
Feel free to close this now that the PR has been merged @ned2
