### ISSUE TITLE
Error parsing some nested expressions

### ISSUE THREAD

**Issue by adqm** [scopatz/xonsh#919]
I'm not sure exactly what is going on here, but I noticed some interesting parsing issues.  For example:

```
hartz@thinky-515 ~ $ @($(which screens).strip())
.................... 
  File "<string>", line None
SyntaxError: <xonsh-code>:1:0: ('code: @(',)
```

```
hartz@thinky-515 ~ $ @($(which screens))
<ERROR STEMMING FROM "\n" ON THE END OF THE COMMAND NAME>
```

```
hartz@thinky-515 ~ $ x = $(which screens)
hartz@thinky-515 ~ $ @(x.strip())
<RUNS OKAY!>
```

I think I have an idea of what is going wrong and how to fix, but figured I'd report first.  Of course, if anyone else wants to jump in and take this, that'd be fine, too :)

**Comment by scopatz** [comment]
This is a new one on me, but looks suspiciously similar to #913

**Comment by scopatz** [comment]
Though I think they might actually be different

**Comment by scopatz** [comment]
Hey @adqm - is this closable?

**Comment by adqm** [comment]
Ah, yes indeed.  Sorry I forgot!
