### ISSUE TITLE
Error during use of xonsh scripts

### ISSUE THREAD

**Issue by SavinaRoja** [scopatz/xonsh#92]
Was testing the use of xonsh for scripting and ran into an error. Would love to help fix if this is a current bug or limitation.

With a basic script, `xonsh-script.sh`:

    #!/usr/bin/xonsh
    
    echo "echo"
    print("print()")

when I execute this script I get the following error from argparse:

    usage: xonsh [-h] [-c COMMAND]
    xonsh: error: unrecognized arguments: ./xonsh-script.sh

Is this expected?

**Comment by scopatz** [comment]
Hi @SavinaRoja - this is a current limitation, and your help would be most appreciated!  We don't have a way for xonsh to take a file as in input argument right now.  It should be a relatively simple fix in `xonsh/main.py`

**Comment by scopatz** [comment]
Feel free to close @SavinaRoja if #95 works for you.

**Comment by SavinaRoja** [comment]
If you execute the script wthout shebang a la `xonsh script.sh`, things work just fine.

But with the shebang and execution a la `./script.sh`, I get the following error:

```
Traceback (most recent call last):
  File "/home/pablo/workspace/xonsh/xonsh/execer.py", line 118, in _parse_ctx_free
    mode=mode, debug_level=self.debug_level)
  File "/home/pablo/workspace/xonsh/xonsh/parser.py", line 271, in parse
    debug=debug_level)
  File "/home/pablo/workspace/venvs/xonsh-dev/lib/python3.4/site-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/home/pablo/workspace/venvs/xonsh-dev/lib/python3.4/site-packages/ply/yacc.py", line 921, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/home/pablo/workspace/xonsh/xonsh/lexer.py", line 66, in token
    self.last = self.lexer.token()
  File "/home/pablo/workspace/venvs/xonsh-dev/lib/python3.4/site-packages/ply/lex.py", line 384, in token
    newtok = self.lexerrorf(tok)
  File "/home/pablo/workspace/xonsh/xonsh/lexer.py", line 414, in t_error
    self._error(msg, t)
  File "/home/pablo/workspace/xonsh/xonsh/lexer.py", line 76, in _error
    self.errfunc(msg, location[0], location[1])
  File "/home/pablo/workspace/xonsh/xonsh/parser.py", line 281, in _lexer_errfunc
    self._parse_error(msg, self.currloc(line, column))
  File "/home/pablo/workspace/xonsh/xonsh/parser.py", line 341, in _parse_error
    raise err
SyntaxError: <xonsh-code>:1:1: Invalid token '#'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pablo/workspace/venvs/xonsh-dev/bin/xonsh", line 12, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/pablo/workspace/xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/home/pablo/workspace/xonsh/xonsh/main.py", line 38, in main
    code = shell.execer.compile(code, mode='exec', glbs=shell.ctx)  
  File "/home/pablo/workspace/xonsh/xonsh/execer.py", line 84, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/home/pablo/workspace/xonsh/xonsh/execer.py", line 62, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/home/pablo/workspace/xonsh/xonsh/execer.py", line 142, in _parse_ctx_free
    returnline=True, lexer=self.parser.lexer)
  File "/home/pablo/workspace/xonsh/xonsh/tools.py", line 69, in subproc_toks
    if toks[-1].type == 'SEMI':
IndexError: list index out of range
Exception ignored in: <bound method Shell.__del__ of <xonsh.shell.Shell object at 0xb7017b6c>>
Traceback (most recent call last):
  File "/home/pablo/workspace/xonsh/xonsh/shell.py", line 102, in __del__
  File "/home/pablo/workspace/xonsh/xonsh/shell.py", line 65, in teardown_readline
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2199, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2132, in _find_spec
TypeError: 'NoneType' object is not iterable
```

**Comment by wrywerytwreywery** [comment]
Woof.  It seems not to like comments in general in exec mode.  Putting any comment (not just a shebang) on the first line, it breaks like that.

Comments elsewhere seem to be able to put it into an infinite loop, depending on where they are placed.

**Comment by scopatz** [comment]
I am looking into it.

**Comment by scopatz** [comment]
What is weird is that these all work:

```console
scopatz@athenaie ~ $ python -c '# I am a comment'
scopatz@athenaie ~ $ exec('# I am a comment')
scopatz@athenaie ~ $ execx('# I am a comment')
```

**Comment by scopatz** [comment]
Ok.  Try it now.  It works for me locally.

**Comment by SavinaRoja** [comment]
That test script works now. However when I modified it to include a comment, it hangs. Does this happen for you with the following?

```
#!/usr/bin/env xonsh

echo "echo"
print("print")

#This is a comment
for i, x in enumerate("xonsh"):
    print(i, x)
```

**Comment by wrywerytwreywery** [comment]
So it looks like the following works:
```
print(7)
print(13) # comment
```

But the following fails:
```
print(7) # comment
print(13)
```

Is it possible that comments somehow don't end with a newline?  The regex for `t_ignore_COMMENT` looks fine, but it doesn't seem to be referenced anywhere in the code.  Is that something that `ply` is taking care of automatically?  If so, is it possible that it is using `DOTALL` and `MULTILINE`?  In that case, I'm pretty sure the `t_ignore_COMMENT` regex would match until the end of the whole string, not just until the end of the line.

I can try to fix.

**Comment by scopatz** [comment]
It is possible that it is eating the newline.... If you could try, that'd be great.

**Comment by wrywerytwreywery** [comment]
Okay, I think I have something (at least that fixes the simple test case from above).  Will push to a new PR.

**Comment by SavinaRoja** [comment]
@wrywerytwreywery That seems to have fixed the comment issue. Then of course I decide to try this and it hung:

```
#!/usr/bin/env xonsh

echo "echo"
print("print")

var = """This is a multiline \
string that causes trouble.\
"""

print(var)

#This is a comment
for i, x in enumerate("xonsh"):
    print(i, x)
```

**Comment by scopatz** [comment]
I think that is my fault.  I don't think there is support for line continuation at all.

**Comment by scopatz** [comment]
This would probably be a simple fix in the lexer again, like with comments but with the following regex: `'\\$'`

**Comment by SavinaRoja** [comment]
@scopatz So it seems that the trouble occurs with or without the "\" precluding the standard "\n". Also presents trouble with docstrings.

```
#!/usr/bin/env xonsh

"""
This script is by SavinaRoja
"""

#This is a comment
for i, x in enumerate("xonsh"):
    print(i, x)
```

**Comment by scopatz** [comment]
OK.  This is because multiline strings are not high enough in the precedence in the lexer then.

**Comment by scopatz** [comment]
So this is actually an error withe the multiline regex. I am too sleepy to debug it right now sadly...

**Comment by scopatz** [comment]
If you want to take a stab, that'd be awesome.

**Comment by wrywerytwreywery** [comment]
I'll give this one a shot tonight.

**Comment by wrywerytwreywery** [comment]
I have a plan for fixing this, but it will involve some heavy work in the lexer (breaking up `string_literal` into several tokens), so I won't be able to get to it tonight.  I'll try to find some time in the next day or two to implement.

**Comment by scopatz** [comment]
I believe that these issues have all been cleared up @SavinaRoja.  Please reopen if you are still having trouble!  Thanks!
