### ISSUE TITLE
Up arrow history search stops accepting new history if __xonsh_history__.buffersize = 0

### ISSUE THREAD

**Issue by JohnLunzer** [scopatz/xonsh#935]
I changed it yesterday morning and then my "Up arrow history" froze there. When I removed the ```__xonsh_history__.buffersize = 0``` line from my .xonshrc my "Up arrow history" started saving commands again.

As I've been working on my getHistory() command I've been able to monitor the history in XONSH_DATA_DIR and everything is fine there, it's saving everything exactly as I would expect it. 

So these must be two different mechanisms and when __xonsh_history_.flush() occurs after every command it's not additionally appending the command to the "Up arrow history", which I can only assume is only taking place when xonsh exits successfully.

**Comment by scopatz** [comment]
Hi @JohnLunzer - the "Up arrow history" this is a feature of the readline and prompt-toolkit shells. They each have their own mechanisms for loading history into their history buffers, see:

* https://github.com/scopatz/xonsh/blob/master/xonsh/readline_shell.py#L382
* https://github.com/scopatz/xonsh/blob/master/xonsh/ptk/history.py

The history is read in separately from how it is saved.  The potential trip up is that the `history` command will also go read in the history file of the current session if you ask for data that has already been flushed.

**Comment by JohnLunzer** [comment]
This ```files = hist.gc.unlocked_files()``` is common code between them. Here is the bug, I don't know where but when ```__xonsh_history__.buffersize = 0``` the history files are not being unlocked when xonsh exits successfully.

**Comment by GuillaumeLeclerc** [comment]
I have been facing a maybe related problem. Sometimes the history (ptk) is not displayed when I press up arrow. Typing one character and deleting it re-enable the feature for me

**Comment by scopatz** [comment]
Hi @JohnLunzer - The reason for the lock is so that xonsh history garbage collection (gc) from one xonsh process doesn't remove the history from another xonsh process that is also currently running. It is not meant, per se to restrict reading history from such files, though I believe that the way things are presently implemented it does that as well.

**Comment by JohnLunzer** [comment]
If the lock status was not aimed at history then I am of the opinion that it should not be checked for any history commands, right now we're throwing away valid history. I believe this can be fixed rather easily by renaming (all references of) ```hist.gc.unlocked_files()``` to ```hist.gc.files()``` with a new parameter `locked=True` as default. ```hist.gc.files(locked=False)``` would mimic the original functionality (which we wouldn't be using). This should be a pretty straightforward change without unwanted side effects.
