### ISSUE TITLE
Pylint not passing in existing code base

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scopatz/xonsh#939]
Hello,

I did as advised in the contribution guide and it seems the code base does not follow pylint and it leads to a lot of errors.

Are we still recommending pylint or this should be removed from the docs ?

**Comment by scopatz** [comment]
Well, the code that your write in PRs should lint OK.  Getting the whole code base to lint is aspirational. We include many pieces of code from outside of the project that  we have yet to fix up or tell the linter to ignore.

**Comment by GuillaumeLeclerc** [comment]
Ok thanks for the answer !
