### ISSUE TITLE
Unable to install xonsh in pyenv managed local Python installation 

### ISSUE THREAD

**Issue by ned2** [scopatz/xonsh#950]
I'm trying to install xonsh into a local Python installation. This installation is accessed via pyenv, so I'm just running `pip install xonsh` as my command, which resolves to the Python installation at   `/home/nejl/.pyenv/versions/3.5.1/`. When I do this, I get the following error from pip:

```
Installing Jupyter kernel spec...
    error: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

I tried using the `--prefix` option to tell pip where the Python installation lives but the same thing happens. I also tried `--root` to do the same thing (not quite sure about what the difference amounts to) and this had the following result:

````
Exception:
Traceback (most recent call last):
  File "/home/nejl/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/home/nejl/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/home/nejl/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/home/nejl/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/req/req_install.py", line 928, in install
    with open(inst_files_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'home/nejl/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh-0.2.7-py3.5.egg-info/installed-files.txt'
````
For some reason the path not found is missing an initial '/'. But even if I massage that in via pdb I get the same error. 

I've only just started using pyenv, so I'm a little unfamiliar with managing these local installations, so may be missing something obvious.

**Comment by melund** [comment]
Hi @ned2 
This is probably a issue with the jupyter kernel install hook. https://github.com/scopatz/xonsh/blob/master/setup.py#L59

I almost never use `pip` so I am just guessing now. Can you try to specify a `--user` option to `pip install`?

**Comment by ned2** [comment]
Yep, turns out I can successfully install xonsh using `pip install --user xonsh`. However this installs xonsh into `~/.local` rather than into the pyenv version which pip is running from. Now that I've thought a bit about how I want things configured on my machine, I'm actually happy with this; I can't currently think of a reason why I'd want xonsh installed directly in one local Python version but not another. In fact I think I'll also be avoiding pip for installing xonsh since I'm now running the.

However, I can certainly imagine others wanting to install xonsh locally using pyenv, so this seems like it would be good to fix.

**Comment by ned2** [comment]
Actually, one problem with installing xonsh using the --user flag (either with pip or setup.py) is that the shebang line in `~/.local/bin/xonsh` is hardcoded to the location of the python installation pyenv was running. eg  `#!/home/nejl/.pyenv/versions/3.5.1/bin/python3.5`. Which 

Is there a reason why it's not something more flexible like `#!/usr/bin/env python3`, which will be less likely to break as Python installations in the system are changed?

**Comment by scopatz** [comment]
Hi @ned2 - do you have setuptools installed? The whole point of us using setuptools (which accounts for about 40% of our startup time) is that it lets xonsh work in venvs.  Also, do you have jupyter installed in your venv?

**Comment by ned2** [comment]
@scopatz pyenv primarily manages entire Python installations (but using them kinda like virtualenvs). So `#!/home/nejl/.pyenv/versions/3.5.1` is a complete Python 3.5.1 installation rather than a virtualenv. Although you can also install and manage virtualenvs with pyenv; but I don't have any in my current setup.

I do have setuptools installed in that Python installation. I did not have jupyter installed already, but doing so does not fix the problem.

**Comment by scopatz** [comment]
Ahh I see - I have never used pyenv (clearly) and personally use conda for managing my python versions.  But I understand the problem, now, I think.  We should get this working.

**Comment by scopatz** [comment]
Ok @ned2, can you give #990 a spin?  It should now respect --prefix, however, even if that breaks - xonsh should still install.

**Comment by ned2** [comment]
Nice! `python setup.py install` successfully installs xonsh into the local installation that pyenv points to. Using the `--prefix` option seems to work also, but I don't even need to use that, as it now _just works_ :)

Not sure if there's a way to test `pip install xonsh` without a new release with this change being pushed to PyPI, but I imagine that might also just work now.

**Comment by scopatz** [comment]
Great! I have gone ahead and merged that.  Feel free to reopen this issue if problem crop up again.
