### ISSUE TITLE
Feature: history all

### ISSUE THREAD

**Issue by JohnLunzer** [scopatz/xonsh#952]
I would like to move [this discussion](https://groups.google.com/forum/#!topic/xonsh/VVIPFQSXitI) to here so it is more well documented.

I recently came up on the code in [history.py for getting unlocked history files](https://github.com/scopatz/xonsh/blob/master/xonsh/history.py#L104).

I have a concern moving forward. I have a custom piece of code for loading history files that ignores lock status. I do this because of a current bug in xonsh (#935). Shells crash or are killed all the time and sometimes after a long running period with lots of history. 

I am questioning why history would need to be concerned with lock status at all, if we are doing read only?

For "history all" this would be very important. All history is valid regardless of lock status. Thoughts are welcome.

**Comment by scopatz** [comment]
Just to repeat my answer from #935, lock status is mainly to prevent garbage collection by other processes.

**Comment by JohnLunzer** [comment]
Closing, duplicate of #572.
