### ISSUE TITLE
Segmentation faults and other special return codes should print corresponding messages

### ISSUE THREAD

**Issue by kirbyfan64** [scopatz/xonsh#955]
If an application like this:

```c
int main() {
    char* p = 0;
    return *p; // Uh-oh!
}
```

segfaults, Bash shows the following:

```
ryan@DevPC-LX:~/langtest/xonsh$ ./seg
Segmentation fault (core dumped)
ryan@DevPC-LX:~/langtest/xonsh$ 
```

But Xonsh shows:

```
ryan@DevPC-LX ~/langtest/xonsh $ ./seg

ryan@DevPC-LX ~/langtest/xonsh $
```

See:

http://tldp.org/LDP/abs/html/exitcodes.html

and:

https://en.wikipedia.org/wiki/Unix_signal#POSIX_signals

Would you be interested in a pull request for this?

**Comment by scopatz** [comment]
Thanks for pointing this out @kirbyfan64! We'd absolutely be interested in a PR to this effect.
