### ISSUE TITLE
`Shell.cmdloop` vulnerable to recursion-depth limit

### ISSUE THREAD

**Issue by SavinaRoja** [scopatz/xonsh#96]
While I was working on #92 , I noticed that `Shell.cmdloop` was recursive and looked subject to crashing if the recursion limit was exceeded. Tested just to be thorough (that was fun...)

**Comment by scopatz** [comment]
hahah I am glad you actually tested it.  Yeah. it *should* be a `while True: ... break`.  But I was lazy.  PR welcome here.  Note that the `builtins.__xonsh_exit__` is a boolean flag for whether or not to exit.  This could be used to break out of this loop.
