### ISSUE TITLE
Recent xonsh forcing $SHELL_TYPE = best?

### ISSUE THREAD

**Issue by adqm** [scopatz/xonsh#961]
Just as of pulling a couple of minutes ago, xonsh seems to be forcing `$SHELL_TYPE='best'` (which I definitely do not want because I disagree about the definition of best), despite my having `$SHELL_TYPE='readline'` in my `.xonshrc`.

Can confirm my `.xonshrc` is being run.  But my `$SHELL_TYPE` setting is not being honored.

**Comment by scopatz** [comment]
I noticed something like this too, with 'random' always selecting ptk. Definitely a bug.
