### ISSUE TITLE
Xonsh instantly kills C programs that read input from stdin

### ISSUE THREAD

**Issue by kirbyfan64** [scopatz/xonsh#976]
For instance, save the following to `si.c`:

```c
#include <stdio.h>

int main() {
    char buf[1024];
    for(;;){
        printf("\n>>> ");
        if (!fgets(buf, 1024, stdin)) break;
    }
    return 0;
}
```

Watch what happens when I run it in Xonsh:

```
ryan@DevPC-LX ~/langtest/xonsh $ clang si.c -o si
ryan@DevPC-LX ~/langtest/xonsh $ ./si

>>> 
*[7] stopped: ./si & (20197)
ryan@DevPC-LX ~/langtest/xonsh $ ./si

>>> 
*[8] stopped: ./si & (20199)
ryan@DevPC-LX ~/langtest/xonsh $ ./si

>>> 
*[9] stopped: ./si & (20201)
ryan@DevPC-LX ~/langtest/xonsh $ ./si

>>> 
*[10] stopped: ./si & (20203)
ryan@DevPC-LX ~/langtest/xonsh $ 
```

This works normally in Bash. No clue what the issue is...

If I run it under `rlwrap` (via `rlwrap ./si`), it works perfectly. In addition, other methods of input (like Python's `input()`) work normally.

**Comment by kirbyfan64** [comment]
But wait, it gets better. :)

If I run `./si` enough times (usually around 8) and then run `printf` with no arguments, the following happens:

```
ryan@DevPC-LX ~/langtest/xonsh $ ./si

>>> 
*[7] stopped: ./si & (22575)
ryan@DevPC-LX ~/langtest/xonsh $ printf
/usr/bin/printf: missing operand
Try '/usr/bin/printf --help' for more information.


```

Yup, it froze...

**Comment by scopatz** [comment]
@kirbyfan64 - are you on master? this seems related to the job control stuff.

**Comment by scopatz** [comment]
Thanks for reporting!

**Comment by GuillaumeLeclerc** [comment]
I also think it is a bug related to job control.

On the other side I think it is normal to stop any process in the background that read or write to the tty. This is why `SIGTTOU` and `SIGTIN` signals exist. But we are not implementing it. What you see should be fixed on master

__Reference__: http://curiousthing.org/sigttin-sigttou-deep-dive-linux

**Comment by scopatz** [comment]
Thanks for that reference, @GuillaumeLeclerc! Super useful.  Job control is something we are definitely need to get right soon.

**Comment by kirbyfan64** [comment]
I can confirm that this is fixed on master. Sorry for the noise!

**Comment by scopatz** [comment]
No worries, @kirbyfan64! Thanks for reporting.  Please feel free to close this issue.
