### ISSUE TITLE
Add a label for prompt-toolkit-specific issues?

### ISSUE THREAD

**Issue by adqm** [scopatz/xonsh#978]
@scopatz, can we add a label "ptk" or similar to apply to issues/PRs that are specific to prompt toolkit?  For symmetry, maybe also a label for readline?  This might make it easier to tell at a glance which part of the system an issue corresponds to.

**Comment by scopatz** [comment]
Great idea!  I'll make the new labels now....

**Comment by scopatz** [comment]
Done. I made them the same color since they shouldn't typically be used together.

**Comment by adqm** [comment]
Great; thanks!

**Comment by scopatz** [comment]
Also added some platform specific labels, windows, etc, for good measure.

**Comment by adqm** [comment]
Ah, good.  If we wanted to really go overboard, we could add lexer, parser, core, xontrib, etc.  But those will probably be easy enough to distinguish via the issue titles.

**Comment by scopatz** [comment]
Yeah.  I can definitely see how the xontib one would be useful, but we can wait until it becomes a problem.
